### ISSUE TITLE
getServerSideProps() example does not work.

### ISSUE THREAD

**Issue by james-elicx** [cloudflare/next-on-pages#10]
Hello,

The `getServerSideProps()` example in the readme does not seem work. Having copied it character for character and tried building, it throws the following error:

```
Build optimization failed: found page without a React Component as default export in
pages/ssr
```

I am only able to get a build to succeed when I remove the `experimental-edge` runtime config from both the page itself and the next.config.js file. It appears to occur whenever you specify the `experimental-edge` runtime in either the next config or the page.

From what I can tell, a Next.js app cannot be built when using `getServerSideProps` in pages while the `experimental-edge` runtime is specified.

If you were able to manage to have `getServerSideProps` work when specifying the `experimental-edge` runtime, would you please be able to provide a source code example, as I am unable to get it to work at all with any of my trial and error?

**Comment by GregBrimble** [comment]
Did you remember to add the `export default Home;` at the bottom? It should work!

**Comment by moodiest** [comment]
> Did you remember to add the `export default Home;` at the bottom? It should work!

Yes, the page's component is the default export.

I created a new next.js app with create-next-app and copied over the example code, but when I specify `experimental-edge` in the page or in the next.config.js, I get the error.

Spent some time trying it in my projects as well and it's the same error.

Do you have an example application where it works that I can compare against?

**Comment by james-elicx** [comment]
After the problems I was experiencing with dev mode/building Next.js 13 (using the new appDir) on Windows with webpack (vercel/next.js#41806), I thought I would give this another spin on Linux, and it builds as expected.

Apologies for this false alarm, I'm going to assume this was just another bug I had building with webpack on windows.
