### ISSUE TITLE
ERROR: Unknown functions manifest version. Expected 3 but found 4

### ISSUE THREAD

**Issue by Anietz** [cloudflare/next-on-pages#125]
This build error affects both old and new deployment. Attached a screenshot.

<img width="649" alt="Screenshot 2023-03-21 at 12 29 52 PM" src="https://user-images.githubusercontent.com/24476838/226593844-ee9792e3-ac5e-4a70-ac40-709e47d1163f.png">

**Comment by dario-piotrowicz** [comment]
Hi @Anietz, thank you very much for the issues

But I am not able to reproduce this, could you please provide more details? Like what next.js version you're using, what vercel cli version you have, what your code does (only static, uses app dir, etc...), and whatever else you think could be related to the issue.

If possible, if you could provide the code itself in a repo or something that would be extremely helpful 🙏

**Comment by mistermantas** [comment]
Also experiencing this on cf pages

▲ Detected Next.js version: 12.1.4
Node is v16.15.1

**Comment by dario-piotrowicz** [comment]
> not a logical default for cf pages to use a version that doesn't immediately build, I think...
> 
yeah... hopefully it'll change at some point soon-ish: https://github.com/cloudflare/pages-build-image/discussions/1

**Comment by dario-piotrowicz** [comment]
> 
> ▲ Detected Next.js version: 12.1.4
> 

Sorry could you clarify? is this the log you see on Pages? (and I assume you're using 16.15.1 locally?) have you then changed/set your `NODE_VERSION` in the dashboard?

**Comment by mistermantas** [comment]
> > ▲ Detected Next.js version: 12.1.4
> 
> Sorry could you clarify? is this the log you see on Pages? (and I assume you're using 16.15.1 locally?) have you then changed/set your `NODE_VERSION` in the dashboard?

it is the log from Pages and that was the version of Node I was using in Pages. I had set an env variable for NODE_VERSION but not NEXT_VERSION - setting both fixed the issue as I said

**Comment by dario-piotrowicz** [comment]
sorry I misread the log and thought you were getting two different node versions 😓  (one locally and one from pages)

**Comment by dario-piotrowicz** [comment]
I am not sure I know this `NEXT_VERSION` env variable and what it is used for 😕 

anyways, if I understand correctly, are things working and this issue can be closed? 🙂

**Comment by Anietz** [comment]
@dario-piotrowicz I am using `NODE_VERSION`  `16.13.0` and `NEXT_VERSION` `12.1.4`. 
Setting this values on the dashboard seems not to fix the issue

**Comment by dario-piotrowicz** [comment]
@Anietz I'd want to look more into this but as I mentioned I could not reproduce the issue, could you please help me with some more details? some reproduction steps? or even some code? that would be extremely helpful :pray:

**Comment by Anietz** [comment]
@dario-piotrowicz I see that when I changed the build config on the dashboard from `npx @cloudflare/next-on-pages --experimental-minify` to `next build && next export` it actually works. 
I think this issue can be closed now

**Comment by dario-piotrowicz** [comment]
Glad to hear you've solved the issue :slightly_smiling_face: 

Just to make sure you're aware, `next export` is going to generate your app as a static site (so no SSR or edge bindings, etc...), hopefully this is what you want :slightly_smiling_face::+1:
