### ISSUE TITLE
Error during build

### ISSUE THREAD

**Issue by arthurmchr** [cloudflare/next-on-pages#14]
After following the bare minimal exemple provided [on cloudflare blog](https://blog.cloudflare.com/next-on-pages/), I get an error during the build process (online and in local) : 
```
Expected "=>" but found "(
index.func.js:200:110
UnhandledPromiseRejectionWarning: Error: Build failed with 1 error:
```

When looking at the code, it comes from this bad function definition :
`async renderErrorToResponse(e,t){let{res:...`

I have defined env variable for NODE_VERSION and setup the flags.

**Comment by tj-kev** [comment]
Try the solution in #8.

**Comment by arthurmchr** [comment]
Thanks it worked
