### ISSUE TITLE
404 errors in dynamic pages and api routes on Cloudflare Pages with Next.js

### ISSUE THREAD

**Issue by xyba1337** [cloudflare/next-on-pages#144]
I’m having an issue with dynamic routes and API routes in Cloudflare Pages. Currently, everything inside the api route and any request to a dynamic page is returning a 404 error. I’m using the latest version of Next.js without the app directory, and I used the normal Next.js (not the static, html export) preset when creating my project in Cloudflare Pages. All the other pages work fine.

Affected:
![Screenshot_1](https://user-images.githubusercontent.com/62798507/229824060-d0acd6be-88c5-4220-a0bc-b2595f8b0a9d.png)

I’ve also set my environment variables to use NODE_VERSION: 16.18.0 because the build process won’t work without it. See more: [https://github.com/cloudflare/next-on-pages/issues/9](url). Despite this, I’m still facing issues with the dynamic routes and api routes.

**Comment by dario-piotrowicz** [comment]
@xyba1337 did you try running the application locally? does it work there?

meaning: `npx @cloudflare/next-on-pages --experimental-minify`
followed by `npx wrangler pages dev .vercel/output/static`
?

can you by any chance share your code?

**Comment by xyba1337** [comment]
I just figured out that cloudflare currently only supports the nextjs edge runtime.
I'll need to look for an alternative which supports nodejs. Sorry for wasting your time

**Comment by dario-piotrowicz** [comment]
@xyba1337 not a problem, sorry you could not use Cloudflare pages for your project 😢
