### ISSUE TITLE
Consistently use the `join` node path utility to construct paths

### ISSUE THREAD

**Issue by dario-piotrowicz** [cloudflare/next-on-pages#154]
We should be using [`join`](https://nodejs.org/api/path.html#pathjoinpaths) to construct all our paths consistently in a platform independent way.

In places we even mix `join` with manually constructed paths such as the following:
https://github.com/cloudflare/next-on-pages/blob/2d72906c52e5c3a4cebd92a6311be5ba98b4cb98/bin/index.js#L9

it should instead be
```js
 join(__dirname, '..', 'dist', 'index.js'), 
```

We should fix all such paths.

**Comment by abhishek276533** [comment]
Hey, @dario-piotrowicz I checked into this one and found that we had only used two of the places. 
<img width="325" alt="image" src="https://user-images.githubusercontent.com/62441572/231886848-9a342600-3382-47fe-bb94-012729becb35.png">
<img width="455" alt="image" src="https://user-images.githubusercontent.com/62441572/231886883-257df5ac-5e34-413f-aa2d-55ce69d9fdca.png">

**Comment by dario-piotrowicz** [comment]
Hi @abhishek276533 sorry if the issue description is confusing, I meant that paths should not be created manually (as in `"dirNameA/dirNameB/file"` ) but should be created using join (as in `join('dirNameA', 'dirNameB', 'file')`)

We actually do this all over the place, for example see:
https://github.com/cloudflare/next-on-pages/blob/91f766f8d0a62b41c4745565527acdf77de6d456/src/buildApplication/buildMetadataFiles.ts#L13

and
https://github.com/cloudflare/next-on-pages/blob/91f766f8d0a62b41c4745565527acdf77de6d456/src/buildApplication/buildMetadataFiles.ts#L29

and
https://github.com/cloudflare/next-on-pages/blob/91f766f8d0a62b41c4745565527acdf77de6d456/src/buildApplication/buildVercelOutput.ts#L100

all these places (and many many more) should be built using `join` (meaning that they shouldn't have any `/` there)

(the two instances that you're showing mix `join` with constructed paths so they are also incorrect but are by far not the only ones)
