### ISSUE TITLE
[🐛 Bug]: buildSuccess check crushes with bad error message

### ISSUE THREAD

**Issue by dario-piotrowicz** [cloudflare/next-on-pages#156]
### Cli version

0.7.0

### Description

In the following check:
https://github.com/cloudflare/next-on-pages/blob/9834066c889453bd1d3feb620892209c45a3482a/src/buildApplication/buildApplication.ts#L28-L38

added in PR #145 

`err` can be `undefined` causing the following error:
![Screenshot 2023-04-06 at 23 14 55](https://user-images.githubusercontent.com/61631103/230503653-23a6640f-37e5-4aad-b8a5-510c302d1463.png)

we should use optional chaining and provide a nice default error message instead of crushing

**Comment by abhishek276533** [comment]
Hi, @dario-piotrowicz I would like to work on this, could you assign this to me

**Comment by dario-piotrowicz** [comment]
Hi @abhishek276533 thank you very much 🙂👍 

As the default message I would go with something a bit more helpful like:
```
Error: the Vercel build failed, please see the Vercel logs above for more information
```
(since above/before this error message there should be some logs from Vercel indicating why the build failed)

___

Do you have an app that causes the Vercel build to fail? let me know if you need one 🙂 

___

PS: you don't have to but if you want consider adding a unit test for `buildApplication` where you can mock `buildVercelOutput` to throw, check that the correct warning is logged and also check that the rest of the operations (`deleteNextTelemetryFiles`, etc...) are not run (again via mocking)

**Comment by abhishek276533** [comment]
Hey @dario-piotrowicz have modified the Error message.
<img width="916" alt="image" src="https://user-images.githubusercontent.com/62441572/231538280-de6e29ac-bb41-4e5f-93bd-08576c8b22a7.png">

However, I'm currently learning how to write unit tests using `vitests`, so I can't upload the unit tests just yet.😅

**Comment by dario-piotrowicz** [comment]
@abhishek276533 sure looks great thanks! 😃 

If you want then feel free to open a PR, don't feel forced to implement the test if you don't want 🙂 (or you can even do it in a separate PR if you prefer)

if you need some help with vitest please let me know, I am not that experienced with it either but I am sure that we can figure things out 🙂👍
