### ISSUE TITLE
[⚡ Feature]: Is there any plan to support Plug'n'Play features in yarn berry?

### ISSUE THREAD

**Issue by noobnooc** [cloudflare/next-on-pages#159]
### Description

I am currently working on developing an app using yarn pnp. However, I encountered an issue when attempting to deploy my app to Cloudflare Pages. I received an error message stating that `@cloudflare/next-on-pages doesn't support Plug'n'Play features from yarn berry.` 

Is there are any plan to support yarn pnp in the future? Alternatively, is there any way to deploy an app using pnp in the current version, such as by unpluging certain packages?

### Would you like to help?

- [ ] Would you like to help implement this feature?

**Comment by dario-piotrowicz** [comment]
Hi @noobnooc I'm very sorry for the late reply 😓 🙇  (I wanted to check this sooner but never got around to it)

It seems that the Cloudflare Pages team is planning on updating the build image to support yarn 3 (https://discord.com/channels/595317990191398933/1104067231991742504) and I believe that should happen fairly soon

As soon as it's updated I __think__ we just need to remove this piece of code: https://github.com/cloudflare/next-on-pages/blob/360d9f07dd38d434bf035d8f784962a00f02fb5d/src/buildApplication/packageManagerUtils.ts#L37-L43

And yarn pnp should just work 🙂 

So support for pnp should be coming soon 🙂, I'll keep you updated here on the progress

(PS: until we properly support yarn pnp I doubt that there are workarounds you could try)

**Comment by madjam002** [comment]
I've been able to get Yarn PnP working by just separating out the `vercel build` and `next-on-pages` bundle, like so:

```
mkdir -p .vercel
echo '{"projectId":"_","orgId":"_","settings":{}}' > .vercel/project.json
YARN_NODE_LINKER=pnp vercel build
next-on-pages --skip-build
```

I also run `vercel build` with the yarn command no-oped because I couldn't find a way to disable the `yarn install` that `vercel build` does.
