### ISSUE TITLE
[⚡ Feature]: Improve CLI logs style

### ISSUE THREAD

**Issue by dario-piotrowicz** [cloudflare/next-on-pages#162]
### Description

Currently the CLI prints a wall of text which is ok but not like super readable:
![Screenshot 2023-04-07 at 19 14 30](https://user-images.githubusercontent.com/61631103/230657625-dbd05c67-0ae3-4de6-9cbd-78fdd884ef4b.png)

This could be improved to make some logs stand out and also to maybe make more clear which lines come from Vercel and which not (or maybe the `▲ vs ⚡️` is enough?)

Important aspects that I think that would make the text more readable are:
 - add spacing where needed (we currently remove `\n`s at the start/end of logs we should improve this by allowing extra spacing)
 - having the `Building Completed.` and `Generated '.vercel/output/static/_worker.js'.` messages green (or something like that) so that it's more clear that things are going well
 - having error messages red (or something like that) so that it is clear when something's gone wrong

**Comment by mtctxd** [comment]
![image](https://user-images.githubusercontent.com/94276879/230792077-8cd9c73e-49ae-4d9d-bd34-4ab68e28b804.png)

**Comment by dario-piotrowicz** [comment]
Sorry @mtctxd what are you showing there? is that the output you see when using the CLI? 😕

**Comment by mtctxd** [comment]
@dario-piotrowicz No just showing how it might look with color changed.

**Comment by dario-piotrowicz** [comment]
Ah ok sorry, you didn't comment anything so I thought you were saying that on some terminal it looks like that or something (which yeah was quite surprising! 😁)

Yeah that looks pretty nice, one thing I would do is make sure that the "Vercel" icon stays white 🙂 

Another thing we'd need to do is to separate the lines, like for example you can see there that the warning is right below the build completed log, ideally I think things should be accordingly spaced out 🙂 (something like this [warning message](https://github.com/cloudflare/next-on-pages/blob/9834066c889453bd1d3feb620892209c45a3482a/src/buildApplication/generateGlobalJs.ts#L29-L38) but we'd change the logging code so that you're not forced to add those empty string log statements 😓)

___

Regarding the Vercel output I was thinking that it would be awesome if maybe we could make it like separated so that it's more clear that we're running that under the hood, for example [boxing it via ink] (https://github.com/vadimdemedes/ink/blob/master/media/box-borderStyle.jpg) that would be very very neat in my opinion 🤩 , but it may be overkill to introduce `ink`, plus I haven't really used it before so I don't know if you can simply box some lines and keep adding lines inside the box as they come in (so it's just an idea, may be not worth it 🤷)

**Comment by dario-piotrowicz** [comment]
@mtctxd Where you sharing the colors because you'd like to help with this? 😃

**Comment by james-elicx** [comment]
This discussion about colors reminds me of something I read on Twitter last month. It was about Turborepo and why more color was not the default. One of the engineers [wrote](https://twitter.com/anthonysheww/status/1638312664320602112) that "colors in terminals are special characters and CI providers haven't historically been able to render them correctly. It's a safer default to not use colors in CI."

I'm bringing it up as I wonder if this might be something worth considering. Perhaps we could check for the `CI` environment variable to hide color output, as someone else in the Twitter thread suggested.

**Comment by mtctxd** [comment]
@GregBrimble yea I did not know if it is ok to use, I was using ANSI codes before, but maybe if there already existing solution, it is better for sure to use it.
@dario-piotrowicz Can you say if this logs are ok? At least colors. Because some of the logs are actualy maybe not errors, but it is still there, for example `Vercel CLI 28.0.2`. And yea, I did not included any more spaces, just refactored loggers a bit.

![image](https://user-images.githubusercontent.com/94276879/231280252-3c281671-0f1f-4188-9377-607fe464425f.png)

**Comment by mtctxd** [comment]
@dario-piotrowicz Here I just logged longest error i could found.
![image](https://user-images.githubusercontent.com/94276879/231281026-736461d0-4ce7-40de-9b2f-66aedfceabc0.png)

**Comment by dario-piotrowicz** [comment]
@mtctxd yeah I think it looks nice 😄 

Regarding the colors I think here:
https://github.com/cloudflare/next-on-pages/blob/9834066c889453bd1d3feb620892209c45a3482a/src/cli.ts#L72-L96

`cliLog` should display things with the terminal default color, `cliWarn` should be yellow/orange (or something like that) and `cliWarn` should be red.

We'd be still missing the green for successfull messages, for that I would maybe add a `cliSuccess` function or allow the `cliLog` (alongside the others as well) to take an optional argument in which you can provide options to override the colors.

Anyways this is just how I would go about it I think, if you have other ideas that's totally fine, feel free to implement this as you think is best 🙂

**Comment by mtctxd** [comment]
Yea, I did same. Anyway will look forward to add `ink` somehow. I will try to do it myself, but as I understand I can look for any library for it, right?

**Comment by dario-piotrowicz** [comment]
@mtctxd yeah of course any (well maintained) library would do 🙂, but as I mentioned above about `ink` (or anything similar to that) I was just thinking that it would be quite cool if we could have like the Vercel output contained in a sort of box to show more clearly that it is like a separate process (but still showing the logs printed real time, not waiting for all the output and print it all at once), but that's by no means necessary and if it requires complicated code/logic might not be worth it.

So yeah do what you can and see if you can get to something cool without too much complications, if you can't just colors and spacing is already a very nice improvement 😄 

___

About additional spaces (again this is how I thought about it but feel free to do it however you think is best 🙂) I thought that we'd just change this function:
https://github.com/cloudflare/next-on-pages/blob/9834066c889453bd1d3feb620892209c45a3482a/src/cli.ts#L104-L109

So that we can do something like:
```ts
cliLog(
`
  this is my log
`
);
```
and it would not strip await the extra newlines at the start and end so the caller is the one who needs to care about those, this feels like the most straightforward solution but I wonder if it could make some logs awkward to write.

Alternatively we could have an option to the `cliLog`, `cliWarn` and `cliError` that makes the function add spacing for you, like for example:
```ts
cliLog(`this is my log`, { spaced: true });
```

**Comment by dario-piotrowicz** [comment]
should be all done, thanks @mtctxd 😃
