### ISSUE TITLE
Try not to install `vercel` every time

### ISSUE THREAD

**Issue by eve0415** [cloudflare/next-on-pages#17]
Hello.

Are there any reasons why it trys to run `npm install -D vercel` every time?
I have already installed via `yarn add -D @cloudflare/next-on-pages vercel`.
Also, it is marked as peer-dependency which I don't think `next-on-pages` should install it for them.
Or, check `package.json` for `vercel` before installing.

Anyway I get some errors running the command.

```
Error: spawn npm ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn npm',
  path: 'npm',
  spawnargs: [ 'install', '-D', 'vercel' ]
}

Node.js v18.12.0
```

node: 18.12.0
next-on-pages: 0.1.0

**Comment by hckhanh** [comment]
I agreed with you. I don't know why this command always run and failed

**Comment by egegungordu** [comment]
Same here

**Comment by Shervanator** [comment]
I also get issues with this, we have a yarn 2 monorepo with patched packages, and each time it attempts to install vercel causes a failure as it seems to be using npm under the hood, ```
⚡️ @cloudflare/next-to-pages CLI
⚡️
⚡️ Installing 'vercel' CLI...
⚡️
▲ npm
▲  ERR! code EUNSUPPORTEDPROTOCOL
▲
▲ npm ERR! Unsupported URL Type "patch:": patch:@react-native-community/slider@2.0.9#../../patches/@react-native-community+slider+2.0.9.patch
▲
▲
▲ npm
▲  ERR! A complete log of this run can be found in:
▲ npm ERR!     /Users/shervinaflatooni/.npm/_logs/2022-11-15T05_49_33_439Z-debug-0.log
▲
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "undefined".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```

**Comment by merry75** [comment]
same issue

**Comment by merry75** [comment]
same as above running in monorepo and getting 

⚡️ @cloudflare/next-to-pages CLI
⚡️
⚡️ Installing 'vercel' CLI...
⚡️
node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:288:12)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn npm',
  path: 'npm',
  spawnargs: [ 'install', '-D', 'vercel' ]
}

**Comment by hanford** [comment]
refs https://github.com/cloudflare/next-on-pages/issues/6

**Comment by raisedadead** [comment]
Created a PR that makes it easier.

**Comment by matteo-hertel** [comment]
I had the same issue, in a yarn workspace mono repo the default usage of `npm` creates the `package-lock.json` too failing the CI

I dug 5 mins in the source code and I found an easy workaround: given the docs install both `vercel` and `next-on-pages` as a dev dependency, I've changed the build script to
`"build:workers": "vercel build && next-on-pages --experimental-minify --skip-build"`

that did the trick, hope is useful to anybody else while all the PRs are getting merged and proper support for yarn is added
