### ISSUE TITLE
[⚡ Feature]: Document that pnpm is not supported by pages

### ISSUE THREAD

**Issue by dario-piotrowicz** [cloudflare/next-on-pages#171]
pnpm is not supported by Cloudflare Pages build system so, if you try deploying an app and it needs to be built by Cloudflare (meaning that it is not a direct upload) then if it uses pnpm the build will fail.

(note: you can use pnpm locally without issue)

There are some simple solutions to this: https://github.com/cloudflare/next-on-pages/issues/52#issuecomment-1480345217
(but ultimately pnpm should get built-in support in Cloudflare Pages at some point, hopefully soon, see https://github.com/cloudflare/pages-build-image/discussions/1)

We should probably document the above somewhere so that developers can see this clearly instead of seeing their build failing and getting confused by it.

**Comment by AntoineKM** [comment]
Update they should probably mention that it will probably having issue with Next.js and Build System v1 but stable with v2 ! 
![image](https://github.com/cloudflare/next-on-pages/assets/54948363/0f53816e-c15d-419f-be13-87d776a55ee9)
