### ISSUE TITLE
[🐛 Bug]: Unexpected behavior on default locale

### ISSUE THREAD

**Issue by Magicloud** [cloudflare/next-on-pages#172]
### Cli version

v0.8.0

### Next.js related information

21:41:40.779	    Operating System: 21:41:40.780	      Platform: linux 21:41:40.780	      Arch: x64 21:41:40.780	      Version: #1 SMP Sun Jan 10 15:06:54 PST 2016 21:41:40.780	    Binaries: 21:41:40.780	      Node: 16.19.1 21:41:40.780	      npm: 8.19.3 21:41:40.780	      Yarn: 1.22.4 21:41:40.780	      pnpm: N/A 21:41:40.781	    Relevant packages: 21:41:40.781	      next: 13.2.4 21:41:40.781	      eslint-config-next: 13.2.4 21:41:40.781	      react: 18.2.0 21:41:40.781	      react-dom: 18.2.0 21:41:40.781	 21:41:41.368	warn  - Latest canary version not detected, detected: "13.2.4", newest: "13.3.1-canary.6". 21:41:41.368	        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue. 21:41:41.369	        Read more - https://nextjs.org/docs/messages/opening-an-issue

### Vercel version

28.18.5

### Description

Per [doc](https://nextjs.org/docs/advanced-features/i18n-routing#sub-path-routing), "The default locale does not have a prefix."

Right now I have a project with only one locale (en), which works as expected in Vercel. But in Cloudflare, `/anything` does not work at all. I have to use `/en/anything`.

### Reproduction

I cannot give you the full source, which is private. This is the locale settings:

```
module.exports = {
  i18n: {
    defaultLocale: "en",
    locales: ["en"],
  },
  localePath: "./src/locales",
}

```

### Would you like to help?

- [ ] Would you like to help fixing this bug?

**Comment by james-elicx** [comment]
Hey there, the internationalized routing (`i18n`) option in `next.config.js` is not currently supported.
