### ISSUE TITLE
[🐛 Bug]: `NextResponse.rewrite(new URL(xxx))` does not work correctly.

### ISSUE THREAD

**Issue by noobnooc** [cloudflare/next-on-pages#177]
### Cli version

v0.8.0

### Next.js related information

     Operating System:       Platform: darwin       Arch: arm64       Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000     Binaries:       Node: 19.6.1       npm: 9.4.0       Yarn: 3.5.0       pnpm: N/A     Relevant packages:       next: 13.3.0       eslint-config-next: 13.3.0       react: 18.2.0       react-dom: 18.2.0  warn  - Latest canary version not detected, detected: "13.3.0", newest: "13.3.1-canary.6".         Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.         Read more - https://nextjs.org/docs/messages/opening-an-issue

### Vercel version

28.18.5

### Description

I want to change the default API prefix `/api` of the nextjs to another one, so I created `middleware.ts` in `src`, and fill with following content:

```ts
import { NextRequest, NextResponse } from "next/server";

export const config = {
  matcher: "/v1/:path*",
};

export function middleware(request: NextRequest) {
  if (request.nextUrl.pathname.startsWith("/v1")) {
    return NextResponse.rewrite(
      new URL(`/api${request.nextUrl.pathname}`, request.url)
    );
  }
}
```

When I test with `next dev` command, it's all correct. when I fetch `/v1/hello` will get the response that `/api/hello` responses. But when I test with `yarn dlx @cloudflare/next-on-pages` and `yarn dlx wrangler pages dev .vercel/output/static --compatibility-flag=nodejs_compat` command, the `/v1/hello` will responses with `200` status code but with empty body.

I don't know is it a bug from `next-on-pages`, or it's I used incorrectly. Or is there another way to implement my requiremet.

### Would you like to help?

- [ ] Would you like to help fixing this bug?

**Comment by dario-piotrowicz** [comment]
Hi @noobnooc thanks for the issue 🙂, it seems like the middleware rewrites generate a header called `x-middleware-rewrite` which we are not checking on our side, that needs to be added to the worker request handling.

We'll need to fix this (we should be able to fix it soon-ish I think), so I don't think your code is wrong in any way.

___

As a temporary solution you could manually do the rewriting in your middleware, something like this:
```ts
import { NextRequest, NextResponse } from "next/server";

export const config = {
  matcher: "/v1/:path*",
};

export async function middleware(request: NextRequest) {
  const apiRoute = `${request.nextUrl}`.replace('/v1/', '/api/');
  const apiResponse = await fetch(apiRoute);
  return apiResponse;
}
```
would that work for you?
