### ISSUE TITLE
next@13.0.3 react route is throwing error 'Worker threw exception'

### ISSUE THREAD

**Issue by RuttvikKheni** [cloudflare/next-on-pages#19]
I am following same as readme file of next-on-pages(https://github.com/cloudflare/next-on-pages).
if I run it in local machine and it's working and SSR is also works.

but, when I deploy code that time backend is working but react route is throwing 1101(Worker threw exception).

this is root react file and I am sharing local and after deploy output with you.

root route code
![image](https://user-images.githubusercontent.com/72619482/201469022-c8d959c3-028f-40e1-9c25-562839b6c598.png)

local server
![image](https://user-images.githubusercontent.com/72619482/201469028-2eff4b4c-b831-4dbe-976a-557eb1c62a34.png)

after deploy
![image](https://user-images.githubusercontent.com/72619482/201468970-df6b5191-3611-4e18-b039-96e2d89e1f56.png)

**Comment by jnmsl** [comment]
You have probably missed step 8.

> In the Pages project Settings > Functions > Compatibility Flags, add the transformstream_enable_standard_constructor and streams_enable_constructors flags. These will not be necessary once they graduate to be on by default on 2022-11-30's compatibility date.

**Comment by harshil-bodara** [comment]
> You have probably missed step 8.
> 
> > In the Pages project Settings > Functions > Compatibility Flags, add the transformstream_enable_standard_constructor and streams_enable_constructors flags. These will not be necessary once they graduate to be on by default on 2022-11-30's compatibility date.

Yes, you are right issue fixed.
Thanks for help @jnmsl
