### ISSUE TITLE
Feedback on `--experimental-minify`

### ISSUE THREAD

**Issue by GregBrimble** [cloudflare/next-on-pages#2]
If you spot a bug relating to the `--experimental-minify` feature, please describe below!

**Comment by Shadid12** [comment]
Hi I am encountering the following error when I run `npx @cloudflare/next-on-pages --experimental-minify` 

ERROR: Unknown functions manifest version. Expected 2 but found 1. 

My API route looks like this 
```js
// pages/api/hello.js

export const config = {
  runtime: 'experimental-edge',
}

export default function handler(req, res) {
  res.status(200).json({ name: 'John Doe' })
}

```

When I take out the `runtime: 'experimental-edge',` code block it builds.

**Comment by smol-honk** [comment]
I'm also getting this with no api routes.

**Comment by Illizian** [comment]
I am seeing the following issue:

```
10:15:12.680 | ▲ Traced Next.js server files in: 825.075ms
10:15:12.680 | ▲
10:15:13.417 | ▲ Created all serverless functions in: 736.559ms
10:15:13.417 | ▲
10:15:13.528 | ▲ Collected static files (public/, static/, .next/static): 7.18ms
10:15:13.528 | ▲
10:15:13.590 | ▲ Build Completed in .vercel/output [17s]
10:15:13.591 | ▲
10:15:13.671 | ⚡️
10:15:13.671 | ⚡️
10:15:13.671 | ⚡️ Completed 'npx vercel build'.
10:15:13.672 | ⚡️
10:15:14.192 | ⚡️ ERROR: Unknown functions manifest version. Expected 2 but found 1.
10:15:14.193 | ⚡️ Please report this at https://github.com/cloudflare/next-on-pages/issues.
10:15:14.217 | Failed: build command exited with code: 1
10:15:15.291 | Failed: an internal error occurred
```

I have configured our Pages deployments to use the commands described in this repo:
```
10:14:51.816 | Executing user command: npx @cloudflare/next-on-pages --experimental-minify
```

This could be a simple issue of not having updated Next? We've moved from Vercel with an existing application - you can see the PR here - https://github.com/NorfolkDev/nordevcon-website/pull/110

**Comment by vbuser2004** [comment]
Experiencing the same output and failed build as @Illizian and @Shadid12 above.

Using:
Nextjs: 12.2.5
Node: 16.14.1

**Comment by jdddog** [comment]
I'm receiving the error below. It doesn't occur without the `--experimental-minify` flag. Using Next.js version 13.0.6 and I think that code in question might come from Chakra UI.

```node
▲ Build Completed in .vercel/output [47s]
▲ 
⚡️
⚡️
⚡️ Completed 'npx vercel build'.
⚡️
✘ [ERROR] Unexpected "??"

    ../../../../../tmp/zgx24y3l0ah/institution/[id].func.js:33578:53:
      33578 │         (null == N || N(m), QA(m.currentTarget) && $ ?? Y && Z());
            ╵                                                      ~~

/home/user/.npm/_npx/39e2fd552b408994/node_modules/esbuild/lib/main.js:1575
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 1 error:
../../../../../tmp/zgx24y3l0ah/institution/[id].func.js:33578:53: ERROR: Unexpected "??"
    at failureErrorWithLog (/home/user/.npm/_npx/39e2fd552b408994/node_modules/esbuild/lib/main.js:1575:15)
    at /home/user/.npm/_npx/39e2fd552b408994/node_modules/esbuild/lib/main.js:1033:28
    at /home/user/.npm/_npx/39e2fd552b408994/node_modules/esbuild/lib/main.js:978:67
    at buildResponseToResult (/home/user/.npm/_npx/39e2fd552b408994/node_modules/esbuild/lib/main.js:1031:7)
    at /home/user/.npm/_npx/39e2fd552b408994/node_modules/esbuild/lib/main.js:1143:14
    at responseCallbacks.<computed> (/home/user/.npm/_npx/39e2fd552b408994/node_modules/esbuild/lib/main.js:680:9)
    at handleIncomingPacket (/home/user/.npm/_npx/39e2fd552b408994/node_modules/esbuild/lib/main.js:735:9)
    at Socket.readFromStdout (/home/user/.npm/_npx/39e2fd552b408994/node_modules/esbuild/lib/main.js:656:7)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: {
        column: 53,
        file: '../../../../../tmp/zgx24y3l0ah/institution/[id].func.js',
        length: 2,
        line: 33578,
        lineText: '        (null == N || N(m), QA(m.currentTarget) && $ ?? Y && Z());',
        namespace: '',
        suggestion: ''
      },
      notes: [],
      pluginName: '',
      text: 'Unexpected "??"'
    }
  ],
  warnings: []
}
```

**Comment by Cherry** [comment]
It seems like `--experimental-minify` is actually inflating the build when simply duplicating pages from the initial `create-next-app`. Filed an issue about this and the general size output at https://github.com/cloudflare/next-on-pages/issues/47.

**Comment by shiyuhang0** [comment]
> With our project (which was started from https://github.com/shadowwalker/next-pwa) `npx @cloudflare/next-on-pages` works without the `--experimental-minifynode` but when I add it there are 6 errors, all of which are just `Unexpected "??"'`. Looks like it's the same error as mentioned above: [#2 (comment)](https://github.com/cloudflare/next-on-pages/issues/2#issuecomment-1343612209)
> 
> However Cloudflare Pages doesn't work, even without the `--experimental-minifynode` because of `Error: Failed to publish your Function. Got error: Error: Script startup exceeded CPU time limit.`. I can't figure out how to fix this yet but think it's unrelated to `@cloudflare/next-on-pages`
> 
> # Details
> ## package.json
> ```
> {
>   "name": "my-nextjs-pwa",
>   "version": "0.1.0",
>   "private": true,
>   "scripts": {
>     "dev": "next dev",
>     "build": "next build",
>     "start": "next start",
>     "lint": "next lint"
>   },
>   "dependencies": {
>     "@chakra-ui/react": "^2.4.4",
>     "@emotion/react": "^11.10.5",
>     "@emotion/styled": "^11.10.5",
>     "@fontsource/poppins": "^4.5.10",
>     "@fontsource/roboto": "^4.5.8",
>     "@next/font": "13.0.7",
>     "@types/node": "18.11.17",
>     "@types/react": "18.0.26",
>     "@types/react-dom": "18.0.9",
>     "eslint": "8.30.0",
>     "eslint-config-next": "13.0.7",
>     "framer-motion": "^6.5.1",
>     "i18next": "^22.4.6",
>     "next": "13.0.7",
>     "next-pwa": "^5.6.0",
>     "react": "18.2.0",
>     "react-dom": "18.2.0",
>     "react-i18next": "^12.1.1",
>     "react-icons": "^4.7.1",
>     "sass": "^1.57.1",
>     "typescript": "4.9.4"
>   },
>   "devDependencies": {
>     "autoprefixer": "^10.4.13",
>     "postcss": "^8.4.20",
>     "tailwindcss": "^3.2.4",
>     "vercel": "^28.10.1"
>   }
> }
> ```
> 
> ## Error log
> ```
> ▲ 
> ▲ Traced Next.js server files in: 3.012s
> ▲ 
> ▲ Created all serverless functions in: 1.329s
> ▲ 
> ▲ Collected static files (public/, static/, .next/static): 4.611ms
> ▲ 
> ▲ Build Completed in .vercel/output [53s]
> ▲ 
> ⚡️
> ⚡️
> ⚡️ Completed 'npx vercel build'.
> ⚡️
> ✘ [ERROR] Unexpected "??"
> 
>     ../../../../../tmp/8ua1xv070ol/overview/[id].func.js:7139:53:
>       7139 │         (null == a || a(e), rh(e.currentTarget) && u ?? v && y());
>            ╵                                                      ~~
> 
> ✘ [ERROR] Unexpected "??"
> 
>     ../../../../../tmp/8ua1xv070ol/myData.func.js:6625:53:
>       6625 │         (null == a || a(e), rh(e.currentTarget) && u ?? v && y());
>            ╵                                                      ~~
> 
> ✘ [ERROR] Unexpected "??"
> 
>     ../../../../../tmp/8ua1xv070ol/index.func.js:6725:53:
>       6725 │         (null == a || a(e), rh(e.currentTarget) && u ?? v && y());
>            ╵                                                      ~~
> 
> ✘ [ERROR] Unexpected "??"
> 
>     ../../../../../tmp/8ua1xv070ol/profile.func.js:6806:53:
>       6806 │         (null == a || a(e), rh(e.currentTarget) && u ?? v && y());
>            ╵                                                      ~~
> 
> ✘ [ERROR] Unexpected "??"
> 
>     ../../../../../tmp/8ua1xv070ol/profile/settings.func.js:6757:53:
>       6757 │         (null == a || a(e), rh(e.currentTarget) && u ?? v && y());
>            ╵                                                      ~~
> 
> ✘ [ERROR] Unexpected "??"
> 
>     ../../../../../tmp/8ua1xv070ol/profile/addCarer.func.js:7058:53:
>       7058 │         (null == a || a(e), rh(e.currentTarget) && u ?? v && y());
>            ╵                                                      ~~
> 
> /home/stijn/.npm/_npx/39e2fd552b408994/node_modules/esbuild/lib/main.js:1575
>   let error = new Error(`${text}${summary}`);
>               ^
> 
> Error: Build failed with 6 errors:
> ../../../../../tmp/8ua1xv070ol/index.func.js:6725:53: ERROR: Unexpected "??"
> ../../../../../tmp/8ua1xv070ol/myData.func.js:6625:53: ERROR: Unexpected "??"
> ../../../../../tmp/8ua1xv070ol/overview/[id].func.js:7139:53: ERROR: Unexpected "??"
> ../../../../../tmp/8ua1xv070ol/profile.func.js:6806:53: ERROR: Unexpected "??"
> ../../../../../tmp/8ua1xv070ol/profile/addCarer.func.js:7058:53: ERROR: Unexpected "??"
> ...
>     at failureErrorWithLog (/home/stijn/.npm/_npx/39e2fd552b408994/node_modules/esbuild/lib/main.js:1575:15)
>     at /home/stijn/.npm/_npx/39e2fd552b408994/node_modules/esbuild/lib/main.js:1033:28
>     at /home/stijn/.npm/_npx/39e2fd552b408994/node_modules/esbuild/lib/main.js:978:67
>     at buildResponseToResult (/home/stijn/.npm/_npx/39e2fd552b408994/node_modules/esbuild/lib/main.js:1031:7)
>     at /home/stijn/.npm/_npx/39e2fd552b408994/node_modules/esbuild/lib/main.js:1143:14
>     at responseCallbacks.<computed> (/home/stijn/.npm/_npx/39e2fd552b408994/node_modules/esbuild/lib/main.js:680:9)
>     at handleIncomingPacket (/home/stijn/.npm/_npx/39e2fd552b408994/node_modules/esbuild/lib/main.js:735:9)
>     at Socket.readFromStdout (/home/stijn/.npm/_npx/39e2fd552b408994/node_modules/esbuild/lib/main.js:656:7)
>     at Socket.emit (node:events:513:28)
>     at addChunk (node:internal/streams/readable:315:12) {
>   errors: [
>     {
>       detail: undefined,
>       id: '',
>       location: {
>         column: 53,
>         file: '../../../../../tmp/8ua1xv070ol/index.func.js',
>         length: 2,
>         line: 6725,
>         lineText: '        (null == a || a(e), rh(e.currentTarget) && u ?? v && y());',
>         namespace: '',
>         suggestion: ''
>       },
>       notes: [],
>       pluginName: '',
>       text: 'Unexpected "??"'
>     },
>     {
>       detail: undefined,
>       id: '',
>       location: {
>         column: 53,
>         file: '../../../../../tmp/8ua1xv070ol/myData.func.js',
>         length: 2,
>         line: 6625,
>         lineText: '        (null == a || a(e), rh(e.currentTarget) && u ?? v && y());',
>         namespace: '',
>         suggestion: ''
>       },
>       notes: [],
>       pluginName: '',
>       text: 'Unexpected "??"'
>     },
>     {
>       detail: undefined,
>       id: '',
>       location: {
>         column: 53,
>         file: '../../../../../tmp/8ua1xv070ol/overview/[id].func.js',
>         length: 2,
>         line: 7139,
>         lineText: '        (null == a || a(e), rh(e.currentTarget) && u ?? v && y());',
>         namespace: '',
>         suggestion: ''
>       },
>       notes: [],
>       pluginName: '',
>       text: 'Unexpected "??"'
>     },
>     {
>       detail: undefined,
>       id: '',
>       location: {
>         column: 53,
>         file: '../../../../../tmp/8ua1xv070ol/profile.func.js',
>         length: 2,
>         line: 6806,
>         lineText: '        (null == a || a(e), rh(e.currentTarget) && u ?? v && y());',
>         namespace: '',
>         suggestion: ''
>       },
>       notes: [],
>       pluginName: '',
>       text: 'Unexpected "??"'
>     },
>     {
>       detail: undefined,
>       id: '',
>       location: {
>         column: 53,
>         file: '../../../../../tmp/8ua1xv070ol/profile/addCarer.func.js',
>         length: 2,
>         line: 7058,
>         lineText: '        (null == a || a(e), rh(e.currentTarget) && u ?? v && y());',
>         namespace: '',
>         suggestion: ''
>       },
>       notes: [],
>       pluginName: '',
>       text: 'Unexpected "??"'
>     },
>     {
>       detail: undefined,
>       id: '',
>       location: {
>         column: 53,
>         file: '../../../../../tmp/8ua1xv070ol/profile/settings.func.js',
>         length: 2,
>         line: 6757,
>         lineText: '        (null == a || a(e), rh(e.currentTarget) && u ?? v && y());',
>         namespace: '',
>         suggestion: ''
>       },
>       notes: [],
>       pluginName: '',
>       text: 'Unexpected "??"'
>     }
>   ],
>   warnings: []
> }
> ```

met the same error. Do you solve it?

**Comment by jdddog** [comment]
@Stijn-B and @shiyuhang0 I might have had the same problem when deploying to Cloudflare Pages. I was using the Direct Uploads feature though and it wasn't very forthcoming with a detailed error message, it just said "no deployment available".

**Comment by mattddean** [comment]
I updated the version of esbuild used by next-on-pages and got a more descriptive error message for the `✘ [ERROR] Unexpected "??"` error.

With version 0.17.14 of esbuild, the error message is `✘ [ERROR] Cannot use "??" with "&&" without parentheses`.

I suspect this may something to do with the fact that `npx vercel build` has already "built" the JavaScript files, seemingly without respecting the ?? and && rule, and so this error comes about trying to run esbuild on already built JS files. I wonder if there is a bug in what `npx vercel build` uses to build is JS files that produces JS that doesn't follow this ?? and && rule.

The issue can be reproduced by cloning this commit and running the commands in the readme.

```sh
git clone git@github.com:mattddean/next-pages.git
cd next-pages
git checkout e5e8b258164e04053e86932093af77184a77d545
```

**Comment by dario-piotrowicz** [comment]
> met the same error Error: Failed to publish your Function. Got error: Error: Script startup exceeded CPU time limit. when I deploy pages with prisma. Do you solve it?

@shiyuhang0 the startup cpu time limit is a different issue, we're aware of it and will soon provide a solution for it 🙂 (PS: but it might still happen if your app needs to perform lengthy operations when handling requests)
