### ISSUE TITLE
ERROR: Could not map all functions to an entry in the manifest. When using Middleware and nextjs 13. 

### ISSUE THREAD

**Issue by the-programmer-alex** [cloudflare/next-on-pages#20]
When trying to deploy nextjs with middleware (edge runtime) with the index page using nodejs runtime. It always seems to fail with the command, `could not map all functions to an entry in the manifest.` Despite the fact the build itself succeeded, just the final step fails. 

Is this a known issue, based on the CF docs, middleware should just be a question of setting the edge runtime option. 

```
End log

 | ▲ Route (pages)                              Size     First Load JS
-- | --
 | ▲ ┌ ● / (512 ms)                             22.8 kB        95.6 kB
 | ▲ ├   └ css/c574ac10f3e3de78.css             7.59 kB
▲ ├   /_app                                  0 B            72.9 kB
 | ▲ ├ ○ /401                                   1.17 kB          74 kB
| ▲ ├   └ css/bacb32495600f722.css             1.74 kB
 ▲ └ ○ /404                                   181 B            73 kB
 ▲ + First Load JS shared by all              77.2 kB
 | ▲   ├ chunks/framework-3b5a00d5d7e8d93b.js   45.4 kB
 | ▲   ├ chunks/main-724a41f4f8780942.js        26.3 kB
 ▲   ├ chunks/pages/_app-fda4a1013dcfb8cc.js  297 B
 | ▲   ├ chunks/webpack-59c5c889f52620d6.js     819 B
 ▲   └ css/469c8a3831237427.css               4.38 kB
 ▲
| ▲ ƒ Middleware                               29.4 kB
 | ▲
 | ▲
| ▲ ○  (Static)  automatically rendered as static HTML (uses no initial props)
 | ▲ ●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
| ▲
| ▲
 ▲ Done in 20.42s.
 | ▲
 ▲ Collected static files (public/, static/, .next/static): 9.006ms
| ▲
 ▲ Build Completed in .vercel/output [58s]
▲
1 | ⚡️
 | ⚡️
 | ⚡️ Completed 'npx vercel build'.
| ⚡️
| ⚡️ ERROR: Could not map all functions to an entry in the manifest.
 | ⚡️ Please report this at https://github.com/cloudflare/next-on-pages/issues.
 | Failed: build command exited with code: 1
 Failed: an internal error occurred
```

# Middleware file
```
middleware.ts

...
// See "Matching Paths" below to learn more
// Only set edge runtime for middleware, otherwise pages break due to nodejs requirement
export const config = {
  runtime: 'experimental-edge',
  matcher: "/",
};
```

# Versions
```
    "next": "^13.0.2",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
     ....
```

**Comment by julesyoungberg** [comment]
I am also seeing this with next.js 12.3.0 and vercel 28.5.3 when using the `src` directory. It seems to work if the pages and middleware are at the project root though.

With the middleware at `src/middleware.ts`, my `.next/server/middleware-manifest.json` file contains
```
  "middleware": {
    "/": {
      "env": [],
      "files": [
        "server/edge-runtime-webpack.js",
        "server/src/middleware.js"
      ],
      "name": "src/middleware",
      "page": "/",
      "matchers": [
        {
          "regexp": "^(?:\\/(_next\\/data\\/[^/]{1,}))?(?:\\/((?!api|_next\\/static|favicon.ico).*))(.json)?[\\/#\\?]?$"
        }
      ],
      "wasm": [],
      "assets": []
    }
  },
```

and the edge function builds into `.vercel/output/functions/src/middleware.func`. This explains why the function is not mapped correctly because the code only checks for middleware with name "middleware": https://github.com/cloudflare/next-on-pages/blob/main/src/index.ts#L372

**Comment by the-programmer-alex** [comment]
> I am also seeing this with next.js 12.3.0 and vercel 28.5.3 when using the `src` directory. It seems to work if the pages and middleware are at the project root though.
> 
> With the middleware at `src/middleware.ts`, my `.next/server/middleware-manifest.json` file contains
> 
> ```
>   "middleware": {
>     "/": {
>       "env": [],
>       "files": [
>         "server/edge-runtime-webpack.js",
>         "server/src/middleware.js"
>       ],
>       "name": "src/middleware",
>       "page": "/",
>       "matchers": [
>         {
>           "regexp": "^(?:\\/(_next\\/data\\/[^/]{1,}))?(?:\\/((?!api|_next\\/static|favicon.ico).*))(.json)?[\\/#\\?]?$"
>         }
>       ],
>       "wasm": [],
>       "assets": []
>     }
>   },
> ```
> 
> and the edge function builds into `.vercel/output/functions/src/middleware.func`. This explains why the function is not mapped correctly because the code only checks for middleware with name "middleware": https://github.com/cloudflare/next-on-pages/blob/main/src/index.ts#L372

How interesting. It doesn't seem like there's any settings to indicate I'm using /src in nextjs either. It sorta just auto picks it up. Only .tsconfig requires a new base path.

**Comment by the-programmer-alex** [comment]
So based on @julesyoungberg's comment, I could deploy fine when the pages and middleware is on the project root folder. 
Anyone dealing with middleware, you

`MUST put pages/middle in the project root`

**Comment by julesyoungberg** [comment]
I think this package should support `src/middleware` since Vercel is not planning to change it: https://github.com/vercel/next.js/issues/37604
