### ISSUE TITLE
[🐛 Bug]: Internal server error 

### ISSUE THREAD

**Issue by alirezavlz** [cloudflare/next-on-pages#209]
### Cli version

0.10.1

### Description

After successful build and deployment I get this error! I tried to see the logs and this is what I get;

```
GET https://xxx.pages.dev/ - Ok @ 5/2/2023, 11:34:45 AM
  (error) Error: Invariant: AsyncLocalStorage accessed in runtime where it is not available
  (error) TypeError: Cannot read properties of null (reading 'default')
GET https://xxx.pages.dev/favicon.ico - Ok @ 5/2/2023, 11:34:45 AM
```

### Pages Deployment Method

Pages CI (GitHub/GitLab integration)

### Would you like to help?

- [ ] Would you like to help fixing this bug?

**Comment by james-elicx** [comment]
Hello, have you added the `nodejs_compat` compatibility flag to your Pages project's settings in the dashboard?

https://github.com/cloudflare/next-on-pages#3-deploy-your-application-to-cloudflare-pages

**Comment by alirezavlz** [comment]
Thank you guys, I added those `nodejs_compat ` in the past but somehow it wasn't there.
