### ISSUE TITLE
Middleware locally and on CF Pages have different response when returning cookies. Local returns the index page with cookie set. CF only returns cookies without the html.

### ISSUE THREAD

**Issue by the-programmer-alex** [cloudflare/next-on-pages#21]
Not certain if this is intended behaviour. When running using `npm run dev`, the middleware below would add the cookie to the current request and then display the home page content. 

[Same method as nextjs middleware docs](https://nextjs.org/docs/advanced-features/middleware#using-cookies)
```
    // Curr URL = /

export function middleware(request: NextRequest) {

    const response = NextResponse.next();
    response.cookies.set("myCookie", cookieVal);

    return response;
}

// See "Matching Paths" below to learn more
// Only set edge runtime for middleware, otherwise typewriter effect will break due to nodejs requirement
export const config = {
  runtime: 'experimental-edge',
  matcher: "/",
};

```

However, on CF Pages, it would not display the actual page content. Only rendering a pre in the body, without the index page html. The network tab does return the cookie though. 

# Edit Further Testing

Just tested with a blank return next() and it does the same thing. Nothing loads in the html. 
`return NextResponse.next()`

Is there something wrong with using the above code? Not even doing anything fancy either.

# Versions 
```
    "next": "^13.0.2",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
     ....

**Comment by the-programmer-alex** [comment]
It's pretty strange, when I get rid of the conditional redirects, everything loads and works fine. It's only when I have conditional redirects that the html doesn't load in. Eg, check for auth cookie, set in if set, otherwise unauth redirect. 

Not sure if this is due to the experimental edge breaking in my index.tsx, hence it's only enabled in the middleware itself. 

```
middleware.ts

export const config = {
  runtime: "experimental-edge",
};
```

**Comment by julesyoungberg** [comment]
I am seeing this too. I think it's because the worker always returns the result of the middleware as the response: https://github.com/cloudflare/next-on-pages/blob/main/templates/_worker.js/index.ts#L136

That should only happen if the middleware causes a redirect or writes to the body though, so there is some extra logic needed  to support rewrites & passing through. The code could check for the `x-middleware-rewrite` and `x-middleware-redirect` headers on the middleware response.

**Comment by dario-piotrowicz** [comment]
Note: This is most likely going to get fixed by the changes that @james-elicx is making in regards of https://github.com/cloudflare/next-on-pages/issues/129

**Comment by dario-piotrowicz** [comment]
@the-programmer-alex this should be fixed now in our beta release 🙂, if you want please have a check and let me know if you're still facing this issue (https://www.npmjs.com/package/@cloudflare/next-on-pages/v/0.0.0-87e183b)
