### ISSUE TITLE
next error publishing function with web worker

### ISSUE THREAD

**Issue by rawsh** [cloudflare/next-on-pages#23]
My page is building successfully and publishing assets, but fails when trying to deploy the worker

```
13:17:33.614 | Success: Assets published!
-- | --
13:17:34.862 | Error: Failed to publish your Function. Got error: Uncaught TypeError: Cannot read properties of undefined (reading 'includes')
at worker.mjs:25840:35 in get platform   
at worker.mjs:25830:46 in _KeyboardManager   
at worker.mjs:26235:74 in Object.defineProperty.value   
at worker.mjs:32963:49 in __w_pdfjs_require__   
at worker.mjs:25564:26 in Object.defineProperty.value  
 at worker.mjs:32963:49 in __w_pdfjs_require__   
at worker.mjs:25475:61 in Object.defineProperty.value   
at worker.mjs:32963:49 in __w_pdfjs_require__   
at worker.mjs:24235:71 in Object.defineProperty.value   
at worker.mjs:32963:49 in __w_pdfjs_require__
```

https://github.com/rawsh/pdfgrep.com

I'm using the pdfjs web worker so I'm assuming next is trying to SSR some code that should only run on local, but I'm confused because it builds and I don't get any complaints from next. How can I debug what is causing this?

**Comment by dario-piotrowicz** [comment]
@rawsh thanks a lot for the issue, sorry for replying to it this late 🙇 

I just cloned your repo and built it using the latest (0.7.0) next-on-pages, everything went fine as you can see from the [deployed app](https://pdfgrep-dario-test.pages.dev/).

So this is probably no longer an issue anymore, could you please double check?

**Comment by dario-piotrowicz** [comment]
I'm closing the issue as I haven't yet received a reply to the above comment and suspect that this is no longer an issue

@rawsh if you come back to this and still face the same issue please feel free to reopen the issue and/or ping me
