### ISSUE TITLE
[⚡ Feature]: --outdir

### ISSUE THREAD

**Issue by GregBrimble** [cloudflare/next-on-pages#231]
### Description

Let me specify an output directory rather than always only ever exporting to `.vercel/output/static/_worker.js`.

### Would you like to help?

- [ ] Would you like to help implement this feature?

**Comment by GregBrimble** [comment]
I expect index.js to be inside whatever I set --outdir to.

e.g.

`npx @cloudflare/next-on-pages --outdir=./dist`

```
dist/
  index.js
  __next_on_pages_dist__/
    chunks/
      123.js
```

It should create the `dist` directory for me if it doesn't already exist. Not sure if it should error, wipe, or intermingle with `dist` if it already exists? We can look at what other tools do.

**Comment by james-elicx** [comment]
I would like to handle this one if it can be assigned to me. As discussed, I think it's valuable to put the full output in whatever the specified value for `--outdir` is.

For changing the `_worker.js` directory, which it seems like you are also interested in, I think it would be more valuable to add a flag along the lines of `--workerdir`. I can implement this too if you wish (and leave it undocumented for your own playing with).

**Comment by GregBrimble** [comment]
I don't think I need `--workerdir`! I just wanted a way to generate the Worker pieces in some place that is well-known to me, that isn't the final `.vercel/output/static` dir, because I want to do some transformations first.

So just `--outdir` alone is going to be completely sufficient for me since I know that the Worker is always in `${outdir}/_worker.js/index.js`. That's perfect. Thank you!
