### ISSUE TITLE
[🐛 Bug]: D1 causes the deployment/publishing process to fail

### ISSUE THREAD

**Issue by dario-piotrowicz** [cloudflare/next-on-pages#243]
> **Note**
> This issue effects the latest beta version(/s) and not the current `v0.10.1` release
> (since it is related to newly introduced lazy loading functionality)

If you have a working next-on-pages application (any application, a new brand new one or for example any from [next-apps-for-testing](https://github.com/dario-piotrowicz/next-apps-for-testing), it doesn't really make a difference), as soon as you add a D1 binding for your project in the Cloudflare dashboard, any as in:
![Screenshot 2023-05-14 at 17 09 33](https://github.com/cloudflare/next-on-pages/assets/61631103/76a4b7f8-85bb-4811-bdec-6fe499dbc6b5)

even if your application doesn't use the D1 binding at all you won't be able to publish the app anymore, neither via direct upload nor via the GitHub/GitLab integration.

The GitHub/GitLab integration surfaces an error such as this:
![238193413-851fc4ac-d244-4321-88ad-63df288198b4](https://github.com/cloudflare/next-on-pages/assets/61631103/cd5e8c44-18fd-49da-89fc-6f3d3de493cb)

___

This basically makes it currently impossible for any app build using next-on-pages to use D1

___

PS: locally I believe D1 works as expected

**Comment by dario-piotrowicz** [comment]
@zizifn 🙂👍

**Comment by dario-piotrowicz** [comment]
@GregBrimble I've also tested this with a direct upload with your latest [wrangler prerelease](https://prerelease-registry.devprod.cloudflare.dev/workers-sdk/runs/4949808500/npm-package-wrangler-3175) with no luck

**Comment by dario-piotrowicz** [comment]
PS: this is an external issue which (most likely) can't be fixed in the next-on-pages code itself, I've created it just to keep track of the progress on it (and so that people trying to use D1 and failing can see this issue)

**Comment by dario-piotrowicz** [comment]
PS: this is an issue with any Pages app using the `_worker.js` directory, for example even this extremely simple application breaks when a D1 is set in the dashboard for it: https://github.com/dario-piotrowicz/cf-workers-and-pages-bugs-reproductions/tree/master/pages/simple-workerjs-dir

**Comment by dario-piotrowicz** [comment]
I've just tested this and seems all good, so I'm closing this issue 🙂 

@zizifn please check if now your application works fine and let me know if you still experience this issue

**Comment by sazzy4o** [comment]
@dario-piotrowicz I am still running into this issue. I think I have the latest `@cloudflare/next-on-pages` and `wrangler` installed:
```
├─┬ @cloudflare/next-on-pages@1.0.2
│ ├── acorn@8.8.2
│ ├── ast-types@0.14.2
│ ├── chalk@5.2.0
│ ├── chokidar@3.5.3
│ ├── cookie@0.5.0
│ ├── esbuild@0.15.18
│ ├── js-yaml@4.1.0
│ ├── next-on-pages-vercel-cli@29.3.0-next-on-pages-fix-3
│ ├── pcre-to-regexp@1.1.0
│ ├── semver@7.5.1
│ ├── wrangler@3.1.0
│ ├── zod@3.21.4
│ └── zodcli@0.0.4
```
I am I using the wrong version or is there something else I am missing?
Here is the error message I am seeing after enabling D1 bindings (looks the same):
```
19:50:38.246 | ✨ Upload complete!
-- | --
19:50:41.078 | Success: Assets published!
19:50:44.993 | Error: Failed to publish your Function. Got error: Uncaught Error: No such module "opt/buildhome/repo/.vercel/output/static/_worker.js/index.js".   imported from "bundledWorker-0.2654080686179836.mjs"
```
Thanks for any insights you might have!

**Comment by james-elicx** [comment]
> I am I using the wrong version or is there something else I am missing? Here is the error message I am seeing after enabling D1 bindings (looks the same):
> 
> ```
> 19:50:38.246 | ✨ Upload complete!
> -- | --
> 19:50:41.078 | Success: Assets published!
> 19:50:44.993 | Error: Failed to publish your Function. Got error: Uncaught Error: No such module "opt/buildhome/repo/.vercel/output/static/_worker.js/index.js".   imported from "bundledWorker-0.2654080686179836.mjs"
> ```
> 
> Thanks for any insights you might have!

Hey there @sazzy4o, this is an issue when using D1 and Wrangler v2 to deploy. I am going to assume that you are using the Pages git CI for your deployments. IIRC, that uses Wrangler v2 when it actually deploys the built app to Pages.

You could try deploying manually with Wrangler v3, or create a GitHub workflow using something like [cloudflare/pages-action](https://github.com/cloudflare/pages-action) to deploy with v3 on pushes.

**Comment by hanumanjiblog** [comment]
This issue not resolved please help me

**Comment by sazzy4o** [comment]
I was able to get the deploy to succeed using Github Actions

However, it doesn't seem like `env.DB` exists:
```
export default async function handler(req: NextRequest, env: Env) {
	try{
		const result = await env.DB.prepare(
			...
		).bind(data).run();
		...
	} catch(e){
		console.log(`${e}: ${e.message}, ${e.stack}`);
	}
}
```
```
TypeError: Cannot read properties of undefined (reading 'prepare'): Cannot read properties of undefined (reading 'prepare'),
...
```

Despite the binding existing for the pages site:
![image](https://github.com/cloudflare/next-on-pages/assets/10637549/b10da0d8-c277-454d-b4e2-0584d41a2722)

This is likely an unrelated issue (I'll have a closer look tomorrow and might create a separate issue)

**Comment by james-elicx** [comment]
> I was able to get the deploy to succeed using Github Actions
> 
> However, it doesn't seem like `env.DB` exists:
> 
> ```
> export default async function handler(req: NextRequest, env: Env) {
> 	try{
> 		const result = await env.DB.prepare(
> ```

Hello @sazzy4o, `@cloudflare/next-on-pages` spreads the env variables onto `process.env`. You should try to access your environment variables and bindings through that instead - we do not pass an `env` argument to API route handlers.



> This issue not resolved please help me

Hello @hanumanjiblog, please read my earlier comment to another user.

This is an error from Wrangler v2. I shall assume that you are using the Pages git CI for deployments - in which case, both of the build images currently use Wrangler v2 to do the deployments IIRC. Therefore, you could try deploying manually with Wrangler v3 (`npx wrangler pages deploy`), or create a Github action using [cloudflare/pages-action](https://github.com/cloudflare/pages-action) to deploy using Wrangler v3 on pushes.

**Comment by sazzy4o** [comment]
Thanks @james-elicx! Using `process.env.DB` instead of the `env.DB` passed into the function worked
