### ISSUE TITLE
AppDir Page path params undefined

### ISSUE THREAD

**Issue by AlexDaichendt** [cloudflare/next-on-pages#25]
Hey, 

I am trying to mimic the demo of vercel, to be specific the [ISR with path variables](https://github.com/vercel/app-playground/blob/main/app/isr/%5Bid%5D/page.tsx). However, it appears that the params parameter is always undefined, despite it working with `next build && next start`. 

`app/something/[id]/page.tsx`: 
```
export default async function Page({
  params,
}: {
  params?: any;
  children?: React.ReactNode;
}) {
  console.log(params);
  const data = await fetchData(params.id);
  return (
    <>
      <PageComponent {...data} />
    </>
  );
}
```

Am I missing something? Are path parameters supported?

**Comment by viantirreau** [comment]
I think this might be related to issue #32
