### ISSUE TITLE
[🐛 Bug]: Next info often fails in retrieving packages versions

### ISSUE THREAD

**Issue by dario-piotrowicz** [cloudflare/next-on-pages#250]
### next-on-pages environment related information

```
System:
        Platform: darwin
        Arch: arm64
        Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
        CPU: (10) arm64 Apple M1 Pro
        Memory: 32 GB
        Shell: /bin/zsh
Binaries:
        Node: 16.16.0
        Yarn: 1.22.19
        npm: 8.11.0
        pnpm: N/A
Package Manager Used: pnpm
Relevant Packages:
        @cloudflare/next-on-pages: 0.0.0-fa33b2c (prerelease for PR #213)
        vercel: N/A
        next: N/A
```

### Description

As you can see from the informations I pasted above 👆 it seems like in the `--info` command we often fail to collect some packages versions, I very often see `N/A` values for `vercel` and `next` we should improve things and make the versions collection more reliable.

____

This basically means that the following code: https://github.com/cloudflare/next-on-pages/blob/e0537560f3888fdd13595345859adfb867914654/src/cli.ts#L211-L262

very likely has some issue and needs to be improved

**Comment by tarunrajput** [comment]
@dario-piotrowicz, I think we cannot list with npx. That's why it is failing to retrieve pkg version
<img width="491" alt="image" src="https://github.com/cloudflare/next-on-pages/assets/34857453/799660da-1a2b-422a-8d01-eca58f074260">

**Comment by dario-piotrowicz** [comment]
are you sure? I think I've seen it working sometimes... :thinking:  (like [here](https://github.com/cloudflare/next-on-pages/issues/202) and [here](https://github.com/cloudflare/next-on-pages/issues/219))

Also the `N/A` `pnpm` version in my info, we do get the other versions but not `pnpm`? (for example [here](https://github.com/cloudflare/next-on-pages/issues/244) also yarn is not detected)

something feels a bit off to me :thinking: :sweat:

**Comment by dario-piotrowicz** [comment]
I think I've found the issue(/s), assigning it to myself since I need this for another fix as well 🙂
