### ISSUE TITLE
NextJS APIs are not listed as functions and thus logs cannot be viewed on dashboard

### ISSUE THREAD

**Issue by Hades32** [cloudflare/next-on-pages#27]
TLDR: I have a simple `/api/hello` route, which works, but going to the dashboard as described [here](https://developers.cloudflare.com/pages/platform/functions/debugging-and-logging/#view-logs-in-the-cloudflare-dashboard) shows nothing

**Comment by GregBrimble** [comment]
We're currently working on the stability and robustness of tailing Functions, which will hopefully improve this for you. We'll follow up once we've closed out some of those issues.

**Comment by GregBrimble** [comment]
It should now be possible to view logs in the Cloudflare dashboard and with Wrangler: https://developers.cloudflare.com/pages/platform/functions/debugging-and-logging/
