### ISSUE TITLE
dynamic pages not supported by edge

### ISSUE THREAD

**Issue by Galaraz** [cloudflare/next-on-pages#278]
When using getServerSideProps export const config = { runtime: 'edge' }

the error message is as follows provided runtime 'edge', the edge runtime for rendering is currently experimental. Use 'experimental-edge' runtime instead.
could you please check. my code stopped working and I'm not sure if the error is due to my configuration this error happens specifically with my dynamic routes.

**Comment by Galaraz** [comment]
Thank you very much guys, unfortunately I don't know why this error happened, the solution for me was to return to the point where it worked and add the modifications little by little.

**Comment by dario-piotrowicz** [comment]
I see, I'm glad that you managed to solve it :smiley::+1:
