### ISSUE TITLE
i18n with `next-intl` fails to register routes

### ISSUE THREAD

**Issue by Hades32** [cloudflare/next-on-pages#28]
I tried using next-intl with next-on-pages, but I'm getting the message below:
```
⚡️ ERROR: Failed to produce a Cloudflare Pages build from the project.
⚡️ The following functions were not configured to run with the Edge Runtime:
⚡️
⚡️  - de
⚡️  - en
```
Seems like the dynamic routes don't get picked up

**Comment by josephbuchma** [comment]
@Hades32 have you found any workarounds?

**Comment by Hades32** [comment]
I stopped using this repo. It misses a lot of features. I now use preact

**Comment by ThuKieuIC2** [comment]
@Hades32 Does your Preact support SEO well?
Vercel still builds well NextJs projects, but it runs edge functions slower much than CF Workers.
For Website frontend only, I use CF Application plan (CDN, proxy..) routing to Vercel.
For backend, I buy a CF Workers plan.

**Comment by ThuKieuIC2** [comment]
I still use built-in i18n and have this solution, pls try:

(i) Keep next.config.js
```
i18n: {
    locales: ['vi',  'en'],
    defaultLocale: 'vi',
    localeDetection: false,
  },
```
(ii) Add this line to public/_redirects file
```
/ /vi 301
```
All build runs well, and I never face any issue. The default locale "vi" also removed on URL after first time render home page from / or /vi

**Comment by james-elicx** [comment]
I believe that we may have identified a way that we can support the `i18n` option from the `next.config.js`, now that we have the new routing system. I'll be looking into a way to introduce proper support.
