### ISSUE TITLE
[🐛 Bug]: Unable to get NextFetchEvent

### ISSUE THREAD

**Issue by ynishimura** [cloudflare/next-on-pages#285]
### next-on-pages environment related information

System:
        Platform: darwin
        Arch: x64
        Version: Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64
        CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
        Memory: 32 GB
        Shell: /bin/zsh
Binaries:
        Node: 18.15.0
        Yarn: N/A
        npm: 9.5.0
        pnpm: N/A
Package Manager Used: npm
Relevant Packages:
        @cloudflare/next-on-pages: 1.0.1
        vercel: 30.0.0
        next: 13.4.2

### Description

I've attempted to retrieve the `NextFetchEvent` by referring to [this Next.js documentation](https://nextjs.org/docs/pages/api-reference/functions/next-server#nextfetchevent), but it's not working as expected.

Is there a method to retrieve the `NextFetchEvent`?

Also, I would like to use the `waitUntil` of `NextFetchEvent`. Is there another way to do this without using `NextFetchEvent`?

### Pages Deployment Method

None

### Would you like to help?

- [ ] Would you like to help fixing this bug?

**Comment by dario-piotrowicz** [comment]
next-on-pages relies on a module worker, such workers don't surface the `fetchEvent` (see [Cloudflare docs](https://developers.cloudflare.com/workers/runtime-apis/fetch-event/#syntax-module-worker))

from a module worker you can get the execution context with its `waitUntil` and `passThroughOnException` methods, would that suffice for you?

in any case that should be available soon via some utilities (as I've already implemented it in https://github.com/cloudflare/next-on-pages/pull/265). Currently we simply got some disagreements on the team on how we'd want the API to look like, after we agree on that implementing the utility itself should be pretty simple 🙂

**Comment by ynishimura** [comment]
Thank you for sharing the document. I'll try out what you suggested. Looking forward to the implementation of the utils as it will be quite helpful.

**Comment by dario-piotrowicz** [comment]
@va3y the idea would be that inside the `fetch` you could take the `context` and put it somewhere in the global scope (potentially using AsyncLocalStorage for making it more robust) and then inside the next handler retrieve it.

I think this is just about the only way to implement this.

I did this in https://github.com/cloudflare/next-on-pages/pull/265 ([here](https://github.com/cloudflare/next-on-pages/blob/343a67b3a87fdbc26a472c27f2e918f81230d198/src/cli/buildApplication/generateGlobalJs.ts#L14-L16) I create the ALS, [here](https://github.com/cloudflare/next-on-pages/blob/343a67b3a87fdbc26a472c27f2e918f81230d198/src/cli/templates/_worker.js/index.ts#L43) I put the `context` into it and [here](https://github.com/cloudflare/next-on-pages/blob/343a67b3a87fdbc26a472c27f2e918f81230d198/src/utils/utils/cloudflareGlobalContext.ts) I define a utility that developers could call in their Next.js handler to retrieve the `context`)

Unfortunately I wasn't yet able to merge my PR as there are conflicting ideas on the team in regards on what sort of API we should expose (primarily in regards to the bindings), I'll have to discuss with the team to decide what sort of API we'd all like to expose (but I don't think that the underlying implementation would change)
