### ISSUE TITLE
[🐛 Bug]: npx vercel build for edge runtime causing ReferenceError: document is not defined

### ISSUE THREAD

**Issue by anonymouscatcher** [cloudflare/next-on-pages#287]
### next-on-pages environment related information

System:
	Platform: darwin
	Arch: x64
	Version: Darwin Kernel Version 22.5.0
Binaries:
	Node: 18.16.0
	Yarn: 1.22.10
	npm: 9.5.1
	pnpm: N/A
Package Manager Used: yarn (classic)
Relevant Packages:
	@cloudflare/next-on-pages: 0.10.1
	vercel: N/A
	next: 13.4.2

### Description

I'm facing a little hiccup while trying to build a Vercel app for Cloudflare Pages. The good news is that the application build goes smoothly and completes successfully. However, I hit a roadblock when I try to run npx vercel@latest build as it throws an error.

I use app directory.
I use route segmented config

```js
export const runtime = 'edge';
```

build command:
```shell
npx @cloudflare/next-on-pages@latest
```

```shell
▲  - info Collecting page data...
▲  /app/***/.next/server/edge-runtime-webpack.js:196
▲  /******/ 		__webpack_require__.b = document.baseURI || self.location.href;
▲       		                        ^
▲
▲  ReferenceError: document is not defined
▲  at /app/***/.next/server/edge-runtime-webpack.js:196:36
▲  at /app/***/.next/server/edge-runtime-webpack.js:245:13
▲  at /app/***/.next/server/edge-runtime-webpack.js:250:12
▲  at Script.runInContext (node:vm:141:12)
▲  at runInContext (node:vm:291:6)
▲  at evaluateInContext (/app/***/node_modules/next/dist/server/web/sandbox/context.js:361:38)
▲  at getRuntimeContext (/app/***/node_modules/next/dist/server/web/sandbox/sandbox.js:68:9)
▲  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
▲  at async /app/***/node_modules/next/dist/build/utils.js:975:29
▲  at async Span.traceAsyncFn (/app/***/node_modules/next/dist/trace/trace.js:103:20)
▲  /app/***/.next/server/edge-runtime-webpack.js:196
▲  /******/ 		__webpack_require__.b = document.baseURI || self.location.href;
```

I checked everything in my application and I'm sure I'm using `use client` for all the client components which uses dom functionalities. I hadn't this issue before and my app was working after upgrading to latest version of `next` and `@cloudflare/next-on-pages` I get this errors.

### Pages Deployment Method

Pages CI (GitHub/GitLab integration)

### Would you like to help?

- [ ] Would you like to help fixing this bug?

**Comment by alirezavlz** [comment]
Also the `not-found.js` doesn't seems to be working with edge runtime,

```js
import dynamic from 'next/dynamic';

export const runtime = 'edge';

const Error404 = dynamic(() => import('@/components/404/Error404'));

export default function NotFound() {
  return <Error404 />;
}
```

error:
```
⚡️ ERROR: Failed to produce a Cloudflare Pages build from the project.
⚡️
⚡️ 	The following functions were not configured to run with the Edge Runtime:
⚡️ 		- _error.func
```

**Comment by james-elicx** [comment]
Hello, your `document is not defined` error is occurring during the Next.js build step from the Vercel CLI. This is indicated by the little triangles at the start of the messages.

I'm afraid we won't really be able to help much because of that 🙁 - it's something out of our control and would indicate that there's either a bug with Next.js or an issue with your code, because it's occurring while Next.js tries to build.

Does your app build fine when you just use `npx vercel build` instead of `npx @cloudflare/next-on-pages`?

p.s. I noticed that you environment information says you are using v0.10.1. Please double check that you are using the latest version of next-on-pages (v1.0.1) 🙂

(I'll leave discussion about the `_error.func` problem for the other issue you opened)

**Comment by anonymouscatcher** [comment]
after a lot of investigations I found that web worker causing this issue, it wasn't easy since I'm converting a large project to cloudflare pages.

**Comment by dario-piotrowicz** [comment]
@anonymouscatcher awesome to hear that you solved it :smiley: 

Please let us know if you find anything DX related that you think we could do to make such type of conversions easier :slightly_smiling_face:

**Comment by clmnin** [comment]
Hi @anonymouscatcher, how did you solve this issue? I am facing the same issue when trying to import `@ffmpeg/ffmpeg` in an edge runtime route.

**Comment by farhanabi** [comment]
@clmnin I think `@ffmpeg/ffmpeg` uses Web Workers, which aren't supported in edge runtime environments
