### ISSUE TITLE
[🐛 Bug]: Module not found: Can't resolve on appDir

### ISSUE THREAD

**Issue by muhrusdi** [cloudflare/next-on-pages#306]
### next-on-pages environment related information

System:
        Platform: darwin
        Arch: arm64
        Version: Darwin Kernel Version 22.5.0: Mon Apr 24 20:52:24 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6000
        CPU: (8) arm64 Apple M1 Pro
        Memory: 16 GB
        Shell: /bin/zsh
Binaries:
        Node: 18.15.0
        Yarn: 1.22.19
        npm: 9.5.0
        pnpm: N/A
Package Manager Used: yarn (classic)
Relevant Packages:
        @cloudflare/next-on-pages: 1.0.2
        vercel: [object Promise]
        next: 13.4.5

### Description

When i deploy my nextjs app, i got this error on clouflare pages log

07:32:08.405 | ▲  This information is used to shape Next.js' roadmap and prioritize features.
-- | --
07:32:08.405 | ▲  You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
07:32:08.405 | ▲  https://nextjs.org/telemetry
07:32:08.544 | ▲  - info Creating an optimized production build...
07:32:15.533 | ▲  Failed to compile.
07:32:15.534 | ▲  ./app/blog/page.tsx
07:32:15.534 | ▲  Module not found: Can't resolve '@/components/blog/blog-item'
07:32:15.534 | ▲
07:32:15.534 | ▲  https://nextjs.org/docs/messages/module-not-found
07:32:15.534 | ▲
07:32:15.534 | ▲  ./app/layout.tsx
07:32:15.534 | ▲  Module not found: Can't resolve '@/styles/global.module.scss'
07:32:15.534 | ▲
07:32:15.535 | ▲  https://nextjs.org/docs/messages/module-not-found
07:32:15.535 | ▲
07:32:15.535 | ▲  ./app/page.tsx
07:32:15.535 | ▲  Module not found: Can't resolve '@/components/footer'
07:32:15.535 | ▲
07:32:15.535 | ▲  https://nextjs.org/docs/messages/module-not-found

### Pages Deployment Method

Pages CI (GitHub/GitLab integration)

### Would you like to help?

- [ ] Would you like to help fixing this bug?

**Comment by james-elicx** [comment]
Hey there, sorry to hear you're having issues.

Looking at the logs, it appears that these are coming from the Vercel CLI, as indicated by the little triangle at the start. This would mean that they are build errors when Next.js is trying to build your application 🙁

It sounds like there might be a missing import alias or it is struggling to resolve the import alias correctly. You could try using relative paths perhaps.

I'm afraid this isn't really something we play any role in or can help with other than offering advice, as it is from Next.js and not next-on-pages.

**Comment by muhrusdi** [comment]
i already try relative path, but got same issue 


07:08:47.633 | ▲  This information is used to shape Next.js' roadmap and prioritize features.
-- | --
07:08:47.633 | ▲  You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
07:08:47.634 | ▲  https://nextjs.org/telemetry
07:08:47.785 | ▲  - info Creating an optimized production build...
07:08:54.799 | ▲  Failed to compile.
07:08:54.800 | ▲  ./app/blog/page.tsx
07:08:54.800 | ▲  Module not found: Can't resolve '../../components/blog/blog-item'
07:08:54.800 | ▲
07:08:54.800 | ▲  https://nextjs.org/docs/messages/module-not-found
07:08:54.801 | ▲
07:08:54.801 | ▲  ./app/layout.tsx
07:08:54.801 | ▲  Module not found: Can't resolve '../styles/global.module.scss'
07:08:54.801 | ▲
07:08:54.801 | ▲  https://nextjs.org/docs/messages/module-not-found
07:08:54.802 | ▲
07:08:54.802 | ▲  ./app/page.tsx
07:08:54.802 | ▲  Module not found: Can't resolve '../components/banner'

**Comment by muhrusdi** [comment]
it's running well when i build locally

**Comment by muhrusdi** [comment]
solved

i change import/export component

**Comment by SuperchupuDev** [comment]
> solved
> 
> i change import/export component

what does that mean? i'm having this same issue and i don't really know how to fix it

**Comment by laurentlahmy** [comment]
@muhrusdi Can you explain what you changed? (facing the same issue)
@SuperchupuDev Do you remember how you fixed it?

**Comment by SuperchupuDev** [comment]
IIRC the errors i got were when importing css modules. can't remember much but i think moved them to a folder inside src and i think that worked

**Comment by laurentlahmy** [comment]
@SuperchupuDev thanks!
In my case I changed the casing of the file name of some components, and somehow Next needed the old name (`/components/Text` instead of `/components/text`). I guess some caching not invalidated somewhere.

**Comment by msdrigg** [comment]
See https://github.com/cloudflare/next-on-pages/issues/761 I think it's the same issue
