### ISSUE TITLE
[🐛 Bug]: Next.js app directory route interception doesn't work properly

### ISSUE THREAD

**Issue by bharatari** [cloudflare/next-on-pages#310]
### next-on-pages environment related information

System:
        Platform: linux
        Arch: x64
        Version: #1 SMP Fri Jan 27 02:56:13 UTC 2023
        CPU: (12) x64 12th Gen Intel(R) Core(TM) i7-1255U
        Memory: 8 GB
        Shell: /bin/bash
Binaries:
        Node: 18.15.0
        Yarn: 1.22.19
        npm: 9.5.0
        pnpm: 8.3.1
Package Manager Used: npm
Relevant Packages:
        @cloudflare/next-on-pages: 1.0.2
        vercel: [object Promise]
        next: [object Promise]

### Description

Route interception as described in the Next.js docs [here](https://nextjs.org/docs/app/building-your-application/routing/intercepting-routes) doesn't seem to work properly with `next-on-pages`. [Parallel routes](https://nextjs.org/docs/app/building-your-application/routing/parallel-routes) **do** work, it's just route interception (directories with `(.), (..), (...)` prefixes) that don't work.

### Reproduction

Here is a minimal repro of the issue: https://github.com/bharatari/route-interception.

`next dev`
Route `/`
![Screenshot 2023-06-13 103657](https://github.com/cloudflare/next-on-pages/assets/5521868/538e3060-f36a-4b44-9ac9-4e7d4619f876)
Route `/hello` after clicking the button (which is a Link to /hello). Note that interception happens as expected here, the modal is shown instead of rendering the actual `/hello` route.
![Screenshot 2023-06-13 103721](https://github.com/cloudflare/next-on-pages/assets/5521868/6f1505fb-3f90-45de-99a1-7f0f949bec76)
Route `/hello` when loading the URL directly. This is the case with no interception, the actual route is rendered.
![Screenshot 2023-06-13 103737](https://github.com/cloudflare/next-on-pages/assets/5521868/1fb9ca49-77a3-4ec1-b1d9-cbe9cafea850)

`wrangler`
Route `/`
![Screenshot 2023-06-13 104034](https://github.com/cloudflare/next-on-pages/assets/5521868/dd21982e-978b-4b0e-95ef-70fa8df4711c)
Route `/hello` after clicking the button (which is a Link to /hello). The `/hello` route is loaded, interception **does not** work as expected here.
![Screenshot 2023-06-13 104100](https://github.com/cloudflare/next-on-pages/assets/5521868/6531eef8-743c-4157-bcc4-34f571215069)
Route `/hello` when loading the URL directly. This is the case with no interception.
![Screenshot 2023-06-13 104047](https://github.com/cloudflare/next-on-pages/assets/5521868/1e89b207-a92a-44a9-bd55-95d8bd771bc4)

When run with `wrangler`, intercepted routes as defined in the `app` directory are completely ignored. The actual route is rendered every time.

### Pages Deployment Method

None

### Would you like to help?

- [ ] Would you like to help fixing this bug?

**Comment by james-elicx** [comment]
Thank you for opening this issue and providing a reproduction 🙂

I believe I have identified the cause and have opened a PR that should fix this issue. I would welcome you to try out the prerelease available in https://github.com/cloudflare/next-on-pages/pull/312#issuecomment-1589663418.

**Comment by bharatari** [comment]
Hi @james-elicx, the prerelease is working great. Thanks for the quick fix!
