### ISSUE TITLE
[🐛 Bug]: `No such module "__next-on-pages-dist__/functions/index.func.js".` on `wrangler dev`/`wrangler deploy`

### ISSUE THREAD

**Issue by ivolimasilva** [cloudflare/next-on-pages#316]
### next-on-pages environment related information

```
System:
	Platform: darwin
	Arch: arm64
	Version: Darwin Kernel Version 22.5.0: Mon Apr 24 20:53:19 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6020
	CPU: (12) arm64 Apple M2 Max
	Memory: 32 GB
	Shell: /bin/zsh
Binaries:
	Node: 18.16.0
	Yarn: N/A
	npm: 9.5.1
	pnpm: N/A
Package Manager Used: npm
Relevant Packages:
	@cloudflare/next-on-pages: 1.1.0
	vercel: [object Promise]
	next: [object Promise]
```

### Description

Running `wrangler dev` or `wrangler deploy` and accessing the URL shows `Internal server error` and the logs show:
```
Error: No such module "__next-on-pages-dist__/functions/index.func.js".
    at P (index.js:335:35)
    at ae (index.js:508:65)
    at T (index.js:498:10)
    at async jsonError (index.js:530:12) {
  stack: Error: No such module "__next-on-pages-dist__/func…:498:10)
    at async jsonError (index.js:530:12),
  message: No such module "__next-on-pages-dist__/functions/index.func.js".
  ```

### Reproduction

Follow the guide in this repo's README.

1. `npx create-next-app@latest my-next-app`
2. `cd my-next-app`
3. `export const runtime = 'edge';` in the page file
4. `npx @cloudflare/next-on-pages`
<details>
<summary>Log</summary>

```
⚡️ @cloudflare/next-on-pages CLI v.1.1.0
⚡️ Detected Package Manager: npm
⚡️ Preparing project...
⚡️ Project is ready
⚡️ Building project...
▲  Vercel CLI 30.2.2
▲  WARNING: You should not upload the `.next` directory.
▲  Installing dependencies...
▲  up to date in 142ms
▲  116 packages are looking for funding
▲  run `npm fund` for details
▲  Detected Next.js version: 13.4.6
▲  Detected `package-lock.json` generated by npm 7+...
▲  Running "npm run build"
▲  > cloudflare-next@0.1.0 build
▲  > next build
▲  - info Creating an optimized production build...
▲  - info Compiled successfully
▲  - info Linting and checking validity of types...
▲  - info Collecting page data...
▲  - info Generating static pages (0/3)
▲  - info Generating static pages (3/3)
▲  - info Finalizing page optimization...
▲
▲  Route (app)                                Size     First Load JS
▲  ┌ ℇ /                                      0 B                0 B
▲  └ ○ /favicon.ico                           0 B                0 B
▲  + First Load JS shared by all              77.6 kB
▲  ├ chunks/769-8ab68f842512379f.js         25.2 kB
▲  ├ chunks/bce60fc1-49ee79ad31766ac6.js    50.5 kB
▲  ├ chunks/main-app-ab92f207fb183741.js    218 B
▲  └ chunks/webpack-4e1473a5f6694102.js     1.68 kB
▲
▲  Route (pages)                              Size     First Load JS
▲  ─ ○ /404                                   182 B          74.8 kB
▲  + First Load JS shared by all              74.6 kB
▲  ├ chunks/framework-8883d1e9be70c3da.js   45 kB
▲  ├ chunks/main-542a92a81d12d254.js        27.7 kB
▲  ├ chunks/pages/_app-998b8fceeadee23e.js  195 B
▲  └ chunks/webpack-4e1473a5f6694102.js     1.68 kB
▲  ℇ  (Streaming)  server-side renders with streaming (uses React 18 SSR streaming or Server Components)
▲  ○  (Static)     automatically rendered as static HTML (uses no initial props)
▲  Traced Next.js server files in: 1.567s
▲  Created all serverless functions in: 636.907ms
▲  Collected static files (public/, static/, .next/static): 2.192ms
▲  Build Completed in .vercel/output [7s]
⚡️ Completed `npx vercel build`.
⚡️ Generated '.vercel/output/static/_worker.js/index.js'.
```
</details>

Then
```
wrangler dev .vercel/output/static/_worker.js/index.js --compatibility-date 2022-11-30 --compatibility-flags="nodejs_compat"
```

Or `wrangler deploy ...`

### Pages Deployment Method

Direct Upload (`wrangler pages publish` or the @cloudflare/pages-action GitHub Action)

### Additional Information

Also tried to connect to a Github repo through Pages CI but got the same issue.

### Would you like to help?

- [X] Would you like to help fixing this bug?

**Comment by paolotiu** [comment]
Were you able to solve this?

**Comment by dario-piotrowicz** [comment]
Hi @ivolimasilva, your command:
```sh
wrangler dev .vercel/output/static/_worker.js/index.js --compatibility-date 2022-11-30 --compatibility-flags="nodejs_compat"
```
is for workers but next-on-pages works on Pages, that won't work, you should use the pages command instead:
```sh
wrangler pages dev .vercel/output/static/ --compatibility-date 2022-11-30 --compatibility-flags="nodejs_compat"
```

Could you give that a go and let me know if it works for you? :slightly_smiling_face:

**Comment by ivolimasilva** [comment]
@dario-piotrowicz Yeah, that works! Thanks!

But I now get:
```
Error: The 'credentials' field on 'RequestInitializerDict' is not implemented.
```

Which seems to be expected as of https://github.com/cloudflare/workers-sdk/issues/2514. Do you know any way around it?

**Comment by dario-piotrowicz** [comment]
@ivolimasilva no problem, I'm glad that it works 🙂 

Regarding the credentials problem I wasn't aware of it, by reading it looks like you need not to set credentials in local development, would that be possible in your application?

(You could use `NODE_ENV` but I am afraid that we've got a bug with that currently, so you should find a different temporary workaround instead)

**Comment by ivolimasilva** [comment]
> Regarding the credentials problem I wasn't aware of it, by reading it looks like you need not to set credentials in local development, would that be possible in your application?

I already removed `credentials: 'include'` from my code, albeit I still need it. Even so, it throws out the same error. I'm using **urql** client but found some other reports ([here](https://stackoverflow.com/questions/76292297/alternate-way-to-pass-graphql-auth-in-nuxt3-using-apollo-client)).

**Comment by dario-piotrowicz** [comment]
@ivolimasilva sorry I misread the issue's conversation, it seems like it's not supported at all, so neither locally nor when deployed, so you'd need to remove it entirely 😓 

Since it doesn't look like it's supported on workers there isn't anything that can be done on our side 😕

So I think that the there are only two solutions here, you either need to remove that entirely from your code if possible or alternatively you can make sure that such `fetch` requests only run on the client 🤔

**Comment by ivolimasilva** [comment]
Yeah, that was what I was afraid of 😢 thanks nonetheless!
