### ISSUE TITLE
[🐛 Bug]: EPERM: operation not permitted on Windows 11 during build

### ISSUE THREAD

**Issue by bruceharrison1984** [cloudflare/next-on-pages#322]
### next-on-pages environment related information

```
System:
        Platform: win32
        Arch: x64
        Version: Windows 10 Pro
        CPU: (16) x64 AMD Ryzen 7 2700X Eight-Core Processor
        Memory: 32 GB
        Shell: C:\Program Files\Git\usr\bin\bash.exe
Binaries:
        Node: 18.13.0
        Yarn: N/A
        npm: 9.2.0
        pnpm: N/A
Package Manager Used: npm
Relevant Packages:
        @cloudflare/next-on-pages: 1.1.0
        vercel: [object Promise]
        next: [object Promise]
```

### Description

Attempting to build the default NextJS project fails OOTB on Windows 11.

### Reproduction

Starting with the default NextJS project that `npm create cloudflare@latest` produces, try to run `npm run pages:build`.

The build almost completes, then fails at the end with: 
```
Error: EPERM: operation not permitted, symlink 'index.func' -> 'C:\Users\leeha\development\test\.vercel\output\functions\index.rsc.func'
```

### Pages Deployment Method

Direct Upload (`wrangler pages publish` or the @cloudflare/pages-action GitHub Action)

### Would you like to help?

- [ ] Would you like to help fixing this bug?

**Comment by bruceharrison1984** [comment]
@james-elicx I can give it a shot on OSX and see how it goes. I had tried running as admin but got the same result. 

I appreciate the work so far though! This will be great once all the kinks are worked out.

**Comment by dario-piotrowicz** [comment]
I'm closing this issue as it seem like it's out of our control

I hope you don't mind @bruceharrison1984

I'm adding a warning saying that we don't recommend running next-on-pages on Windows hopefully that could make things slightly clearer for others in the future 🙂
