### ISSUE TITLE
[🐛 Bug]: Build failure with next-on-pages 1.0.2+

### ISSUE THREAD

**Issue by vbudovski** [cloudflare/next-on-pages#327]
### next-on-pages environment related information

```
System:
	Platform: darwin
	Arch: x64
	Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:22 PDT 2023; root:xnu-8796.121.3~7/RELEASE_X86_64
	CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
	Memory: 16 GB
	Shell: /bin/zsh
Binaries:
	Node: 16.20.0
	Yarn: N/A
	npm: 8.19.4
	pnpm: 8.6.0
Package Manager Used: npm
Relevant Packages:
	@cloudflare/next-on-pages: 1.0.2
	vercel: [object Promise]
	next: [object Promise]
```

### Description

Build fails on monorepo using PNPM and build system v2.
It succeeds with next-on-pages 1.0.1, but fails on both 1.0.2 and 1.1.0.

The build command (`pnpm --filter <workspace-name> exec next-on-pages`) succeeds locally with all versions, but fails on Cloudflare Pages.

```
13:38:26.697 | .../turbo@1.10.6/node_modules/turbo postinstall: Done
-- | --
13:38:26.751 | .../node_modules/workerd postinstall$ node install.js
13:38:26.963 | .../node_modules/workerd postinstall: /opt/buildhome/repo/node_modules/.pnpm/workerd@1.20230518.0/node_modules/workerd/bin/workerd: error while loading shared libraries: libc++.so.1: cannot open shared object file: No such file or directory
13:38:26.964 | .../node_modules/workerd postinstall: [workerd] Failed to validate workerd binary
13:38:26.964 | .../node_modules/workerd postinstall: Local development will not work. This usually means you're on an unsupported
13:38:26.965 | .../node_modules/workerd postinstall: operating system, or missing some shared libraries. On Debian-based systems,
13:38:26.965 | .../node_modules/workerd postinstall: make sure you've installed the `libc++1` package.
13:38:26.965 | .../node_modules/workerd postinstall: Done
13:38:27.689 | .../next-on-pages-vercel-cli preinstall$ node ./scripts/preinstall.js
13:38:27.785 | .../next-on-pages-vercel-cli preinstall: Done
13:38:28.310 |  
13:38:28.311 | devDependencies:
13:38:28.311 | + husky 8.0.3
13:38:28.311 | + lint-staged 13.2.2
13:38:28.311 | + prettier 2.8.8
13:38:28.311 | + turbo 1.10.6
13:38:28.311 |  
13:38:28.311 | . prepare$ husky install
13:38:28.436 | . prepare: husky - Git hooks installed
13:38:28.438 | . prepare: Done
13:38:28.443 | Done in 38s
13:38:28.490 | Executing user command: pnpm --filter web build-pages
13:38:29.376 |  
13:38:29.377 | > web@0.1.0 build-pages /opt/buildhome/repo/apps/web
13:38:29.377 | > next-on-pages
13:38:29.377 |  
13:38:29.600 | ⚡️ @cloudflare/next-on-pages CLI v.1.0.2
13:38:29.603 | ⚡️ Detected Package Manager: pnpm
13:38:29.603 | ⚡️ Preparing project...
13:38:29.605 | ⚡️ Project is ready
13:38:29.605 | ⚡️ Building project...
13:38:31.058 | ▲  undefined
13:38:31.059 | ▲  ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL  Command failed with ENOENT: next-on-pages-vercel-cli build
13:38:31.059 | ▲  spawn next-on-pages-vercel-cli ENOENT
13:38:31.059 | ▲
13:38:31.059 | ▲  Command "next-on-pages-vercel-cli" not found.
```

### Reproduction

1. Set up a monorepo with Next.js app inside a workspace
2. Add next-on-pages as a dev dependency for the workspace.
3. Run `pnpm --filter <workspace-name> exec next-on-pages` as the build command in Cloudflare Pages

### Pages Deployment Method

Pages CI (GitHub/GitLab integration)

### Would you like to help?

- [ ] Would you like to help fixing this bug?

**Comment by james-elicx** [comment]
Hello, sorry to hear you're having issues 🙁. For future reference, it'd be appreciated if you use the latest release (v1.1.0) when opening issues - in this case, the latest release is back to using `vercel` instead of `next-on-pages-vercel-cli`.

Please can you try using the prerelease in https://github.com/cloudflare/next-on-pages/pull/317#issuecomment-1594343036? I believe it should have resolved the command not found issue. You can also try adding `vercel` as a dev dependency with the latest release.

**Comment by vbudovski** [comment]
Hi @james-elicx, I believe I did try adding vercel dependency in 1.1.10 -- no improvement. Can confirm that the pre-release does build!

**Comment by james-elicx** [comment]
> Can confirm that the pre-release does build!

Glad to hear the prerelease worked! It should be included in the next release pretty soon. 🙂

**Comment by dario-piotrowicz** [comment]
@vbudovski we've release the change, please try [`1.1.1`](https://www.npmjs.com/package/@cloudflare/next-on-pages/v/1.1.1) 🙂 

Let me know if it's working fine for you 🙂

**Comment by vbudovski** [comment]
Thanks @dario-piotrowicz! Can confirm that 1.1.1 works.

**Comment by dario-piotrowicz** [comment]
@vbudovski Awesome, thanks a lot for confirming it (and for closing the issue) 😃:+1:
