### ISSUE TITLE
[🐛 Bug]: Redirecting in middleware causes query string parameters to be retained

### ISSUE THREAD

**Issue by madjam002** [cloudflare/next-on-pages#335]
### next-on-pages environment related information

Relevant Packages:
	@cloudflare/next-on-pages: 1.1.0

### Description

If you create a middleware and return a redirect like so:

```
return new Response('', {
        status: 302,
        headers: {
          Location: 'http://localhost:8788/',
        }
      })
```

If the original request URL has query string parameters like `?foo=bar`, the Location header will be `http://localhost:8788/?foo=bar` which is not the intended redirect URL.

Same behaviour is exhibited if using `Response.redirect` or `NextResponse.redirect`.

This seems to be causing the issue: https://github.com/cloudflare/next-on-pages/blob/2c8748176ffed5d50585bd86e14b1f2c974d0c96/packages/next-on-pages/templates/_worker.js/handleRequest.ts#L75

Commenting this out and just returning the unmodified Location header results in the correct Location header being returned.

### Pages Deployment Method

Direct Upload (`wrangler pages publish` or the @cloudflare/pages-action GitHub Action)

### Would you like to help?

- [ ] Would you like to help fixing this bug?

**Comment by james-elicx** [comment]
Hey there, thanks for raising this - we merged a fix for this issue yesterday and it should be included in the next release. Alternatively, you can try it out now in the latest beta release 🙂
