### ISSUE TITLE
[🐛 Bug]: new NextResponse() ignoring 2xx status codes, always returning 404

### ISSUE THREAD

**Issue by madjam002** [cloudflare/next-on-pages#341]
### next-on-pages environment related information

`"@cloudflare/next-on-pages": "0.0.0-f879ffd"`

### Description

Returning a new Response with a status code of 200 will always return status code 404.

E.g:

```
return new NextResponse(
      `Hello, world`,
      {
        status: 200,
        headers: {
          'content-type': 'text/html',
        },
      },
    )
```

If you return a status code of 400 it will work, but a 200 status code does not and will always result in 404.

The bug seems to be caused by this line:
https://github.com/cloudflare/next-on-pages/blob/f879ffd7f6031bdff6420ad53047aa31c3c39f97/packages/next-on-pages/templates/_worker.js/routes-matcher.ts#L564

Removing the `this.status < 400` check fixes the issue, but I assume this is here for other reasons.

### Pages Deployment Method

None

### Would you like to help?

- [ ] Would you like to help fixing this bug?

**Comment by james-elicx** [comment]
Hey there, thank you for raising this issue.

It appears I didn't quite bail out of routing completing when I added the change to account for returning `new NextResponse` 🙈, so it would have always gone through the check for the route existing in the build output.

I have just opened a PR that should resolve this, and I would welcome you to try out the prerelease in https://github.com/cloudflare/next-on-pages/pull/342#issuecomment-1609165186 🙂.
