### ISSUE TITLE
[🐛 Bug]: /.next/

### ISSUE THREAD

**Issue by Likenttt** [cloudflare/next-on-pages#359]
### next-on-pages environment related information

Nothing wrong

### Description

Build command:npx @cloudflare/next-on-pages@1
Build output directory: /.vercel/output/static
Build system version:1 (latest)
Root directory:/

My project archtecture:
.
├── README.md
├── functions
│   └── api
│       └── v1
│           ├── auth
│           │   ├── discord
│           │   │   ├── callback.ts
│           │   │   └── redirect.ts
│           │   ├── github
│           │   │   ├── callback.ts
│           │   │   └── redirect.ts
│           │   ├── google
│           │   │   ├── callback.ts
│           │   │   └── redirect.ts
│           │   └── spotify
│           │       ├── callback.ts
│           │       └── redirect.ts
│           └── user
│               └── me.ts
├── lib
│   ├── providers
│   │   └── AuthProvider.tsx
│   └── utils
│       ├── dark-theme.ts
│       ├── local-storage.ts
│       └── session.ts
├── next-env.d.ts
├── next.config.js
├── package-lock.json
├── package.json
├── pages
│   ├── _app.tsx
│   ├── index.tsx
│   └── me.tsx
├── postcss.config.js
├── public
│   ├── favicon.svg
│   ├── logo.png
│   ├── pwa-192x192.png
│   ├── pwa-512x512.png
│   ├── robots.txt
│   └── safari-pinned-tab.svg
├── styles
│   └── globals.css
├── tailwind.config.js
├── tsconfig.json
├── wrangler.toml
└── yarn.lock

15 directories, 33 files

But if I set output dir `Build output directory: /.vercel/output/static`, the apis are 404. If I set `Build output directory: /.vercel/output`, the apis are available but the static pages cannot be loaded correctly. So how to use the outdir on earth? 

### Pages Deployment Method

Pages CI (GitHub/GitLab integration)

### Would you like to help?

- [x] Would you like to help fixing this bug?

**Comment by dario-piotrowicz** [comment]
Hi @Likenttt

By looking at your files structure and your issue description you application seems to be to be for a static site, is that correct?

If that's the case you shouldn't be using next-on-pages but you should build your next application as a static one as indicated in the [Next.js Cloudflare Pages guide](https://developers.cloudflare.com/pages/framework-guides/deploy-a-nextjs-site/#use-a-static-export).

Meaning that your build command should be `npm run build` and your build directory `out` (your `/functions` directory will get picked up from the root so there is no need for any extra configuration there)

<details>

<summary>not static?</summary>

If instead you actually wanted to deploy a full stack next.js app via next-on-pages, then you shouldn't be using the `/functions` directory but Next [api routes](https://nextjs.org/docs/api-routes/introduction) instead.

And then the build output directory should be `.vercel/output/static` (without the `/` at the beginning)

But I doubt that's what you want here 🤔 

</details>

I hope the above helps 🙂

**Comment by Likenttt** [comment]
> Hi @Likenttt
> 
> By looking at your files structure and your issue description you application seems to be to be for a static site, is that correct?
> 
> If that's the case you shouldn't be using next-on-pages but you should build your next application as a static one as indicated in the [Next.js Cloudflare Pages guide](https://developers.cloudflare.com/pages/framework-guides/deploy-a-nextjs-site/#use-a-static-export).
> 
> Meaning that your build command should be `npm run build` and your build directory `out` (your `/functions` directory will get picked up from the root so there is no need for any extra configuration there)
> 
> not static?
> If instead you actually wanted to deploy a full stack next.js app via next-on-pages, then you shouldn't be using the `/functions` directory but Next [api routes](https://nextjs.org/docs/api-routes/introduction) instead.
> 
> And then the build output directory should be `.vercel/output/static` (without the `/` at the beginning)
> 
> But I doubt that's what you want here 🤔
> 
> I hope the above helps 🙂

Thanks. I got a similar reply from your colleague on discord.  https://discord.com/channels/595317990191398933/1125353798387368017/1125356095100162079 I will try next Edge api. Have a nice day~

**Comment by Likenttt** [comment]
> Hi @Likenttt
> 
> By looking at your files structure and your issue description you application seems to be to be for a static site, is that correct?
> 
> If that's the case you shouldn't be using next-on-pages but you should build your next application as a static one as indicated in the [Next.js Cloudflare Pages guide](https://developers.cloudflare.com/pages/framework-guides/deploy-a-nextjs-site/#use-a-static-export).
> 
> Meaning that your build command should be `npm run build` and your build directory `out` (your `/functions` directory will get picked up from the root so there is no need for any extra configuration there)
> 
> not static?
> I hope the above helps 🙂

Thanks I will try Next Edge API. Your colleague gave me a similar suggestion https://discord.com/channels/595317990191398933/1125353798387368017/1125356095100162079

**Comment by dario-piotrowicz** [comment]
I'm closing this isn't hopefully a real issue

@Likenttt I hope you solved your issue if not we're always here (and on discord) to help? 🙂
