### ISSUE TITLE
[🐛 Bug]: Cant setup next-on-pages with chat-ui

### ISSUE THREAD

**Issue by martwozniak** [cloudflare/next-on-pages#368]
### next-on-pages environment related information

System:
        Platform: win32
        Arch: x64
        Version: Windows 10 Pro
        CPU: (16) x64 AMD Ryzen 7 2700X Eight-Core Processor
        Memory: 32 GB
        Shell: C:\Program Files\Git\usr\bin\bash.exe
Binaries:
        Node: 18.16.1
        Yarn: 1.22.19
        npm: 9.5.1
        pnpm: N/A
Package Manager Used: yarn (classic)
Relevant Packages:
        @cloudflare/next-on-pages: 1.2.0
        vercel: N/A
        next: N/A

### Description

I want to setup https://github.com/mckaywrigley/chatbot-ui with next-on-pages , but it isn't possible.
I am getting errors all the time. Even static build isn't possible (`next export`).

When I setup 
`runtime: 'experimental-edge' /  runtime: 'edge'`

and add:
`
export const config = {
  runtime: 'edge',
}; 
`
Page is not building itself. 

### Reproduction

Clone repo: https://github.com/mckaywrigley/chatbot-ui   (or simply create fork)
Meke it your private repo 
Add `runtime: 'experimental-edge' ` to your `next.config.js`
Add `export const config = {
  runtime: 'edge',
};` to your routes. 
Go to Cloudflare Pages
Add your repository and choose Next.js preset 

### Pages Deployment Method

Pages CI (GitHub/GitLab integration)

### Pages Deployment ID

No deployment available

### Additional Information

<html>
<body>

20:51:25.377 | warn  - /api/home provided runtime 'experimental-edge'. It can be updated to 'edge' instead.
-- | --
20:51:25.382 | warn  - You are using an experimental edge runtime, the API might change.
20:51:25.675 | warn  - You ase using `experimental.runtime` which was removed. Check https://nextjs.org/docs/api-routes/edge-api-routes on how to use edge runtime.
20:51:59.344 | <w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (103kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)
20:51:59.945 | <w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (103kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)
20:51:59.951 | <w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (104kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)
20:52:03.988 | Failed to compile.
20:52:03.989 |  
20:52:03.989 | ./node_modules/core-js/internals/global.js
20:52:03.989 | Dynamic Code Evaluation (e. g. 'eval', 'new Function', 'WebAssembly.compile') not allowed in Edge Runtime
20:52:03.989 | Learn More: https://nextjs.org/docs/messages/edge-dynamic-code-evaluation
20:52:03.990 |  
20:52:03.990 | Import trace for requested module:
20:52:03.990 | ./node_modules/core-js/internals/global.js
20:52:03.990 | ./node_modules/core-js/modules/web.dom-collections.iterator.js
20:52:03.990 | ./node_modules/next-i18next/dist/commonjs/serverSideTranslations.js
20:52:03.990 | ./node_modules/next-i18next/serverSideTranslations.js
20:52:03.990 |  
20:52:03.990 | ./node_modules/core-js/internals/global.js
20:52:03.991 | Dynamic Code Evaluation (e. g. 'eval', 'new Function', 'WebAssembly.compile') not allowed in Edge Runtime
20:52:03.991 | Learn More: https://nextjs.org/docs/messages/edge-dynamic-code-evaluation
20:52:03.991 |  
20:52:03.991 | Import trace for requested module:
20:52:03.991 | ./node_modules/core-js/internals/global.js
20:52:03.991 | ./node_modules/core-js/modules/web.dom-collections.iterator.js
20:52:03.991 | ./node_modules/next-i18next/dist/commonjs/serverSideTranslations.js
20:52:03.991 | ./node_modules/next-i18next/serverSideTranslations.js
20:52:03.991 |  
20:52:03.992 | ./node_modules/jsdom/lib/jsdom/living/helpers/create-event-accessor.js
20:52:03.992 | Dynamic Code Evaluation (e. g. 'eval', 'new Function', 'WebAssembly.compile') not allowed in Edge Runtime
20:52:03.992 | Learn More: https://nextjs.org/docs/messages/edge-dynamic-code-evaluation
20:52:03.992 |  
20:52:03.992 | Import trace for requested module:
20:52:03.992 | ./node_modules/jsdom/lib/jsdom/living/helpers/create-event-accessor.js
20:52:03.992 | ./node_modules/jsdom/lib/jsdom/browser/Window.js
20:52:03.992 | ./node_modules/jsdom/lib/api.js
20:52:03.992 |  
20:52:03.993 | ./node_modules/jsdom/lib/jsdom/vm-shim.js
20:52:03.993 | Dynamic Code Evaluation (e. g. 'eval', 'new Function', 'WebAssembly.compile') not allowed in Edge Runtime
20:52:03.993 | Learn More: https://nextjs.org/docs/messages/edge-dynamic-code-evaluation
20:52:03.993 |  
20:52:03.993 | Import trace for requested module:
20:52:03.993 | ./node_modules/jsdom/lib/jsdom/vm-shim.js
20:52:03.993 | ./node_modules/jsdom/lib/api.js
20:52:03.993 |  
20:52:03.993 | ./node_modules/nwsapi/src/nwsapi.js
20:52:03.994 | Dynamic Code Evaluation (e. g. 'eval', 'new Function', 'WebAssembly.compile') not allowed in Edge Runtime
20:52:03.994 | Learn More: https://nextjs.org/docs/messages/edge-dynamic-code-evaluation
20:52:03.994 |  
20:52:03.994 | Import trace for requested module:
20:52:03.994 | ./node_modules/nwsapi/src/nwsapi.js
20:52:03.994 | ./node_modules/jsdom/lib/jsdom/living/helpers/selectors.js
20:52:03.994 | ./node_modules/jsdom/lib/jsdom/living/helpers/style-rules.js
20:52:03.994 | ./node_modules/jsdom/lib/jsdom/browser/Window.js
20:52:03.995 | ./node_modules/jsdom/lib/api.js
20:52:03.995 |  
20:52:03.995 |  
20:52:03.995 | > Build failed because of webpack errors
20:52:04.109 | Failed: build command exited with code: 1
20:52:05.585 | Failed: error occurred while running build command

</body>
</html>

### Would you like to help?

- [X] Would you like to help fixing this bug?

**Comment by dario-piotrowicz** [comment]
Hi @martwozniak, it seems like the application you are trying to migrate to Cloudflare pages is quite incompatible with the Cloudflare runtime.

I can see in the repository you shared things like docker and kubernetes which are technologies very much opposite to what the Cloudflare edge runtime is all about (very fast stateless code run on the edge). Anything using such technologies will always be at a very fundamental level very incompatible with the Cloudflare runtime (which Pages runs on).

___

More specifically your error messages say that the application or better, some libraries used by it are trying to dynamically evaluate some code, which for security reasons is not allowed in the [Cloudflare runtime](https://developers.cloudflare.com/workers/runtime-apis/web-standards/#javascript-standards) (it is also not allowed in the Next.js edge runtime as you can see in [their documentation](https://nextjs.org/docs/messages/edge-dynamic-code-evaluation)). 
You could try seeing if there are alternative libraries that the application could use that don't require dynamic code evaluations but I think that that would prove to be quite challenging, moreover based on my comment above I suspect that solving this issue will just unveil countless others that are most likely not really solvable. 

___

I'm sorry to disappoint you, but I don't think that there is any reasonable way to deploy the application you shared to Cloudflare Pages, I can only suggest you to deploy it via other platforms, Vercel should be very suited for that (as their network is different from Cloudflare's, but not on the edge as I mentioned above).

But thank you so much for considering Cloudflare 🙏, sorry again that our runtime can't satisfy your needs 🙇

**Comment by grski** [comment]
@dario-piotrowicz thanks for the reply, we discussed this, Marcin just informed me. 
Side note: we are NOT considering using cloudflare, but rather powering all of our projects with it already, this being a new addition to the suite ;) I'm a cf fan boy, hence I wanted us to try.

@martwozniak thanks for verifying this.

**Comment by dario-piotrowicz** [comment]
@grski no problem, my pleasure 🙂 

As I mentioned I'm sorry that Pages could not host your application, I'm glad you're using Cloudflare for your projects and thanks for trying next-on-pages! 😄

I hope that maybe you'll get a chance to use next-on-pages for some application sometime 🙂
