### ISSUE TITLE
Pages not created when using Localize / Internationalize on NextJS

### ISSUE THREAD

**Issue by AnaArbealez** [cloudflare/next-on-pages#37]
I'm using the follow configuration to use internationalization on my app:

1) on next.config.js:

```
const nextTranslate = require('next-translate')

const nextConfig = {
    experimental: {
        runtime: 'experimental-edge',
    },

module.exports = withPlugins(
    [nextTranslate, ..],
    nextConfig,
);
```

2)i18n.js file: 
```
module.exports = {
    locales: ['en-IE'],
    defaultLocale: 'en-IE',
    pages: {
        '*': ['common'],
    },
    loadLocaleFrom: (lang, ns) => {
        const translation = lang.slice(0, 2);

        return import(`./locales/${translation}/${ns}.json`).then(
            (m) => m.default,
        );
    },
};
```

3)   NextJS version:
` "next": "12.2.6"`

Deployments are successful on Deploying to Cloudflare global network messages (no errors), but in the end, pages are not created for every single language.

**Comment by james-elicx** [comment]
I believe that we may have identified a way that we can support the `i18n` option from the `next.config.js`, now that we have the new routing system. I'll be looking into a way to introduce proper support.

**Comment by dario-piotrowicz** [comment]
@AnaArbealez, we've just merged a PR @james-elicx made that should have fixed this issue, if you want please have a look using our latest beta version: https://www.npmjs.com/package/@cloudflare/next-on-pages/v/0.0.0-86df485 to see if everything works as expected for you now :slightly_smiling_face: :pray: 

PS: sorry it took so long to address this issue :bow:

**Comment by james-elicx** [comment]
> I've tried several configurations but my brain has run out of ideas. If you have an idea or a concrete example with next translate?

Hey there @loicy, sorry to hear it's not working properly for you. We have an example app that we use over at [dario-piotrowicz/next-apps-for-testing](https://github.com/dario-piotrowicz/next-apps-for-testing/tree/master/apps/i18n-next-translate-13.4.1). I noticed that our test app and your code has differences in how the i18n config is defined.

Our repository is based on the starter from `next-translate`, so you could try doing something similar to that and see how things go perhaps?

I'm sure you already are, but please also ensure you are running the latest version of next-on-pages 🙂

**Comment by loicy** [comment]
Hey back @james-elicx 

Thanks for your reply.

I tested it with the same configuration and it's the same problem.

I've made the repo public = [](https://github.com/loicy/cloudflare-page-next-v3)

I also put the url of the Cloudflage page: [](https://cloudflare-page-next-v3.pages.dev/)

I've also noticed that the /api/hello API returns an internal error.

**Comment by james-elicx** [comment]
> Hey back @james-elicx
> 
> Thanks for your reply.
> 
> I tested it with the same configuration and it's the same problem.
> 
> I've made the repo public = [loicy/cloudflare-page-next-v3](https://github.com/loicy/cloudflare-page-next-v3)

Thank you for providing a reproduction @loicy. I've traced the problem back to what appears to be an issue in the Vercel build output config.

I have opened a PR with what I believe should fix the issue for SSR'd index pages and would welcome you to try the prerelease in https://github.com/cloudflare/next-on-pages/pull/315#issuecomment-1592057631.

> I've also noticed that the /api/hello API returns an internal error.

Your API route is throwing an internal server error because you are trying to use the NodeJS format instead of the Edge runtime format. See the [Next.js docs](https://nextjs.org/docs/pages/building-your-application/routing/api-routes#edge-api-routes) for more info.

**Comment by loicy** [comment]
Yo back,

I've tested pre-release 315 and it doesn't seem to work.

As far as the Api is concerned, it's fine. Sorry for the inconvenience.

**Comment by james-elicx** [comment]
> Yo back,
> 
> I've tested pre-release 315 and it doesn't seem to work.
> 
> As far as the Api is concerned, it's fine. Sorry for the inconvenience.

Hello @loicy, please can you triple check that you are using the prerelease. It is working fine.

Here is a deployed version of your app using the prerelease and the problems you mentioned are resolved...

https://nop-issue-i18n-repro.pages.dev/

**Comment by dario-piotrowicz** [comment]
> Yo back,
> 
> I've tested pre-release 315 and it doesn't seem to work.

just to make sure, if you use `npx` and have a `next-on-pages` version installed it'll just delegate to that one (this bit me in the past 😅), have you checked the command's log to make sure that the version is the one you'd expect?

![Screenshot 2023-06-15 at 11 52 24](https://github.com/cloudflare/next-on-pages/assets/61631103/156965a5-fcb3-4ffb-9477-612337a84c66)

**Comment by loicy** [comment]
Hello !

Very quick fix, thank you very much!

It was my fault, I had made a mistake in ordering the build.
