### ISSUE TITLE
[🐛 Bug]: Various API Routes Issue & @vercel/og Issue

### ISSUE THREAD

**Issue by thomaswang** [cloudflare/next-on-pages#376]
### next-on-pages environment related information

System:
        Platform: darwin
        Arch: arm64
        Version: Darwin Kernel Version 22.5.0: Mon Apr 24 20:52:24 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6000
        CPU: (10) arm64 Apple M1 Pro
        Memory: 16 GB
        Shell: /bin/zsh

Binaries:
        Node: 18.16.1
        Yarn: 1.22.19
        npm: 9.5.1
        pnpm: 8.6.6

Package Manager Used: pnpm

Relevant Packages:
        @cloudflare/next-on-pages: 1.2.0
        vercel: N/A
        next: 13.4.9

### Description

API routes doesn't seem to function correctly on CF Pages despite it working locally and on Vercel. I'm providing the basic example below of hitting the GitHub API that returns an error. 

I'm also having trouble with the @vercel/og API route using `import { ImageResponse } from "next/server"` that returns a `500 Internal Service Error` but that example is a bit more opaque. 

Current deployment on Vercel (https://thomas.wang) where both API routes are fine over there: 

- https://thomas.wang/api/github
- https://thomas.wang/api/og

The most basic API route does work though (https://409ff03f.thomaswang.pages.dev/api):

```js
import { BUILD_URL } from "utilities/constants"
import { NextResponse } from "next/server"

export const runtime = "edge"

export async function GET() {
  return new NextResponse(
    JSON.stringify(
      {
        github_url: `${BUILD_URL}/api/github`,
        og_url: `${BUILD_URL}/api/og`
      },
      null,
      2
    ),
    { status: 200, headers: { "Content-Type": "application/json" } }
  )
}
```

### Reproduction

https://409ff03f.thomaswang.pages.dev/api/github

Error message:
```
{
  "statusCode": 400,
  "message": "Unexpected token 'R', \"\r\nRequest fo\"... is not valid JSON"
}
```

```js
import { NextResponse } from "next/server"

export const runtime = "edge"

export async function GET() {
  try {
    const json = await (
      await fetch("https://api.github.com/users/thomaswang")
    ).json()

    return new NextResponse(JSON.stringify(json, null, 2), {
      status: 200,
      headers: {
        "Content-Type": "application/json",
        "Cache-Control": "public, s-maxage=10, stale-while-revalidate"
      }
    })
  } catch (error) {
    return new NextResponse(
      JSON.stringify(
        {
          statusCode: 400,
          message:
            error?.message.toString() ||
            error.toString() ||
            "An unexpected error occurred."
        },
        null,
        2
      ),
      {
        status: 400,
        headers: {
          "Content-Type": "application/json",
          "Cache-Control": "public, s-maxage=86400, stale-while-revalidate"
        }
      }
    )
  }
}
```

### Pages Deployment Method

Pages CI (GitHub/GitLab integration)

### Pages Deployment ID

https://409ff03f.thomaswang.pages.dev/

### Would you like to help?

- [ ] Would you like to help fixing this bug?

**Comment by thomaswang** [comment]
Thanks for the help @dario-piotrowicz!

When you say you ran the code and logged the response, do you mean you simulated the code in a worker environment (like [miniflare](https://github.com/cloudflare/miniflare))?

**Comment by dario-piotrowicz** [comment]
Ok got it, Next.js seems to set the user-agent header: https://github.com/vercel/next.js/blob/62c2c5abc2f7f3cfa99e66bacd64b1d56d45e85c/packages/next/src/server/web/sandbox/context.ts#L319

We should be able to do that simply by monkey patching fetch, I'll open a PR soon (today or in the new few days) with a fix 🙂

**Comment by thomaswang** [comment]
Thanks @dario-piotrowicz I seemed to have missed that.

Have the prerelease installed now and using getting this error in my @vercel/og locally:

```
[mf:inf] GET /api/og 500 Internal Server Error (12ms)
Error: Some functionality, such as asynchronous I/O, timeouts, and generating random values, can only be performed while handling a request.
    at Object.apply (unvhu1jt83.js:22:20)
    at Object.U (__next-on-pages-dist__/chunks/548.js:2:924)
    at g (__next-on-pages-dist__/functions/middleware.func.js:1:136)
    at __next-on-pages-dist__/functions/api/og.func.js:1:5605
    at w (__next-on-pages-dist__/functions/middleware.func.js:1:1518)
    at o (__next-on-pages-dist__/functions/api/og.func.js:1:5086)
    at __next-on-pages-dist__/functions/api/og.func.js:1:5330 {
  stack: Error: Some functionality, such as asynchronous I/…t-on-pages-dist__/functions/api/og.func.js:1:5330,
  message: Some functionality, such as asynchronous I/O, time…, can only be performed while handling a request.
}
```

**Comment by dario-piotrowicz** [comment]
> Thanks @dario-piotrowicz I seemed to have missed that.
> 
> Have the prerelease installed now and getting this error in my `/api/og` API route locally:
> 
> ```
> [mf:inf] GET /api/og 500 Internal Server Error (12ms)
> Error: Some functionality, such as asynchronous I/O, timeouts, and generating random values, can only be performed while handling a request.
>     at Object.apply (unvhu1jt83.js:22:20)
>     at Object.U (__next-on-pages-dist__/chunks/548.js:2:924)
>     at g (__next-on-pages-dist__/functions/middleware.func.js:1:136)
>     at __next-on-pages-dist__/functions/api/og.func.js:1:5605
>     at w (__next-on-pages-dist__/functions/middleware.func.js:1:1518)
>     at o (__next-on-pages-dist__/functions/api/og.func.js:1:5086)
>     at __next-on-pages-dist__/functions/api/og.func.js:1:5330 {
>   stack: Error: Some functionality, such as asynchronous I/…t-on-pages-dist__/functions/api/og.func.js:1:5330,
>   message: Some functionality, such as asynchronous I/O, time…, can only be performed while handling a request.
> }
> ```

mh... that shouldn't happen 😓 can you double check and make sure that at the start next-on-pages logs the correct version?

**Comment by thomaswang** [comment]
This is the code for `/api/og`:

```js
import { ImageResponse } from "next/server"

import type { NextRequest } from "next/server"
import { BUILD_URL } from "utilities/constants"

export const runtime = "edge"

const font = fetch(
  new URL("../../../public/font/HelveticaNeue.ttf", import.meta.url)
).then((res) => res.arrayBuffer())

export async function GET(req: NextRequest) {
  const fontData = await font
  const { searchParams } = req.nextUrl
  const isTwitter = searchParams.get("twitter") ? true : false

  return new ImageResponse(
    (
      <div tw="flex flex-col justify-between bg-neutral-50 w-full h-full pl-20 pr-48 py-12">
        <img // eslint-disable-line
          tw="rounded-full w-20 h-20"
          src={`${BUILD_URL}/thomas.jpg`}
          width={80}
          height={80}
        />
        <div
          style={{
            fontSize: 72
          }}
        >
          Thomas Wang
        </div>
      </div>
    ),
    {
      width: 1200,
      height: isTwitter ? 600 : 630,
      fonts: [
        {
          name: "Helvetica Neue",
          data: fontData,
          style: "normal"
        }
      ]
    }
  )
}
```

**Comment by dario-piotrowicz** [comment]
> @dario-piotrowicz sorry not sure exactly what you mean by "at the start logs the correct version" -- do you mean this:
> 
> ```
> $ npx @cloudflare/next-on-pages
> ⚡️ @cloudflare/next-on-pages CLI v.1.2.0
> ⚡️ Detected Package Manager: pnpm
> ⚡️ Preparing project...
> ⚡️ Project is ready


sorry for not being too clear 🙏 , anyways yeah I meant when you run the next-on-pages CLI, there you can see that you are running v.1.2.0. That version does not include the fix, to get the fix you should make sure to use the prerelease version, when you do you should clearly see that the version is a prerelease one:
<img width="1160" alt="Screenshot 2023-07-10 at 10 02 33" src="https://github.com/cloudflare/next-on-pages/assets/61631103/c66d2b6c-facf-4e48-87db-4ef95c868b06">

(PS: note that if you run the command with `npx` and have an installed dependency npx` will default to that, to be extra sure to get the right one I would suggest to actually npm install it)

**Comment by thomaswang** [comment]
Oh nevermind -- found the issue. Had to update the lockfile manually... for some reason running https://github.com/cloudflare/next-on-pages/pull/325#issuecomment-1604457773 didn't update the dependency there

<img width="434" alt="CleanShot 2023-07-10 at 14 28 35@2x" src="https://github.com/cloudflare/next-on-pages/assets/41944255/8930dafe-7308-4f18-9c71-52daf2565174">
<img width="502" alt="CleanShot 2023-07-10 at 14 28 10@2x" src="https://github.com/cloudflare/next-on-pages/assets/41944255/4e3b343e-3163-464d-b5f6-eff3dc1479ce">

**Comment by thomaswang** [comment]
Thanks @dario-piotrowicz! Closing now :)
