### ISSUE TITLE
[🐛 Build Error]: Module not found: Can't resolve 'crypto'

### ISSUE THREAD

**Issue by fineshop** [cloudflare/next-on-pages#384]
### next-on-pages environment related information

Build log:

<html>
<body>

Time | Log
-- | --
14:24:35.240 | ▲  > next build
14:24:36.105 | ▲  Attention: Next.js now collects completely anonymous telemetry regarding usage.
14:24:36.105 | ▲  This information is used to shape Next.js' roadmap and prioritize features.
14:24:36.105 | ▲  You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
14:24:36.105 | ▲  https://nextjs.org/telemetry
14:24:36.829 | ▲  - info Creating an optimized production build...
14:24:37.405 | ▲  - info Disabled SWC as replacement for Babel because of custom Babel configuration ".babelrc" https://nextjs.org/docs/messages/swc-disabled
14:24:37.888 | ▲  - info Using external babel configuration from /opt/buildhome/repo/.babelrc
14:24:56.748 | ▲  Failed to compile.
14:24:56.748 | ▲
14:24:56.748 | ▲  ./node_modules/next/dist/esm/server/lib/incremental-cache/index.js:465:24
14:24:56.748 | ▲  Module not found: Can't resolve 'crypto'
14:24:56.749 | ▲
14:24:56.749 | ▲  https://nextjs.org/docs/messages/module-not-found
14:24:56.749 | ▲
14:24:56.749 | ▲  Import trace for requested module:
14:24:56.749 | ▲  ./node_modules/next/dist/esm/server/web/edge-route-module-wrapper.js
14:24:56.749 | ▲  ./node_modules/next/dist/build/webpack/loaders/next-edge-app-route-loader/index.js?absolutePagePath=private-next-app-dir%2Fapi%2Fcontact%2Froute.ts&page=%2Fapi%2Fcontact%2Froute&appDirLoader=bmV4dC1hcHAtbG9hZGVyP25hbWU9YXBwJTJGYXBpJTJGY29udGFjdCUyRnJvdXRlJnBhZ2U9JTJGYXBpJTJGY29udGFjdCUyRnJvdXRlJnBhZ2VQYXRoPXByaXZhdGUtbmV4dC1hcHAtZGlyJTJGYXBpJTJGY29udGFjdCUyRnJvdXRlLnRzJmFwcERpcj0lMkZvcHQlMkZidWlsZGhvbWUlMkZyZXBvJTJGc3JjJTJGYXBwJmFwcFBhdGhzPSUyRmFwaSUyRmNvbnRhY3QlMkZyb3V0ZSZwYWdlRXh0ZW5zaW9ucz10c3gmcGFnZUV4dGVuc2lvbnM9dHMmcGFnZUV4dGVuc2lvbnM9anN4JnBhZ2VFeHRlbnNpb25zPWpzJmJhc2VQYXRoPSZhc3NldFByZWZpeD0mbmV4dENvbmZpZ091dHB1dD0mcHJlZmVycmVkUmVnaW9uPSZtaWRkbGV3YXJlQ29uZmlnPWUzMCUzRCE%3D&nextConfigOutput=&preferredRegion=&middlewareConfig=e30%3D!
14:24:56.749 | ▲
14:24:56.749 | ▲
14:24:56.750 | ▲  > Build failed because of webpack errors
14:24:56.797 | ▲  Error: Command "npm run build" exited with 1
14:24:56.908 |  
14:24:56.909 | ⚡️ The Vercel build (`npx vercel build`) command failed. For more details see the Vercel logs above.
14:24:56.909 | ⚡️ If you need help solving the issue, refer to the Vercel or Next.js documentation or their repositories.
14:24:56.909 |  
14:24:56.946 | Failed: build command exited with code: 1
14:24:57.652 | Failed: error occurred while running build command

</body>
</html>

App folder: Yes

Error only occurs when I add api routes, for e.g. when I add `app/src/api/contact/route.ts`

Contents of `app/src/api/contact/route.ts`:

```
export async function GET(request: Request) {
  return new Response("Hello, Next.js!", {
    status: 200
  });
}

export const runtime = "edge";
```

Note that I am not using crypto module in my next.js project

### Description

I am trying to add api routes to my project but it's showing a Module not found error while building.

### Pages Deployment Method

None

### Pages Deployment ID

7781357

### Would you like to help?

- [ ] Would you like to help fixing this bug?

**Comment by dario-piotrowicz** [comment]
@fineshop I'm sorry for the late reply, I will look into this soon, I haven't yet started looking into this I'm currently waiting to be granted access to the deployment logs, I'll investigate further when I'm able (and I'd figured I should at least update you here 🙇)

but if you could share your code or provide more details (Next version, Vercel version, Node Version, what dependencies you have (that could require crypto), etc...) I could start looking into this sooner, please let me know if you can help 🙂

**Comment by gio-shara-code** [comment]
@dario-piotrowicz Hey, thanks for responding to this issue. I have the same error:

node: `v18.15.0`
pnpm: `8.6.1`
next: ` v13.4.12`

Build command: `pnpx @cloudflare/next-on-pages@1`

Error output:
```
@cloudflare/next-on-pages CLI v.1.5.0
⚡️ Detected Package Manager: pnpm
⚡️ Preparing project...
⚡️ Project is ready
⚡️ Building project...
▲  .../Library/pnpm/store/v3/tmp/dlx-29866  | Progress: resolved 1, reused 0, downloaded 0, added 0
▲  .../Library/pnpm/store/v3/tmp/dlx-29866  | Progress: resolved 191, reused 172, downloaded 0, added 0
▲  .../Library/pnpm/store/v3/tmp/dlx-29866  | +176 ++++++++++++++++++
▲  .../Library/pnpm/store/v3/tmp/dlx-29866  | Progress: resolved 195, reused 176, downloaded 0, added 176, done
▲  Vercel CLI 31.2.1
▲  Detected `pnpm-lock.yaml` version 6.1 generated by pnpm 8...
▲  Installing dependencies...
▲  Lockfile is up to date, resolution step is skipped
▲  Already up to date
▲  
▲  Done in 1.1s
▲  Detected Next.js version: 13.4.9
▲  Running "pnpm run build"
▲  > next@0.1.0 build /Users/gioshara/development/projects/netcore/next
▲  > next build
▲  - info Loaded env from /Users/gioshara/development/projects/netcore/next/.env.local
▲  - info Creating an optimized production build...
▲  - info Disabled SWC as replacement for Babel because of custom Babel configuration ".babelrc" https://nextjs.org/docs/messages/swc-disabled
▲  - info Using external babel configuration from /Users/gioshara/development/projects/netcore/next/.babelrc
▲  Failed to compile.
▲  
▲  ./node_modules/.pnpm/nodemailer@6.9.4/node_modules/nodemailer/lib/base64/index.js:3:18
▲  Module not found: Can't resolve 'stream'
▲  
▲  https://nextjs.org/docs/messages/module-not-found
▲  
▲  Import trace for requested module:
▲  ./node_modules/.pnpm/nodemailer@6.9.4/node_modules/nodemailer/lib/mime-funcs/index.js
▲  ./node_modules/.pnpm/nodemailer@6.9.4/node_modules/nodemailer/lib/mailer/mail-message.js
▲  ./node_modules/.pnpm/nodemailer@6.9.4/node_modules/nodemailer/lib/mailer/index.js
▲  ./node_modules/.pnpm/nodemailer@6.9.4/node_modules/nodemailer/lib/nodemailer.js
▲  ./src/app/api/contact/route.ts
▲  ./node_modules/.pnpm/next@13.4.9_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/webpack/loaders/next-edge-app-route-loader/index.js?absolutePagePath=private-next-app-dir%2Fapi%2Fcontact%2Froute.ts&page=%2Fapi%2Fcontact%2Froute&appDirLoader=bmV4dC1hcHAtbG9hZGVyP25hbWU9YXBwJTJGYXBpJTJGY29udGFjdCUyRnJvdXRlJnBhZ2U9JTJGYXBpJTJGY29udGFjdCUyRnJvdXRlJnBhZ2VQYXRoPXByaXZhdGUtbmV4dC1hcHAtZGlyJTJGYXBpJTJGY29udGFjdCUyRnJvdXRlLnRzJmFwcERpcj0lMkZVc2VycyUyRmdpb3NoYXJhJTJGZGV2ZWxvcG1lbnQlMkZwcm9qZWN0cyUyRm5ldGNvcmUlMkZuZXh0JTJGc3JjJTJGYXBwJmFwcFBhdGhzPSUyRmFwaSUyRmNvbnRhY3QlMkZyb3V0ZSZwYWdlRXh0ZW5zaW9ucz10c3gmcGFnZUV4dGVuc2lvbnM9dHMmcGFnZUV4dGVuc2lvbnM9anN4JnBhZ2VFeHRlbnNpb25zPWpzJmJhc2VQYXRoPSZhc3NldFByZWZpeD0mbmV4dENvbmZpZ091dHB1dD0mcHJlZmVycmVkUmVnaW9uPSZtaWRkbGV3YXJlQ29uZmlnPWUzMCUzRCE%3D&nextConfigOutput=&preferredRegion=&middlewareConfig=e30%3D!
▲  
▲  ./node_modules/.pnpm/nodemailer@6.9.4/node_modules/nodemailer/lib/dkim/index.js:9:20
▲  Module not found: Can't resolve 'stream'
▲  
▲  https://nextjs.org/docs/messages/module-not-found
▲  
▲  Import trace for requested module:
▲  ./node_modules/.pnpm/nodemailer@6.9.4/node_modules/nodemailer/lib/mailer/index.js
▲  ./node_modules/.pnpm/nodemailer@6.9.4/node_modules/nodemailer/lib/nodemailer.js
▲  ./src/app/api/contact/route.ts
▲  ./node_modules/.pnpm/next@13.4.9_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/webpack/loaders/next-edge-app-route-loader/index.js?absolutePagePath=private-next-app-dir%2Fapi%2Fcontact%2Froute.ts&page=%2Fapi%2Fcontact%2Froute&appDirLoader=bmV4dC1hcHAtbG9hZGVyP25hbWU9YXBwJTJGYXBpJTJGY29udGFjdCUyRnJvdXRlJnBhZ2U9JTJGYXBpJTJGY29udGFjdCUyRnJvdXRlJnBhZ2VQYXRoPXByaXZhdGUtbmV4dC1hcHAtZGlyJTJGYXBpJTJGY29udGFjdCUyRnJvdXRlLnRzJmFwcERpcj0lMkZVc2VycyUyRmdpb3NoYXJhJTJGZGV2ZWxvcG1lbnQlMkZwcm9qZWN0cyUyRm5ldGNvcmUlMkZuZXh0JTJGc3JjJTJGYXBwJmFwcFBhdGhzPSUyRmFwaSUyRmNvbnRhY3QlMkZyb3V0ZSZwYWdlRXh0ZW5zaW9ucz10c3gmcGFnZUV4dGVuc2lvbnM9dHMmcGFnZUV4dGVuc2lvbnM9anN4JnBhZ2VFeHRlbnNpb25zPWpzJmJhc2VQYXRoPSZhc3NldFByZWZpeD0mbmV4dENvbmZpZ091dHB1dD0mcHJlZmVycmVkUmVnaW9uPSZtaWRkbGV3YXJlQ29uZmlnPWUzMCUzRCE%3D&nextConfigOutput=&preferredRegion=&middlewareConfig=e30%3D!
▲  
▲  ./node_modules/.pnpm/nodemailer@6.9.4/node_modules/nodemailer/lib/dkim/index.js:10:11
▲  Module not found: Can't resolve 'fs'
▲  
▲  https://nextjs.org/docs/messages/module-not-found
▲  
▲  Import trace for requested module:
▲  ./node_modules/.pnpm/nodemailer@6.9.4/node_modules/nodemailer/lib/mailer/index.js
▲  ./node_modules/.pnpm/nodemailer@6.9.4/node_modules/nodemailer/lib/nodemailer.js
▲  ./src/app/api/contact/route.ts
▲  ./node_modules/.pnpm/next@13.4.9_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/webpack/loaders/next-edge-app-route-loader/index.js?absolutePagePath=private-next-app-dir%2Fapi%2Fcontact%2Froute.ts&page=%2Fapi%2Fcontact%2Froute&appDirLoader=bmV4dC1hcHAtbG9hZGVyP25hbWU9YXBwJTJGYXBpJTJGY29udGFjdCUyRnJvdXRlJnBhZ2U9JTJGYXBpJTJGY29udGFjdCUyRnJvdXRlJnBhZ2VQYXRoPXByaXZhdGUtbmV4dC1hcHAtZGlyJTJGYXBpJTJGY29udGFjdCUyRnJvdXRlLnRzJmFwcERpcj0lMkZVc2VycyUyRmdpb3NoYXJhJTJGZGV2ZWxvcG1lbnQlMkZwcm9qZWN0cyUyRm5ldGNvcmUlMkZuZXh0JTJGc3JjJTJGYXBwJmFwcFBhdGhzPSUyRmFwaSUyRmNvbnRhY3QlMkZyb3V0ZSZwYWdlRXh0ZW5zaW9ucz10c3gmcGFnZUV4dGVuc2lvbnM9dHMmcGFnZUV4dGVuc2lvbnM9anN4JnBhZ2VFeHRlbnNpb25zPWpzJmJhc2VQYXRoPSZhc3NldFByZWZpeD0mbmV4dENvbmZpZ091dHB1dD0mcHJlZmVycmVkUmVnaW9uPSZtaWRkbGV3YXJlQ29uZmlnPWUzMCUzRCE%3D&nextConfigOutput=&preferredRegion=&middlewareConfig=e30%3D!
▲  
▲  ./node_modules/.pnpm/nodemailer@6.9.4/node_modules/nodemailer/lib/dkim/index.js:11:13
▲  Module not found: Can't resolve 'path'
▲  
▲  https://nextjs.org/docs/messages/module-not-found
▲  
▲  Import trace for requested module:
▲  ./node_modules/.pnpm/nodemailer@6.9.4/node_modules/nodemailer/lib/mailer/index.js
▲  ./node_modules/.pnpm/nodemailer@6.9.4/node_modules/nodemailer/lib/nodemailer.js
▲  ./src/app/api/contact/route.ts
▲  ./node_modules/.pnpm/next@13.4.9_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/webpack/loaders/next-edge-app-route-loader/index.js?absolutePagePath=private-next-app-dir%2Fapi%2Fcontact%2Froute.ts&page=%2Fapi%2Fcontact%2Froute&appDirLoader=bmV4dC1hcHAtbG9hZGVyP25hbWU9YXBwJTJGYXBpJTJGY29udGFjdCUyRnJvdXRlJnBhZ2U9JTJGYXBpJTJGY29udGFjdCUyRnJvdXRlJnBhZ2VQYXRoPXByaXZhdGUtbmV4dC1hcHAtZGlyJTJGYXBpJTJGY29udGFjdCUyRnJvdXRlLnRzJmFwcERpcj0lMkZVc2VycyUyRmdpb3NoYXJhJTJGZGV2ZWxvcG1lbnQlMkZwcm9qZWN0cyUyRm5ldGNvcmUlMkZuZXh0JTJGc3JjJTJGYXBwJmFwcFBhdGhzPSUyRmFwaSUyRmNvbnRhY3QlMkZyb3V0ZSZwYWdlRXh0ZW5zaW9ucz10c3gmcGFnZUV4dGVuc2lvbnM9dHMmcGFnZUV4dGVuc2lvbnM9anN4JnBhZ2VFeHRlbnNpb25zPWpzJmJhc2VQYXRoPSZhc3NldFByZWZpeD0mbmV4dENvbmZpZ091dHB1dD0mcHJlZmVycmVkUmVnaW9uPSZtaWRkbGV3YXJlQ29uZmlnPWUzMCUzRCE%3D&nextConfigOutput=&preferredRegion=&middlewareConfig=e30%3D!
▲  
▲  ./node_modules/.pnpm/nodemailer@6.9.4/node_modules/nodemailer/lib/dkim/index.js:12:15
▲  Module not found: Can't resolve 'crypto'
▲  
▲  https://nextjs.org/docs/messages/module-not-found
▲  
▲  Import trace for requested module:
▲  ./node_modules/.pnpm/nodemailer@6.9.4/node_modules/nodemailer/lib/mailer/index.js
▲  ./node_modules/.pnpm/nodemailer@6.9.4/node_modules/nodemailer/lib/nodemailer.js
▲  ./src/app/api/contact/route.ts
▲  ./node_modules/.pnpm/next@13.4.9_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/webpack/loaders/next-edge-app-route-loader/index.js?absolutePagePath=private-next-app-dir%2Fapi%2Fcontact%2Froute.ts&page=%2Fapi%2Fcontact%2Froute&appDirLoader=bmV4dC1hcHAtbG9hZGVyP25hbWU9YXBwJTJGYXBpJTJGY29udGFjdCUyRnJvdXRlJnBhZ2U9JTJGYXBpJTJGY29udGFjdCUyRnJvdXRlJnBhZ2VQYXRoPXByaXZhdGUtbmV4dC1hcHAtZGlyJTJGYXBpJTJGY29udGFjdCUyRnJvdXRlLnRzJmFwcERpcj0lMkZVc2VycyUyRmdpb3NoYXJhJTJGZGV2ZWxvcG1lbnQlMkZwcm9qZWN0cyUyRm5ldGNvcmUlMkZuZXh0JTJGc3JjJTJGYXBwJmFwcFBhdGhzPSUyRmFwaSUyRmNvbnRhY3QlMkZyb3V0ZSZwYWdlRXh0ZW5zaW9ucz10c3gmcGFnZUV4dGVuc2lvbnM9dHMmcGFnZUV4dGVuc2lvbnM9anN4JnBhZ2VFeHRlbnNpb25zPWpzJmJhc2VQYXRoPSZhc3NldFByZWZpeD0mbmV4dENvbmZpZ091dHB1dD0mcHJlZmVycmVkUmVnaW9uPSZtaWRkbGV3YXJlQ29uZmlnPWUzMCUzRCE%3D&nextConfigOutput=&preferredRegion=&middlewareConfig=e30%3D!
▲  > Build failed because of webpack errors
▲  ELIFECYCLE  Command failed with exit code 1.
▲  Error: Command "pnpm run build" exited with 1
▲  ERROR  Command failed with exit code 1: vercel build
▲  
▲  pnpm: Command failed with exit code 1: vercel build
▲     at makeError (/Users/gioshara/Library/pnpm/global/5/.pnpm/pnpm@8.6.1/node_modules/pnpm/dist/pnpm.cjs:24241:17)
▲     at handlePromise (/Users/gioshara/Library/pnpm/global/5/.pnpm/pnpm@8.6.1/node_modules/pnpm/dist/pnpm.cjs:24812:33)
▲     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
▲     at async Object.handler [as dlx] (/Users/gioshara/Library/pnpm/global/5/.pnpm/pnpm@8.6.1/node_modules/pnpm/dist/pnpm.cjs:206955:7)
▲     at async /Users/gioshara/Library/pnpm/global/5/.pnpm/pnpm@8.6.1/node_modules/pnpm/dist/pnpm.cjs:216361:21
▲     at async main (/Users/gioshara/Library/pnpm/global/5/.pnpm/pnpm@8.6.1/node_modules/pnpm/dist/pnpm.cjs:216328:34)
▲     at async runPnpm (/Users/gioshara/Library/pnpm/global/5/.pnpm/pnpm@8.6.1/node_modules/pnpm/dist/pnpm.cjs:216583:5)
▲     at async /Users/gioshara/Library/pnpm/global/5/.pnpm/pnpm@8.6.1/node_modules/pnpm/dist/pnpm.cjs:216575:7

⚡️ The Vercel build (`pnpm dlx vercel build`) command failed. For more details see the Vercel logs above.
⚡️ If you need help solving the issue, refer to the Vercel or Next.js documentation or their repositories.

 ERROR  Command failed with exit code 1: next-on-pages

pnpm: Command failed with exit code 1: next-on-pages
    at makeError (/Users/gioshara/Library/pnpm/global/5/.pnpm/pnpm@8.6.1/node_modules/pnpm/dist/pnpm.cjs:24241:17)
    at handlePromise (/Users/gioshara/Library/pnpm/global/5/.pnpm/pnpm@8.6.1/node_modules/pnpm/dist/pnpm.cjs:24812:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler [as dlx] (/Users/gioshara/Library/pnpm/global/5/.pnpm/pnpm@8.6.1/node_modules/pnpm/dist/pnpm.cjs:206955:7)
    at async /Users/gioshara/Library/pnpm/global/5/.pnpm/pnpm@8.6.1/node_modules/pnpm/dist/pnpm.cjs:216361:21
    at async main (/Users/gioshara/Library/pnpm/global/5/.pnpm/pnpm@8.6.1/node_modules/pnpm/dist/pnpm.cjs:216328:34)
    at async runPnpm (/Users/gioshara/Library/pnpm/global/5/.pnpm/pnpm@8.6.1/node_modules/pnpm/dist/pnpm.cjs:216583:5)
    at async /Users/gioshara/Library/pnpm/global/5/.pnpm/pnpm@8.6.1/node_modules/pnpm/dist/pnpm.cjs:216575:7
```

The issue comes from the `nodemailer` package as you can see from the error output.

In my nextjs route I am using the following runtime:

```typescript
export const runtime = 'edge'

import nodemailer from 'nodemailer'
import { NextResponse } from 'next/server'
export async function POST(req: Request) {
   // sending the email with nodemailer here...
    return NextResponse.json({ success: true })
}
```

Thanks for your time.

**Comment by dario-piotrowicz** [comment]
Hi @gio-shara-code, thanks for the comment, I can see that you also have the `Module not found: Can't resolve 'crypto'`

However that's probably not be biggest issue in your case, as it looks like `nodemailer` is relying on node apis which aren't supported in the edge runtime (such as `fs` and `path` which are fundamentally incompatible with the Cloudflare workers runtime, where you do not have access to a file system)

So in your case I'd say that your application unfortunately can't be deployed on Cloudflare Pages unless you remove the `nodemailer` dependency 😓

**Comment by gio-shara-code** [comment]
@dario-piotrowicz Appreciate your quick response. I will consider using a proper Email provider or run a small backend for nodemailer 🙏 Have a good one!

**Comment by dario-piotrowicz** [comment]
@fineshop are you still experiencing the issue?

(you comment here makes me think that you're ok now? https://github.com/vercel/next.js/issues/50444#issuecomment-1646445937)

**Comment by fineshop** [comment]
> @fineshop are you still experiencing the issue?
> 
> (you comment here makes me think that you're ok now? [vercel/next.js#50444 (comment)](https://github.com/vercel/next.js/issues/50444#issuecomment-1646445937))

No, it's not yet resolved even through the project is fresh without any other dependencies. Whenever I use the API routing with edge runtime, the error occurs.

**Comment by fineshop** [comment]
> @fineshop do you use `next-auth`? if so maybe you could try using their experimental version 5 as mentioned here? https://github.com/vercel/next.js/issues/50444#issuecomment-1670452856
> 
> I can see in your logs that you're using a `.babelrc` file? could you share its content?  maybe that could be causing the issue?
> 
> Besides that I am not really sure... this is an issue in Next itself (since you can see in the logs that `next build` is the one that's failing) so (since it's all on Next's side and doesn't involve integrating with the vercel cli nor next-on-pages) I feel that it's extremely unlikely that fresh applications can be broken simply by using API routes 🤔 (I could not reproduce that either)
> 
> could you share a minimal reproduction?

Here is content of `.babelrc`:

```
{ 
   "presets": [ 
     "@babel/preset-env", 
     "@babel/preset-typescript", 
     [ 
       "@babel/preset-react", 
       { 
         "runtime": "automatic" 
       } 
     ], 
     "next/babel" 
   ], 
   "plugins": [ 
     [ 
       "module-resolver", 
       { 
         "root": ["./"], 
         "alias": { 
           "@": "./src" 
         } 
       } 
     ] 
   ] 
 }
```

**Comment by lucasjinreal** [comment]
@dario-piotrowicz  Hello, unfortunatelly, on my side, the error comes with next-auth actually.

./node_modules/.pnpm/next-auth@4.22.1_next@13.4.12_nodemailer@6.9.4_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/lib/email/signin.js:8:14
Module not found: Can't resolve 'crypto'

but next-auto called node mailer

In such case, next-auth is so fundamental, how can I do with it>
