### ISSUE TITLE
[🐛 Bug]: With Edge Runtime, missing a resource when deployed to Cloudflare Pages or running preview locally

### ISSUE THREAD

**Issue by thealiilman** [cloudflare/next-on-pages#396]
### next-on-pages environment related information

```zsh
System:
	Platform: darwin
	Arch: arm64
	Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000
	CPU: (8) arm64 Apple M1 Pro
	Memory: 16 GB
	Shell: /bin/zsh
Binaries:
	Node: 18.16.0
	Yarn: 1.22.19
	npm: 9.5.1
	pnpm: N/A
Package Manager Used: yarn (classic)
Relevant Packages:
	@cloudflare/next-on-pages: 1.3.0
	vercel: N/A
	next: N/A
```

### Description

We are experimenting with Edge Runtime for our blog and we noticed the following 404 responses when we have the necessary Edge Runtime changes deployed and when we run a preview (`wrangler pages dev`).

```
Failed to load resource: the server responded with a status of 404 () https://748d706d.reproducible-missing-file.pages.dev/blog/_next/static/chunks/pages/%5Blanguage%5D-95ff3c047aad677e.js

Refused to execute script from https://748d706d.reproducible-missing-file.pages.dev/blog/_next/static/chunks/pages/%5Blanguage%5D-95ff3c047aad677e.js because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
```

The 404 responses above comes from the repo for reproducing this error. It is the similar 404 responses we are encountering in our blog.

Our blog uses components from internal AirAsia packages, and none of the JS and CSS from these packages are being loaded. I'm thinking the file that has the necessary JS and CSS aren't being loaded. They do exist when running locally via `yarn dev` and `yarn start`.

I can confirm that the **decoded** version of URL above, https://748d706d.reproducible-missing-file.pages.dev/blog/_next/static/chunks/pages/[language]-95ff3c047aad677e.js, does exist. For whatever reason, the **encoded** version does not exist.

I can confirm that the **encoded** version does exist when running locally via `yarn dev` and `yarn start`.

### Reproduction

Instructions are in the README.md file.

https://github.com/thealiilman/reproducible-missing-file

### Pages Deployment Method

Direct Upload (`wrangler pages publish` or the @cloudflare/pages-action GitHub Action)

### Additional Information

Here's a preview deployment of no errors logged into DevTools console:
https://6ff41122.reproducible-missing-file.pages.dev/whatever/

Here's a preview deployment of errors logged into DevTools console:
https://748d706d.reproducible-missing-file.pages.dev/blog/whatever/

### Would you like to help?

- [ ] Would you like to help fixing this bug?

**Comment by james-elicx** [comment]
Hey there,

Thank you for providing a reproduction. I believe it is due to using `basePath`/`assetPrefix`, causing the `/_next/static` assets to be put inside a sub-directory, which we didn't account for when excluding the directory from invoking the worker.

I have opened a PR that should resolve this issue for you. I would welcome you to try out the prerelease in https://github.com/cloudflare/next-on-pages/pull/397#issuecomment-1647768695 🙂.

**Comment by thealiilman** [comment]
I can confirm that your fix works. Fantastic!

Cheers @james-elicx

![](https://media.giphy.com/media/QsyPRpG6WVR6SYfBVw/giphy.gif)
