### ISSUE TITLE
Next.js is not working in the cloudflare pages

### ISSUE THREAD

**Issue by SudheendraSoftionik** [cloudflare/next-on-pages#416]
### Description

Trying to deploy Next.js 13 but it is not working in the Cloudflare pages. 

![image](https://github.com/cloudflare/next-on-pages/assets/54434002/433a7e11-ee2c-4384-a20d-69ee79e544de)

### Pages Deployment Method

None

### Would you like to help?

- [ ] Would you like to help fixing this bug?

**Comment by james-elicx** [comment]
Hey there, it sounds like you might be using an older version of Node.js.

Please can you try setting an environment variable for `NODE_VERSION` to 16 or greater, per the [readme](https://github.com/cloudflare/next-on-pages/tree/main/packages/next-on-pages#3-deploy-your-application-to-cloudflare-pages)?

Additionally, I can see in your build command that you're doing a static export with `next export`. This repo is for `@cloudflare/next-on-pages`, which is SSR support for Next.js - different to doing a static export.

**Comment by SudheendraSoftionik** [comment]
After setting NODE_VERSION getting below error

<img width="1212" alt="Screenshot 2023-08-01 at 8 22 30 PM" src="https://github.com/cloudflare/next-on-pages/assets/54434002/824002c7-18eb-4bee-8d03-53ad3981155e">

**Comment by james-elicx** [comment]
> After setting NODE_VERSION getting below error
> 
> <img alt="Screenshot 2023-08-01 at 8 22 30 PM" width="1212" src="https://user-images.githubusercontent.com/54434002/257553245-824002c7-18eb-4bee-8d03-53ad3981155e.png">

Per the [readme](https://github.com/cloudflare/next-on-pages/tree/main/packages/next-on-pages#3-deploy-your-application-to-cloudflare-pages), please add the `nodejs_compat` compatibility flag in your Pages project settings.

Go to your Pages project in the Cloudflare dashboard > Settings > Functions > Compatibility Flags, and add the `nodejs_compat` flag for both production and preview.

**Comment by dario-piotrowicz** [comment]
Thanks a lot @james-elicx for clearing things up

I'm closing the issue as it seems to be just a user error, hopefully it could all be cleared out now 🙂 

@SudheendraSoftionik I hope everything's ok now, if you still have issues with deploying your application feel free to reopen the issue and/or let us know
