### ISSUE TITLE
Page route mismatch next js 12 

### ISSUE THREAD

**Issue by diptnc** [cloudflare/next-on-pages#424]
Hi there,
I recently uploaded my next js site using Pages->NextJSPreset.
After successful deployment , when i navigate to home url [https://next-diptanuchakraborty-in.pages.dev/]( https://next-diptanuchakraborty-in.pages.dev/), it redirects me to some other page of my website which is [https://next-diptanuchakraborty-in.pages.dev/sitemap.html](https://next-diptanuchakraborty-in.pages.dev/sitemap.html) instead of my homepage . I am not able to understand why this is happening.

When i navigate to [https://next-diptanuchakraborty-in.pages.dev/index](https://next-diptanuchakraborty-in.pages.dev/index) , then i can access the default home page

My pages directory
![pages expanded](https://github.com/cloudflare/next-on-pages/assets/35225642/c6f9ad16-5ee7-42b7-8e87-05b41d20619f)
![index jsx - next-diptnc - Visual Studio Code 10-08-2023 11_02_37 PM](https://github.com/cloudflare/next-on-pages/assets/35225642/b93d8ea9-3e65-43df-a611-e4cf8e9efa5c)

**Comment by diptnc** [comment]
Hello, when deploying as a static site preset in **cloudflare pages**, I don't get any issues.  I wanted to switch to `'@cloudflare/next-on-pages'` because I have a page that pulls some api info from the url slug. It wasn't working with static site generation, but `@cloudflare/next-on-pages `makes it work.  

for eg. [https://next-diptanuchakraborty-in.pages.dev/current-affairs/india-inducts-new-heron-mark-2-drones](https://next-diptanuchakraborty-in.pages.dev/current-affairs/india-inducts-new-heron-mark-2-drones) . it fetches the data with url slug. 

But when i deploy this as static site in cloudflare pages, it shows `404`.

Static build [static build](https://d9b2dab1.next-diptanuchakraborty-in.pages.dev/current-affairs/india-inducts-new-heron-mark-2-drones)

**Comment by dario-piotrowicz** [comment]
I see.... so it does look like this isn't an issue with your pages project but something must be off in `@cloudflare/next-on-pages` 😕 

Could you by any chance build the application locally and share these two files?
 - .vercel/output/static/_worker.js/nop-build-log.json
 - .vercel/output/config.json

**Comment by dario-piotrowicz** [comment]
@diptnc I appreciate that yours is a personal project that you likely can't share, but I was thinking.... could you take your project, remove all the pages inside `pages` (potentially adding there a placeholder one), redux, etc... check if the issue still persists and in that case share the code as a minimal reproduction here?

I'm asking because they are you present it, it does sound like it's not an issue relative to any specific page

and having a minimal reproduction is extremely invaluable in order to solve such issues (especially since I couldn't manage to reproduce it on my end)

**Comment by diptnc** [comment]
i tried to upgrade the project from next 12  to next 13 and it solved the issue.
