### ISSUE TITLE
[🐛 Bug]: Suddenly all my next.js 13 sites became very slow

### ISSUE THREAD

**Issue by geekyayush** [cloudflare/next-on-pages#427]
### next-on-pages environment related information

It's probably the latest version or what cloudflare install on build time. Because I don't have it defined in my codebase.

### Description

I have been using nextjs 13.4.8 version (with pages router) for one project and 13.4.13 (with app router) for my another project.
Both project are hosted on cloudflare.
But now suddenly I see degraded performance in both of the projects.
Usually when I open the page (the domain where both of the projects are hosted), they would open in less than 500ms (looking at the network tab).
But now, they are taking almost 5 seconds. and It all happened suddenly. I did not push any new update to the code or changed any settings.
I did upgrade my workers account to paid one. That's all I did.

The weird thing is that, I just tried to host one of the projects on vercel, and the speed is as expected on vercel.com i.e. less than 200ms in network tab.
But the same code is taking 5 seconds to load the page on cloudflare pages.

Did cloudflare push any update behind the scene which caused this issue?
Anyone else facing this issue?

I really really need help in this please. My project is just about to go production.
If things don't work out with Cloudflare pages, sadly I will have to move everything to verel (which I personally won't prefer) but I guess I will have no choice. :(

### Reproduction

I don't have any reproduction repo but I found one guy who hosted a sample project and I see his site. Even his site is taking 3-4 seconds to load in network tab.

https://87ac4020.next-on-pages-test-5h3.pages.dev/

Link to his comment: https://github.com/cloudflare/next-on-pages/issues/218#issuecomment-1545455038

### Pages Deployment Method

Pages CI (GitHub/GitLab integration)

### Would you like to help?

- [ ] Would you like to help fixing this bug?

**Comment by geekyayush** [comment]
Some more details:

Here you can see these small js files are taking seconds to download. One of them is just half KB js but took 2.11 seonds.
![image](https://github.com/cloudflare/next-on-pages/assets/25874080/62faf6fc-924a-4892-b9f4-a03a266e93cb)

NOTE: In case you might ask about my internet speed. I have a 150Mbps connection, other sites are opening fast. So internet connectivity is not an issue here for sure.

**Comment by james-elicx** [comment]
Hey there, I don't seem to be experiencing this with the URL you linked. I wonder if perhaps there was some added latency in KV responses at that point in time.

Can you try visiting your site again and see if the problem is still occurring?

![image](https://github.com/cloudflare/next-on-pages/assets/10815538/90c84141-99a1-4cf2-83ba-c84067683c7d)

**Comment by geekyayush** [comment]
> Hey there, I don't seem to be experiencing this with the URL you linked. I wonder if perhaps there was some added latency in KV responses at that point in time.

Yes, I just checked that link and it does not have that latency issue. But I am still facing the issue.

> Can you try visiting your site again and see if the problem is still occurring?

I did but still the same issue.
Here's the develop URL for the same: https://develop.gravityblogs-web-app.pages.dev/
Try visiting this in incognito so it does not use the local cache.


> I would also note that these assets in this screenshot are excluded from routing due to being in `/_next/static`, so that would be absolutely nothing to do with next-on-pages.

I agreed. but it's really weird that static files are taking 3-4 seconds to load.

![image](https://github.com/cloudflare/next-on-pages/assets/25874080/3c9c58b7-37e7-4afb-bdcd-43c1bd825546)

**Comment by geekyayush** [comment]
Also, this happened to my other project which wasn't even touched for a week and now suddenly facing this issue.

**Comment by geekyayush** [comment]
> are you still experiencing the issue?

Yes I am.


> by visiting your site in incognito it does look like things are much faster on my end

I see but it is still slow. Usually the requests take less than 500ms.
Not sure why it is in ms from you side. When I open it, all the requests are taking more than 3 seconds including static assets.
I hosted the same thing as it is on vercel here (https://gravityblogs-web-app.vercel.app/) and it takes way less time to open. Usually 200-300 ms.
No changes in code, it's the same exact replica hosted on vercel.


> Also just to make sure, is your issue only on cold start requests? (meaning on requests make after no request was made for a while) Or on all requests?

Yes on cold requests only. For instance, if I open a fresh incognito window and visit the site, it will take those 3-4 seconds in network tab. If I refresh right after it, it will take up to 400ms.
Now If I close the incognito and open a fresh incognito window, it will take 3-4 seconds.



> Because on consecutive requests things should be much much faster

Yes I agree. but consecutive requests are not an issue. The first time visits taking 3-4 seconds is an issue.

**Comment by geekyayush** [comment]
I am getting a feeling that cloudflare pages is not properly compatible with nextjs 13.

**Comment by dario-piotrowicz** [comment]
> Now If I close the incognito and open a fresh incognito window, it will take 3-4 seconds.

Do you mean immediately? If you open the incognito window, open the devtools, disable caching (as you can see in my screenshots) and refresh the page, does it take 3-4 seconds every time?

(I'm asking because what you said makes it sound like browser caching which is not what I was referring to)

> Yes I agree. but consecutive requests are not an issue. The first time visits taking 3-4 seconds is an issue.

yes I wasn't saying that that's the solution, just trying to narrow down where the slow requests come from to see if we can understand better the issue

> I am getting a feeling that cloudflare pages is not properly compatible with nextjs 13.

But as @james-elicx mentioned this has nothing to do with nextjs since the static assets are handled by Pages...  🤔 

Have you tried re-deploying? or maybe deploying something different and see if that has the same issue? or even re-deploying your application but under a different pages project?

**Comment by geekyayush** [comment]
> Do you mean immediately? If you open the incognito window, open the devtools, disable caching (as you can see in my screenshots) and refresh the page, does it take 3-4 seconds every time?

Yes exactly like that but I haven't checked the "Disable cache" option. It takes 3-4 seconds to load in network tab. and after I close incognito, the incognito cache will be vanished. So now if I open incognito window again, and visit the URL. It will take 3-4 seconds.



> (I'm asking because what you said makes it sound like browser caching which is not what I was referring to)

Ohh, sorry. Maybe I said it in a different way.

> yes I wasn't saying that that's the solution, just trying to narrow down where the slow requests come from to see if we can understand better the issue

haha yes got it. Even I didn't think of that as a solution.



> But as @james-elicx mentioned this has nothing to do with nextjs since the static assets are handled by Pages

Ahh, my bad. Understood.



> Have you tried re-deploying? or maybe deploying something different and see if that has the same issue? or even re-deploying your application but under a different pages project

Yes did it. Same thing is happening. I tried it on another project and got same results. One thing I noticed is, I had this one project in next 12.x version and it had speed of 500-600ms. Then I upgraded it to 13.48 something version and then the site speed got slowed.

**Comment by geekyayush** [comment]
i have tried redeploying like a dozen times after that. but same thing. and even the older git commit hash URL which were opening fast, are now opening slow.
but same thing on vercel opens very fast.

It's really being a bottleneck for me.
At the moment, I am forced to move to vercel. : (
But I would really appreciate it if I can get a similar speed or the speed I used to get on Cloudflare pages so I can move back to cloudflare pages. : )

If you need any kind of project info like id or something so you can check from your side (since you are a Member of Cloudflare).
or need package json file, I am happy to tell.

**Comment by geekyayush** [comment]
I did a speed comparison using gtmetrix and here are the results.
Link: https://gtmetrix.com/compare/ZRLQ8APt/Fic8uYrI

![image](https://github.com/cloudflare/next-on-pages/assets/25874080/9337e026-0f60-4f0f-a9b5-bbae6b2f8501)
(left is cloudflare pages, right side is vercel)

This is done on Mumbai, India server since I am from India.
I hope this clears the speed issue I am facing.

One thing I noticed is, if I do the same test on GTmetrix US server, then cloudflare pages take only around1 second extra than vercel compared to doing the same on Mumbai, India server which takes 5-6 seconds to load the cloudflare pages hosted site.

**Comment by geekyayush** [comment]
Maybe, just maybe, this issue exists on Cloudflare Indian server? whatever the issue is

**Comment by geekyayush** [comment]
Hey @dario-piotrowicz , anything on this?
I'd appreciate your help.
Thanks.

**Comment by dario-piotrowicz** [comment]
Hey @geekyayush, sorry for the late reply, I've been discussing about this with the team and we suspect this is a localised network issue and not due to Pages/Next.js.

I'm working to escalate it with the appropriate team so they can give you support.

In the meantime a colleague of mine has enabled tracing for your site, could you please try to go there again so that if you still have issues we can see if we find anything useful in the logs?

Also could you share what content you get from https://develop.gravityblogs-web-app.pages.dev/cdn-cgi/trace?
(you can redact your IP address there)

**Comment by geekyayush** [comment]
> I'm working to escalate it with the appropriate team so they can give you support.

Oh amazing. Thank you.



> could you please try to go there again so that if you still have issues we can see if we find anything useful in the logs

Sure thing. I will visit the site a couple of times.



> Also could you share what content you get from https://develop.gravityblogs-web-app.pages.dev/cdn-cgi/trace?

Here's the output:
```
fl=578f41
h=develop.gravityblogs-web-app.pages.dev
ip=<MY IP>
ts=1692283438.675
visit_scheme=https
uag=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.200
colo=BOM
sliver=none
http=http/2
loc=IN
tls=TLSv1.3
sni=plaintext
warp=off
gateway=off
rbi=off
kex=X25519
```

**Comment by dario-piotrowicz** [comment]
Thank you so very much @geekyayush we've checked and it your requests look particularly slow, there have been some issues with Pages in the last few days that might cause pages to be served slightly slower but likely never as slow as you're getting...

My colleague also saw that your application is getting hits outside of India and that those are being served fast, so although you are getting very slow loading times your users are likely not having the same issue (although I understand that that is not a great consolation)

We definitely need to look into things and understand why things are so slow for you, as I said I'm working on escalating this and making sure that it's handled by the proper team, I'll let you know when I have more news, sorry for the inconvenience 😓  (and that I can't help you more right now)

**Comment by geekyayush** [comment]
> there have been some issues with Pages in the last few days that might cause pages

Oh I see. That could be the issue.



> sorry for the inconvenience 😓 (and that I can't help you more right now)

That's not a problem at all. I am just glad that the issue has been noticed and awesome people are working towards fixing it. ^_^



> we've escalated the issue and it should get be handled by the appropriate team

That's great news. Thank you very much 🙏


> You should also have received an email from the support team

I will check that right away.

Thank you very much @dario-piotrowicz .
Can't wait to move my projects back to Cloudflare pages. 😄

**Comment by Shivam010** [comment]
Hi, joining the thread cause I have been experiencing the same issue.

I have a site hosted on Vercel with DNS on Cloudflare (and reverse proxy on). And another one completely using next-on-pages - on Cloudflare. The simple few kB assets are taking more than a second, _which should be finished in few milliseconds_

<img width="497" alt="image" src="https://github.com/cloudflare/next-on-pages/assets/29069530/6d22edc9-edd5-4a24-8a17-8b786991d652">

**Comment by geekyayush** [comment]
> I have been experiencing the same issue

Hey man,

I just got a reply from Cloudflare support. They are working towards fixing the issue.
Meanwhile, they asked me to redeploy and check if the issue still persists.

I did a redeploy of the same thing (no code changes) and seems like the speed has been improved.

I'd suggest you do the same and check.

**Comment by Shivam010** [comment]
Thanks! 
I will try with the one that's hosted on Cloudflare! 
Any word for the dns reverse proxy for websites hosted somewhere else?

**Comment by Shivam010** [comment]
Nope! Didn't work in either of the cases for me! 🥲
Neither for the one hosted on Cloudflare nor the one using Cloudflare DNS proxy with Vercel.

**Comment by Shivam010** [comment]
Is there anything that neeed to be changed in the configuration? 

_/cc @dario-piotrowicz_

**Comment by geekyayush** [comment]
> Any word for the dns reverse proxy for websites hosted somewhere else

Not sure if they are looking into that.
Maybe @dario-piotrowicz can answer

**Comment by geekyayush** [comment]
> Nope! Didn't work in either of the cases for me

Oh that's sad. 

At the moment, we can't do anything but wait.

> Is there anything that neeed to be changed in the configuration?

I haven't changed anything in config. Just redeployed the same code.

**Comment by AlizerUncaged** [comment]
any fixes for this? my site is having the same problem

**Comment by pandas9** [comment]
cloudflare in general is extremely slow, feel like only 2 good products are DNS and caching

pages and workers extreme latency, R2 upload is like back in 1999, D1 limits are not production ready, heard from other browser rendering is poorly built as well

afraid to test other products, having better speed from $20 VPS that is across the globe
