### ISSUE TITLE
[🐛 Bug]: Dynamic routes and images don't work

### ISSUE THREAD

**Issue by emrecoban** [cloudflare/next-on-pages#428]
### next-on-pages environment related information

```bash
System:
        Platform: linux
        Arch: x64
        Version: #26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Jul 13 16:27:29 UTC 2
        CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
        Memory: 15 GB
        Shell: /bin/bash
Binaries:
        Node: 18.16.0
        Bun: N/A
        pnpm: 8.6.12
        Yarn: 1.22.19
        npm: 9.5.1
Package Manager Used: pnpm
Relevant Packages:
        @cloudflare/next-on-pages: 1.5.0
        vercel: 30.0.0
        next: 13.4.13
```

### Description

[Dynamic routes](https://nextjs.org/docs/app/building-your-application/routing/dynamic-routes#convention) and images don't work. I've tried to deploy the same app on Vercel, and then it worked properly, but didn't work on Cloudflare.

I've tried the beta version, still the same result:
```bash
20:50:53.247 | Executing user command: npx @cloudflare/next-on-pages@0.0.0-705a95b
20:50:59.584 | ⚡️ @cloudflare/next-on-pages CLI v.0.0.0-705a95b (beta/canary release)
20:50:59.587 | ⚡️ Detected Package Manager: pnpm
```
#### Update
I found the error in the build logs:
```bash
20:52:08.023 | ⚡️ Watch mode unexpected error: SyntaxError: Unexpected token (270:4)
```

What should I do to fix it?

### Reproduction

Related to: https://github.com/cloudflare/next-on-pages/issues/32#issue-1465045099 https://github.com/cloudflare/next-on-pages/issues/344

**Comment by emrecoban** [comment]
### Solution

I solved the problem by upgrading the `vercel` package from 30.0.0 to 31.2.3. I should also mention that the solution to the `not-found` error https://github.com/cloudflare/next-on-pages/issues/413 is to add the `vercel` package to your project, not to update `@cloudflare/next-on-pages` (my own experience).

Also `pnpm` showed a warn in the terminal. I ignored this one and it's working properly now:
```bash
 WARN  Issues with peer dependencies found
.
└─┬ @cloudflare/next-on-pages 0.0.0-705a95b (beta)
  └── ✕ unmet peer vercel@^30.0.0: found 31.2.3
```

**Comment by emrecoban** [comment]
@dario-piotrowicz and I thank you for your contribution and effort. Although Next.js applications seem to run smoothly on Vercel, I think Next.js is a framework that has not yet been completed. Unfortunately, it is difficult for Cloudflare (maybe you :)) or other environments to keep up with it.

Yes, I guessed why the warning came out.

**Comment by dario-piotrowicz** [comment]
> not to update
ah I misread your comment 👀 , so you need to use an older version of next on pages??? 😕 

Regarding your comment, yes it's difficult to keep up 😅 😓 

But the main reason isn't really because the framework is evolving but because vercel can generate things that either don't follow precisely their specs or also generate serverless functions (that are not edge compatible) when it shouldn't

Basically the fact is that Vercel is the creator of Next.js so, although it is an open source project they can make it more compatible/convenient for their network, and since the Vercel and Cloudflare networks are pretty different this adds a lot of complexity/problems 😓

**Comment by emrecoban** [comment]
@dario-piotrowicz  I totally agree with you. Sometimes I question myself whether to use Next.js or not. By the way, I use the latest version of next-on-pages now. There doesn't seem to be an issue.
