### ISSUE TITLE
[🐛 Bug]: Wildcard rewritten routes to external destinations exclude original query parameters

### ISSUE THREAD

**Issue by YoungerMax** [cloudflare/next-on-pages#429]
### next-on-pages environment related information

```
System:
        Platform: linux
        Arch: x64
        Version: #1 SMP PREEMPT_DYNAMIC Tue, 08 Aug 2023 22:14:05 +0000 (6.4.9-arch1-1)
        CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
        Memory: 31 GB
        Shell: /bin/bash
Binaries:
        Node: 20.5.0
        Bun: 0.5.5
        pnpm: N/A
        Yarn: N/A
        npm: 9.8.1
Package Manager Used: npm
Relevant Packages:
        @cloudflare/next-on-pages: 1.5.0
        vercel: N/A
        next: 13.4.13
```

### Description

When using Next.js wildcard rewrites to an external `destination` on Pages, query parameters are not forwarded to the external `destination` when requests are made to the `source`.

## Example

Consider the Rewrite object:
```js
{
     source: "/api/:path*",
     destination: "http://example.com/:path*"
}
```

A request to `/api/example?example=example` would make a request to `http://example.com/example` currently, but it is supposed to be `http://example.com/example?example=example`.

### 1. `next.config.js`
```js
const API = 'http://example.com';

/** @type {import('next').NextConfig} */
const nextConfig = {
    generateEtags: false,
    rewrites: async () => {
        return [
            {
                source: '/api/:path*',
                destination: `${API}/:path*`
            }
        ]
    }
}

module.exports = nextConfig;
```

### 3. Make request
Make a request to any `/api` endpoint with query parameters. The observed behavior is that the request will be sent to Next.js on Cloudflare, then Next.js will forward the request to the `destination` without the query parameters passed in the initial request to Next.js.

## Example
- Consider a Next.js application with rewrites configured as above.
- Deploy to Cloudflare Pages with Pages CI - hosted on `https://example.pages.dev`, for example
- Request to `POST https://example.pages.dev/api/example/example?query=param&example=12345`
- Next.js on Pages will make a request to `POST http://example.com/example/example` [**query parameters are excluded**]

### Expected behavior
- Request to `POST https://example.pages.dev/api/example/example?query=param&example=12345`
- Next.js on Pages will make a request to `POST http://example.com/example/example?query=param&example=12345` [**query parameters are _included_**]

### Pages Deployment Method

Pages CI (GitHub/GitLab integration)

### Additional Information

1. **This works locally**: both when running `npm run dev` and `npm run build && npm run start`
2. **Cloudflare deployment**:
     - Build system version: 2
     - Environment variables
          - `NODE_VERSION` = `20.3.1`
     - Compatibility version: `2023-08-04`
     - Compatibility flags: `nodejs_compat`

### Would you like to help?

- [ ] Would you like to help fixing this bug?

**Comment by james-elicx** [comment]
Hey there, sorry about this, and thank you for the detailed write-up. 🙂

I have opened a PR that should resolve this issue. I would welcome you to try out the prerelease in https://github.com/cloudflare/next-on-pages/pull/430#issuecomment-1676454525

**Comment by YoungerMax** [comment]
@james-elicx Thank you very much for the quick response and fix for this issue! :+1: 

This prerelease worked successfully without any flaws. Thanks again!
