### ISSUE TITLE
[🐛 Bug]: d1 bindings missing on process.env 

### ISSUE THREAD

**Issue by SKalt** [cloudflare/next-on-pages#435]
### next-on-pages environment related information

```

System:
	Platform: linux
	Arch: x64
	Version: #86~20.04.2-Ubuntu SMP Mon Jul 17 23:27:17 UTC 2023
	CPU: (8) x64 Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
	Memory: 31 GB
	Shell: /usr/bin/zsh
Binaries:
	Node: 18.12.1
	Bun: N/A
	pnpm: 8.2.0
	Yarn: 1.22.11
	npm: 8.19.2
Package Manager Used: pnpm
Relevant Packages:
	@cloudflare/next-on-pages: 1.5.1
	vercel: N/A
	next: 13.4.13
```

### Description

I'm unexpectedly unable to access my D1 database on `process.env.DB` despite having the binding `DB` configured in both my `./wrangler.toml` and on the cloudflare pages dashboard for both production and preview environments.   
![Screenshot from 2023-08-16 22-17-50](https://github.com/cloudflare/next-on-pages/assets/10438373/0e3f1000-f2e7-4780-a2b7-7a34efaf7e25)
![Screenshot from 2023-08-16 22-17-56](https://github.com/cloudflare/next-on-pages/assets/10438373/f04b4f85-ef09-4384-aa4b-a10f9dc38147)

### Reproduction

Repro repo: https://github.com/SKalt/aws_iam_actions.git in the subdirectory `./website`. The trick is, the problem only happens for D1, and it only happens remotely.
Basic reproduction steps:
```sh
# setup
repo=https://github.com/SKalt/aws_iam_actions.git
target_dir=$(mktemp -d --tmpdir d1_missing.XXX)
git clone $repo $target_dir
cd $target_dir/website
pnpm install
export PATH=${PWD}/node_modules/.bin/$PATH

# configure a d1 database binding for the site 
wrangler d1 create ${DB_NAME:-my_db}
db_uuid=$( wrangler d1 list --json | jq '.[0].uuid' | cat -)
db_name=$( wrangler d1 list --json | jq '.[0].name' | cat -)
echo "
[[d1_databases]]
binding = \"DB\" # i.e. available in your Worker on env.DB
database_name = $db_name
database_id = $db_uuid
" > wrangler.toml
cd $target_dir

# Deploy the site and tail the logs
{ cd .. && make site-deploy; }
# alternately, you could manually run
next-on-pages && wrangler pages deploy ./.vercel/output/static
wrangler pages deployment tail
```
When you navigate to your `project.pages.dev` site, you'll notice something like this in the logs:
```
 GET https://cd340879.your-project.pages.dev/api/v0/search?q= - Ok @ 8/16/2023, 10:15:16 PM
  (log) {
  runtime: 'edge',
  node_env: 'production',
  CF_PAGES_URL: 'https://cd340879.your-project.pages.dev',
  normal_env_vars: 'present',
  kv: "test value",
  db: 'db absent',
  DB: 'process.env.DB absent'
}
```
Unless there's something up with my pages configuration.  Note the D1 database is in ENAM, and the placement for both production and preview is `default`.

Note also that the binding-generation seems to be working correctly:
```sh
 head -20 .vercel/output/static/_worker.js/index.js | sed 's/^/# /g'
# 
# 		import('node:buffer').then(({ Buffer }) => {
# 			globalThis.Buffer = Buffer;
# 		})
# 		.catch(() => null);
# 
# 		const __ENV_ALS_PROMISE__ = import('node:async_hooks').then(({ AsyncLocalStorage }) => {
# 			globalThis.AsyncLocalStorage = AsyncLocalStorage;
# 
# 			const envAsyncLocalStorage = new AsyncLocalStorage();
# 
# 			globalThis.process = {
# 				env: new Proxy(
# 					{},
# 					{
# 						get: (_, property) => Reflect.get(envAsyncLocalStorage.getStore(), property),
# 						set: (_, property, value) => Reflect.set(envAsyncLocalStorage.getStore(), property, value),
# 				}),
# 			};
# 			return envAsyncLocalStorage;
```

### Pages Deployment Method

Direct Upload (`wrangler pages publish` or the @cloudflare/pages-action GitHub Action)

### Pages Deployment ID

cd340879-f746-4c2a-b2ea-acbaee69d4f5

### Additional Information

- There was a hot second where I turned on "smart" worker placement, but I've since turned it off and the problem has persisted.
- I have `nodejs_compat` set for the project

### Would you like to help?

- [ ] Would you like to help fixing this bug?

**Comment by dario-piotrowicz** [comment]
Hi @SKalt 👋 , thanks for the issue 🙂 

Could you let me know what version of wrangler are you using?
If it is 3.5.0 could you try with 3.4.0 instead?

[3.5.0 seems to have removed the D1 shim](https://github.com/cloudflare/workers-sdk/blob/main/packages/wrangler/CHANGELOG.md#350) I wonder if that could be the problem

Someone in the workers-sdk repo seems to be hitting the same: https://github.com/cloudflare/workers-sdk/issues/3756

**Comment by dario-piotrowicz** [comment]
PS: Peges projects do not read the `wrangler.toml` file so that isn't really relevant 🙂

**Comment by SKalt** [comment]
Downgrading `wrangler` from 3.5.1 to 3.4.0 solved the issue! Thanks!
