### ISSUE TITLE
[🐛 Bug]: Crypto: Vercel says Edge Runtime supports it  

### ISSUE THREAD

**Issue by balakedev** [cloudflare/next-on-pages#440]
### next-on-pages environment related information

System:
        Platform: win32
        Arch: x64
        Version: Windows 10 Home
        CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
        Memory: 32 GB
        Shell: C:\Program Files\Git\usr\bin\bash.exe
Binaries:
        Node: 16.19.1
        Bun: N/A
        pnpm: N/A
        Yarn: 1.22.19
        npm: 8.19.3
Package Manager Used: npm
Relevant Packages:
        @cloudflare/next-on-pages: 1.5.1
        vercel: N/A
        next: 13.4.19

### Description

<html>
<body>

23:39:06.937 | ▲  > next build
-- | --
...
23:39:07.516 | ▲  - info Loaded env from /opt/buildhome/repo/.env
23:39:07.674 | ▲  Attention: Next.js now collects completely anonymous telemetry regarding usage.
23:39:07.674 | ▲  This information is used to shape Next.js' roadmap and prioritize features.
23:39:07.674 | ▲  You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
23:39:07.675 | ▲  https://nextjs.org/telemetry
23:39:07.800 | ▲  - info Creating an optimized production build...
23:39:19.443 | ▲  Failed to compile.
23:39:19.444 | ▲
23:39:19.444 | ▲  ./node_modules/next-auth/core/init.js:10:14
23:39:19.444 | ▲  Module not found: Can't resolve 'crypto'
23:39:19.445 | ▲
23:39:19.445 | ▲  https://nextjs.org/docs/messages/module-not-found
23:39:19.445 | ▲
23:39:19.445 | ▲  Import trace for requested module:
23:39:19.445 | ▲  ./node_modules/next-auth/core/index.js
23:39:19.445 | ▲  ./node_modules/next-auth/next/index.js
23:39:19.445 | ▲  ./app/api/auth/[...nextauth]/route.ts
23:39:19.446 | ▲  ./node_modules/next/dist/build/webpack/loaders/next-edge-app-route-loader/index.js?
23:39:19.453 | ▲
.....

</body>
</html>

NextJS docs suggest this should be possible: https://nextjs.org/docs/app/api-reference/edge#crypto-apis

how do we get this to work?

### Reproduction

add next-auth to a clean nextjs 13 project 

### Pages Deployment Method

None

### Would you like to help?

- [ ] Would you like to help fixing this bug?

**Comment by james-elicx** [comment]
The documentation that you linked is referring to the Web Crypto API, whereas your code is trying to import from the Node.js `crypto` module.

I can see from the logs that you are using next-auth. It's a well-known problem that the current version of next-auth does not support the edge runtime properly. I believe this is something that they are aiming to introduce proper support for in v5 - https://github.com/nextauthjs/next-auth/pull/7443

**Comment by balakedev** [comment]
Hi @james-elicx , yeah i deep dived on this pretty hard after making this ticket. Seems that this issue is more a next-auth issue. Will close this ticket.
