### ISSUE TITLE
[🐛 Bug]: Cannot access to non-public env variables in .env.local from RSC

### ISSUE THREAD

**Issue by anonymouscatcher** [cloudflare/next-on-pages#441]
### Description

I have 3 .env files, 

.env.local
.env.production
.env.development

I have some sensitive variables defined in .env.local however after building my app they become undefined in RSC but on dev mode I have access to them, So I assume that it might be related to next-on-pages,

### Reproduction

add something like `RECAPTCHA_SECRET_KEY` to .env.local and build app using next-on-pages and run it and log it in a RSC. it's undefined.

### Pages Deployment Method

Pages CI (GitHub/GitLab integration)

### Would you like to help?

- [ ] Would you like to help fixing this bug?

**Comment by dario-piotrowicz** [comment]
Hi @anonymouscatcher 👋 , thanks for the issue 🙂

the Vercel CLI (that we use in the build process) doesn't seem to handle different env files very well, 
 as it always uses the production variant, as you can see here: https://github.com/cloudflare/next-on-pages/issues/161 

I think this is the same issue you're facing?

**Comment by anonymouscatcher** [comment]
Not sure if this is same, the values which are public are defined after building the app, only the secret variables are undefined

**Comment by dario-piotrowicz** [comment]
@anonymouscatcher could you share a minimal reproduction? 🙂

**Comment by dario-piotrowicz** [comment]
I'm closing this issue in favour of just keeping #604

(as I suspect the most sensible approach here is to improve our documentation rather than making assumptions and generate files for users when they might not want or expect that)
