### ISSUE TITLE
[⚡ Feature]: Is there any way that we can trigger the refetch in RSC?

### ISSUE THREAD

**Issue by anonymouscatcher** [cloudflare/next-on-pages#444]
### Description

I have an issue with certain scenarios while using RSC. Let's say we have a couple of different components that are RSC and they run on a server to fetch user information. However, if a user logs out after clicking log out button, we need to refresh those components. I'm aware that Vercel offers features like `revalidateTag` etc, but I couldn't find a similar feature in next-on-pages and it seems you don't support it yet. This limitation prevents us from using RSC, and as a result, we can't leverage the benefits of Next 13 and the app directory and the whole thing is useless...at least for us

### Would you like to help?

- [ ] Would you like to help implement this feature?

**Comment by dario-piotrowicz** [comment]
Hi @anonymouscatcher :slightly_smiling_face: 

We've actually introduced support for `revalidateTag` in [1.6.0](https://www.npmjs.com/package/@cloudflare/next-on-pages/v/1.6.0) (which we just released yesterday) :slightly_smiling_face: 

I hope that can help you?

Also note that currently our solution only works based on the [workers cache API](https://developers.cloudflare.com/workers/runtime-apis/cache/), which is only available on custom domains (not in `pages.dev`) if this is an issue for you and you need `revalidateTag` to work also on `pages.dev` we're planning on introducing alternatives that use other Cloudflare products (like KV) or allow you to use whatever you prefer as a caching storage, I believe @james-elicx is looking into that :slightly_smiling_face:

**Comment by anonymouscatcher** [comment]
Hi @dario-piotrowicz 
Oh great timing :) I didn’t know this
That’s great news, does it work same as vercel? Is any there any difference? I couldn’t find documents for in repo :) if its same I’ll look into next js documents

**Comment by anonymouscatcher** [comment]
I just tested this, but seems it's not helpful regardless of if Cloudflare support it or not, seems `revalidateTag ` doesn't trigger refetch, it works different than what I thought...

**Comment by anonymouscatcher** [comment]
I think I found the answer, If you use router.refresh it will refresh RSCs :) So going to close this one. thanks
