### ISSUE TITLE
[🐛 Bug]: Rewrites with `has` query option doesn't behave as expected

### ISSUE THREAD

**Issue by emma-cw** [cloudflare/next-on-pages#448]
### next-on-pages environment related information

<details>
  <summary>env info</summary>

```
  System:
	Platform: darwin
	Arch: arm64
	Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:17:35 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T8112
	CPU: (8) arm64 Apple M2
	Memory: 8 GB
	Shell: /opt/homebrew/bin/zsh
  Binaries:
	Node: 18.17.0
	Bun: N/A
	pnpm: N/A
	Yarn: 1.22.19
	npm: 9.6.7
  Package Manager Used: yarn (classic)
  Relevant Packages:
	@cloudflare/next-on-pages: 1.6.0
	vercel: 32.1.0
	next: 13.4.19
```
</details>

### Description

Hi there,

During deployment we've noticed an issue which only seems to affect our project once deployed via next-on-pages. The issue pertains to Next's 'rewrites' config option which doesn't _appear_ to be supported properly at the moment.

On the [supported doc](https://github.com/cloudflare/next-on-pages/blob/main/packages/next-on-pages/docs/supported.md) it does state that "routes `has`" is supported; at present however I think some of the behaviour is not supported. For example, the following "rewrites" config:

```
async rewrites() {
    return {
      beforeFiles: [{
          source: '/user-query',
          has: [{
              type: 'query',
              key: 'name',
              value: '(?<name>.*)',
          }],
          destination: '/user/:name',
      }],
    };
  },
```

Which aims to rewrite "/user-query?name=bacon" to "/user/bacon". This does not appear to work correctly in next-on-pages. I'm not sure if this is a particularly unusual pattern or not but does seem to follow the docs on nextjs and does work when running in development or production build with next. It appears to only fail when locally using `wrangler` or when deployed to a preview URL on Cloudflare.

I also believe fixing this could fix some of the issues with `@sentry/nextjs` as their tunnelling option makes use of a very similar rewrite under-the-hood.

<details>
  <summary>@sentry/nextjs rewrite option</summary>

  ```
    {
      // Matched rewrite routes will look like the following: `[tunnelPath]?o=[orgid]&p=[projectid]`
      // Nextjs will automatically convert `source` into a regex for us
      source: `${tunnelPath}(/?)`,
      has: [
        {
          type: 'query',
          key: 'o', // short for orgId - we keep it short so matching is harder for ad-blockers
          value: '(?<orgid>.*)',
        },
        {
          type: 'query',
          key: 'p', // short for projectId - we keep it short so matching is harder for ad-blockers
          value: '(?<projectid>.*)',
        },
      ],
      destination: 'https://o:orgid.ingest.sentry.io/api/:projectid/envelope/',
    }
  ```
</details>

### Reproduction

https://github.com/emma-cw/next-pages-rewrites-test

Pulling this repo and running with `npm run dev`/`yarn dev` will run successfully and the rewrite will behave as expected. For example `http://localhost:3000/user/bacon` and `http://localhost:3000/user-query?name=bacon` will display the same very basic page.

However if running with `npx @cloudflare/next-on-pages@1` and then `npx wrangler pages dev .vercel/output/static --compatibility-flag=nodejs_compat` the rewrite no longer functions as expected. Instead,  `http://localhost:8788/user/bacon` will show correctly but `http://localhost:8788/user-query?name=bacon` will return `404` instead.

### Pages Deployment Method

None

### Would you like to help?

- [ ] Would you like to help fixing this bug?

**Comment by james-elicx** [comment]
Hey there, thank you for opening this issue. I actually find it rather interesting because the Vercel build output config documentation doesn't describe this behaviour, but I can see that the [Next.js docs](https://nextjs.org/docs/app/api-reference/next-config-js/rewrites#header-cookie-and-query-matching) do.

I have opened a PR that should resolve this. Would you be able to try out the prerelease in https://github.com/cloudflare/next-on-pages/pull/449#issuecomment-1702920072, please?

**Comment by emma-cw** [comment]
Hi @james-elicx,

Thank you so much for the quick turnaround on this. That prerelease works perfectly and has also instantly fixed the tunnelling option for the Sentry next.js as well.
