### ISSUE TITLE
[🐛 Bug]: Can't inject Durable Object Classes into the root export in Dev env

### ISSUE THREAD

**Issue by kjmph** [cloudflare/next-on-pages#458]
### next-on-pages environment related information

```
System:
        Platform: darwin
        Arch: arm64
        Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000
        CPU: (10) arm64 Apple M1 Max
        Memory: 64 GB
        Shell: /opt/homebrew/bin/bash
Binaries:
        Node: 20.6.0
        Bun: N/A
        pnpm: 8.7.4
        Yarn: N/A
        npm: 10.0.0
Package Manager Used: npm
Relevant Packages:
        @cloudflare/next-on-pages: 1.6.0
        vercel: N/A
        next: 13.4.19
```

### Description

While it appears pretty straightforward to use next-on-pages with a KV Namespace in Dev env, it is unclear how to do so for Durable Objects. When next-on-pages is done, there are two ways to move forward.

A) Use the wrangler cli command and only specify configuration in the command line:

```sh
$ npx wrangler pages dev --kv=KV_TEST --do=DO_TEST=TestDurableObject --log-level=debug --compatibility-date=2023-09-04 .vercel/output/static --compatibility-flags="nodejs_compat"
...
workerd/server/server.c++:2614: info: Inspector is listening
service core:user:worker: Uncaught TypeError: Class extends value undefined is not a constructor or null
  at u8wnxnokbor.js:879:44 in maskDurableObjectDefinition
  at u8wnxnokbor.js:888:26
✘ [ERROR] MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.
...
```

This can be fixed. Edit the `.vercel/output/static/_worker.js/index.js` file after next-on-pages completes the build and insert the Durable Object Class as a root module export. This allows one to move forward, and perhaps could be automated, however, this is a difficult prospect for developers to follow. Also, how would that work with deploys to remote?

B) Use the wrangler.toml file to specify configuration:

```toml
# Used in top of the Next project
compatibility_date = "2023-09-04"
compatibility_flags = ["nodejs_compat"]

[durable_objects]
bindings = [{name = "DO_TEST", class_name = "TestDurableObject", script_name = "dotest" }]

[miniflare.mounts]
dotest = "./lib/dotest"

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["TestDurableObject"]
```

AND

```toml
# in lib/dotest/wrangler.toml
name = "dotest"
main = "dotest.mjs"
compatibility_date = "2023-09-04"
```

This appears to work so that next-on-pages will build the project and wrangler will execute the project. However, Wrangler reports the following warnings on startup:

```
▲ [WARNING] Processing wrangler.toml configuration:

    - 😶 Ignored: "miniflare":
      Wrangler does not use configuration in the `miniflare` section. Unless you are using Miniflare
  directly you can remove this section.


▲ [WARNING] WARNING: You have Durable Object bindings that are not defined locally in the worker being developed.

  Be aware that changes to the data stored in these Durable Objects will be permanent and affect the
  live instances.
  Remote Durable Objects that are affected:
  - {"name":"DO_TEST","class_name":"TestDurableObject","script_name":"dotest"}


Metrics dispatcher: Dispatching disabled - would have sent {"type":"event","name":"run dev","properties":{"local":true,"usesTypeScript":false}}.
Using vars defined in .dev.vars
Your worker has access to the following bindings:
- Durable Objects:
  - DO_TEST: TestDurableObject (defined in dotest)
- KV Namespaces:
  - KV_TEST: KV_TEST
▲ [WARNING] ⎔ Support for external Durable Objects in local mode is experimental and may change.
```

When attempting to access the Durable Object from a route handler, the fetch 503s. Most likely because this is a fully external durable object, and if the dev does `npx wrangler dev` inside the `lib/dotest` directory, the sub-project listens on a different port.

So.. How does one test and use Durable Objects with next-on-pages and wrangler? There appears to be no example project. The next-on-pages README reference the Cloudflare Next.js Doc which states:

```
Use bindings in your Next.js application

A [binding](https://developers.cloudflare.com/pages/platform/functions/bindings/) allows your application to interact with Cloudflare developer products, such as [KV](https://developers.cloudflare.com/workers/learning/how-kv-works/), [Durable Object](https://developers.cloudflare.com/durable-objects/), [R2](https://developers.cloudflare.com/r2/), and [D1](https://developers.cloudflare.com/d1/).

In Next.js, add server-side code via [API Routes](https://nextjs.org/docs/pages/building-your-application/routing/api-routes), [Route Handlers](https://nextjs.org/docs/app/building-your-application/routing/router-handlers), and [getServerSideProps](https://nextjs.org/docs/pages/building-your-application/data-fetching/get-server-side-props). Then, access bindings set for your application by accessing them in your code via process.env.

The following code block shows an example of accessing a KV namespace in Next.js.
...
```

Please let me know.

### Pages Deployment Method

None

### Additional Information

This is predominantly about having developers test their work locally before deploying preview instances. However, even so, the above may apply to deployments, we haven't tried that yet.

### Would you like to help?

- [X] Would you like to help fixing this bug?

**Comment by kjmph** [comment]
Note, to be clear, by injecting the Durable Object Class into the root exports in the example listed in A works. This can be confirmed by reading the stored object back from the resulting SQLite database.

**Comment by Ehesp** [comment]
It was my understanding that you can't export a DO running in pages project. You can only bind to a DO running elsewhere.

Might be outdated info though.

**Comment by dario-piotrowicz** [comment]
@Ehesp is correct you cannot instantiate your DO in the pages app, you can only do that in a standard worker and then to test it locally you have to (in parallel):
 - run your worker locally via `wrangler dev`
 - run your next-on-pages app via `wrangler pages dev` with `--do MyDO=MyDurableObjectClass@scriptName`
    (where `MyDO` is the name of the binding, `MyDurableObjectClass` is the name of its class and `scriptName` is the name of your worker)

([source](https://github.com/cloudflare/workers-sdk/commit/ddf7319e733e27f3210dee708a69bc36fa7d4328))

___

It doesn't look like this is properly documented (neither in the pages docs nor in `wrangler pages dev --help`)
sorry about that I will look into improving this 🙇

___

@kjmph hopefully this helps? 🙂 

PS: additionally I'd like to clarify that Pages (`wrangler pages dev`, etc...) don't read the wrangler.toml file, that is a config file used for workers only, Pages doesn't currently have a config file, so nothing that you do in wrangler.toml should have any impact on the next-on-pages app

**Comment by dario-piotrowicz** [comment]
👆 amending my comment above (I checked with a Pages team member and I did get it slightly wrong):

Technically, you can `wrangler pages dev` with DOs you've exported from within the same _worker.js script.

But this won't work on prod because those DOs don't get deployed anyways.

.... so technically yeah you can defined your DOs in Pages apps, but in practice you can't ... 😅

**Comment by kjmph** [comment]
@dario-piotrowicz, it looks like this did make sense to me! There are a few issues to clean up though, why does there have to be a fetch in the standard DO worker? The goal was to have the DO behind an API that handles authz, yet if the DO worker has its own fetch, then can't that be called? I thought DOs were only referenceable by the workers that bound them. I changed the example here:

https://github.com/cloudflare/workers-sdk/blob/95b24b1eb986fb73a2b87c5a0eecc32a607e7331/fixtures/external-durable-objects-app/a/index.ts#L2-L7

to the following:

```typescript
    fetch(request: Request, env: { MY_DO: DurableObjectNamespace }) {
        return new Response('No'); // Random test response
        // const { pathname } = new URL(request.url);
        // const id = env.MY_DO.idFromName(pathname);
        // const stub = env.MY_DO.get(id);
        // return stub.fetch(request);
    },
```

Also, the one nice thing about having DOs in the _worker.js script is that local development is one less step.. Although, this is minor. As you state, deploys don't work, so may as well handle this appropriately. Thanks for all the notes!

**Comment by dario-piotrowicz** [comment]
@kjmph I'm glad my comment helped 😄
I'm closing the issue since it seems resolved (since your questions are Pages related and not specific issues with next-on-pages), please feel free to reopen it if you still have issues with DOs

Regarding your questions, if you don't want to expose an endpoint from the DO worker you could also have it be a [scheduled worker](https://developers.cloudflare.com/workers/runtime-apis/scheduled-event/) (which is never invoked) in that way no fetch handler needs to be defined and basically you only instantiate the DO.

But anyways returning a dummy response as you did works just as well.

I also think that it is a bit unfortunate that you need to define a worker that creates the DO... but since DOs don't get deployed with Pages than that makes sense to me since there isn't any other way to create a DO otherwise (as to why Pages can't deploy DOs I am not completely sure, it might be because of a technical limitation, like the lack of a config file, and maybe it could change in the future 🤷, if you want more details feel free to ask on the [Discord Server](https://discord.com/invite/cloudflaredev) as someone there could be able to provide more details 🙂)
