### ISSUE TITLE
[🐛 Bug]: i18n edge routes generate nodejs routes with vercel >= 32.2.0

### ISSUE THREAD

**Issue by neko-shinshi** [cloudflare/next-on-pages#464]
### next-on-pages environment related information

System:
	Platform: darwin
	Arch: arm64
	Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:17:35 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T8112
	CPU: (8) arm64 Apple M2
	Memory: 16 GB
	Shell: /bin/zsh
Binaries:
	Node: 20.6.1
	Bun: N/A
	pnpm: 8.6.6
	Yarn: 1.22.19
	npm: 9.8.1
Package Manager Used: npm
Relevant Packages:
	@cloudflare/next-on-pages: 1.6.1
	vercel: N/A
	next: 13.4.19

### Description

Hi, I am using the page router with subpath routing to handle i18 for my existing site and have deployed it with internationalization enabled. 

A few hours ago I started getting this error when trying to update, so I made another minimal project to demonstrate it.

`<pre class="c_px c_bv c_sj c_sk c_aha c_ahb c_db c_sx c_ahg c_ahh c_ahi c_hp c_hq c_ahc c_bx c_ahj">

15:27:23.841 | ⚡️ Completed `npx vercel build`.
-- | --
15:27:25.037 |  
15:27:25.038 | ⚡️ ERROR: Failed to produce a Cloudflare Pages build from the project.
15:27:25.038 | ⚡️
15:27:25.038 | ⚡️ 	The following routes were not configured to run with the Edge Runtime:
15:27:25.039 | ⚡️ 	  - /default
15:27:25.039 | ⚡️ 	  - /en
15:27:25.039 | ⚡️ 	  - /ja
15:27:25.039 | ⚡️
15:27:25.039 | ⚡️ 	Please make sure that all your non-static routes export the following edge runtime route segment config:
15:27:25.039 | ⚡️ 	  export const runtime = 'edge';
15:27:25.039 | ⚡️
15:27:25.039 | ⚡️ 	You can read more about the Edge Runtime on the Next.js documentation:
15:27:25.040 | ⚡️ 	  https://nextjs.org/docs/app/building-your-application/rendering/edge-and-nodejs-runtimes
15:27:25.040 |  
15:27:25.061 | Failed: Error while executing user command. Exited with error code: 1
15:27:25.071 | Failed: build command exited with code: 1
15:27:25.966 | Failed: error occurred while running build command

</pre>`

I already have export const runtime = 'experimental-edge' in each page's code, and it still does not work with 'edge'. The pages work again when internationalization is disabled so the error should be related to it.

### Reproduction

I made a minimal project to demonstrate this:
https://github.com/neko-shinshi/cloudflare-next-i18

### Pages Deployment Method

Direct Upload (`wrangler pages publish` or the @cloudflare/pages-action GitHub Action)

### Pages Deployment ID

cloudflare-next-i18.pages.dev

### Would you like to help?

- [X] Would you like to help fixing this bug?

**Comment by dario-piotrowicz** [comment]
Thanks a lot for the issue @neko-shinshi and thanks a lot for being willing to help with it!

This seems like an issue introduced recently by the Vercel CLI, @james-elicx has already opened a PR that should fix it, if you want please check the [PR's prerelease](https://github.com/cloudflare/next-on-pages/pull/466#issuecomment-1724311994) to see if it fixes your issue 🙂
