### ISSUE TITLE
[🐛 Bug]: Next.js Link component not working

### ISSUE THREAD

**Issue by dhmacs** [cloudflare/next-on-pages#469]
### next-on-pages environment related information

System:
	Platform: darwin
	Arch: arm64
	Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000
	CPU: (10) arm64 Apple M1 Max
	Memory: 32 GB
	Shell: /bin/zsh
Binaries:
	Node: 16.14.2
	Bun: N/A
	pnpm: 8.5.1
	Yarn: 1.22.15
	npm: 8.5.0
Package Manager Used: npm
Relevant Packages:
	@cloudflare/next-on-pages: 1.6.1
	vercel: 32.3.1
	next: 13.5.2

### Description

Next.js Link component do not trigger client side navigation and always result in a page reload.
On top of that, the default `prefetch` behaviour results in 404 errors in the console

<img width="617" alt="Screenshot 2023-09-24 at 16 15 31" src="https://github.com/cloudflare/next-on-pages/assets/4640135/b968c34b-45a0-4e3c-8545-8a98ce0c1242">

### Reproduction

Create a new project with:

```
npm create cloudflare@latest my-next-app -- --framework=next
```

Add a second dummy page, and link to it from the home page. Deploy to Cloudflare pages and use the production url to see the issue described above

### Pages Deployment Method

Direct Upload (`wrangler pages publish` or the @cloudflare/pages-action GitHub Action)

### Pages Deployment ID

69ea45f8

### Additional Information

Here's the link from my test project: https://69ea45f8.test-link.pages.dev

### Would you like to help?

- [ ] Would you like to help fixing this bug?

**Comment by dario-piotrowicz** [comment]
@dhmacs thanks so very much for the issue 🙂 🙏 

It turns out that some changes on Vercel's side broke the prefetching and client side navigation, thanks so much for pointing that out 🙂

If you want please give #471's [prerelease](https://github.com/cloudflare/next-on-pages/pull/471#issuecomment-1736297485) a try, it should solve the issue 👍
