### ISSUE TITLE
[🐛 Bug]:  Request fails when asset name start with 500 and 404

### ISSUE THREAD

**Issue by divyam234** [cloudflare/next-on-pages#470]
### Description

This happens only when  if any asset contains name which start with error status codes .For example  
 ```http://abc.com/files/500-abc.pdf```  this request fails. I recon it gets confused b/w error status pages.

### Reproduction

Use above route pattern will reproduce bug.

### Pages Deployment Method

None

### Would you like to help?

- [ ] Would you like to help fixing this bug?

**Comment by dario-piotrowicz** [comment]
@divyam234 thanks so much for the issue 🙂 

it does look bizarre I'll have a look 👍 

But anyways one quick question.... it looks to me like this only happens with `500`s.... are you sure you've seen it with other numbers as well?

![Screenshot 2023-09-27 at 23 42 54](https://github.com/cloudflare/next-on-pages/assets/61631103/35c79977-2e90-4314-8412-fbf81f796859)

**Comment by dario-piotrowicz** [comment]
Correction, I think it only applies to `500`s and `404`s 
![Screenshot 2023-09-27 at 23 49 05](https://github.com/cloudflare/next-on-pages/assets/61631103/fc093d86-83b9-46d5-9948-32e43a9290ad)

**Comment by divyam234** [comment]
Yeah 500 and 404
