### ISSUE TITLE
[🐛 Bug]: Error: An error occurred while gathering the package info of

### ISSUE THREAD

**Issue by mmiszy** [cloudflare/next-on-pages#474]
### next-on-pages environment related information

(`--info` is also broken so can't run it)

pnpm v8.8.0
node.js v20.5.1

### Description

1.6.2 broke the CLI – builds and `--info` throw the following error:

```
/Users/typeofweb/project/node_modules/.pnpm/registry.npmjs.org+@cloudflare+next-on-pages@1.6.2_vercel@32.3.1_wrangler@3.10.1/node_modules/@cloudflare/next-on-pages/dist/index.js:7922
      throw new Error(`An error occurred while gathering the package info of "${n3}"`);
            ^

Error: An error occurred while gathering the package info of "next"
    at Object.getPackageInfo (/Users/typeofweb/project/node_modules/.pnpm/registry.npmjs.org+@cloudflare+next-on-pages@1.6.2_vercel@32.3.1_wrangler@3.10.1/node_modules/@cloudflare/next-on-pages/dist/index.js:7922:13)
    at async Promise.all (index 1)
    at async printEnvInfo (/Users/typeofweb/project/node_modules/.pnpm/registry.npmjs.org+@cloudflare+next-on-pages@1.6.2_vercel@32.3.1_wrangler@3.10.1/node_modules/@cloudflare/next-on-pages/dist/index.js:8563:40)
    at async runNextOnPages (/Users/typeofweb/project/node_modules/.pnpm/registry.npmjs.org+@cloudflare+next-on-pages@1.6.2_vercel@32.3.1_wrangler@3.10.1/node_modules/@cloudflare/next-on-pages/dist/index.js:15146:5)
```

Works fine on 1.6.1

### Pages Deployment Method

None

### Would you like to help?

- [ ] Would you like to help fixing this bug?

**Comment by zafar26** [comment]
> We just discovered 1.6.2 is also breaking our deploys. Attached are screenshots 1.6.1 vs 1.6.2
> 
> ![image](https://github.com/cloudflare/next-on-pages/assets/368767/f2062a9f-a274-465b-b5e3-dbe68229a8d8)
> ![image](https://github.com/cloudflare/next-on-pages/assets/368767/2e20e6fc-5b16-4562-86ee-c298e57ff933)
> 
> I'm noticing the OP is also using `pnpm` (as are we) - perhaps there's something subtle going on there

I am also getting this Error 

Please help

**Comment by dario-piotrowicz** [comment]
Hi, sorry about this bug, it's a regression that happened because we've updated how we handle package managers and package logic, somehow nothing wrong resulted in our manual and e2e tests.... anyways we've reverted the change and made a quick hotfix release so it should hopefully be ok now (and I'll look more into the issue with the package manager approach in the next few days)

**Comment by jmonster** [comment]
@dario-piotrowicz thanks so much for the quick resolution! my deploys have resumed working

**Comment by dario-piotrowicz** [comment]
@jmonster no problem 🙂, sorry for the inconvenience... as I said using the new package really didn't seem to be a problem when I tested it 😓 🙇
