### ISSUE TITLE
[🐛 Bug]: 

### ISSUE THREAD

**Issue by gabrielf** [cloudflare/next-on-pages#484]
### next-on-pages environment related information

```
System:
	Platform: darwin
	Arch: arm64
	Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:23 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6020
	CPU: (12) arm64 Apple M2 Pro
	Memory: 16 GB
	Shell: /bin/zsh
Binaries:
	Node: 20.8.0
	Bun: N/A
	pnpm: N/A
	Yarn: N/A
	npm: 10.1.0
Package Manager Used: npm
Relevant Packages:
	@cloudflare/next-on-pages: 1.6.3
	vercel: N/A
	next: 13.5.3
```

### Description

According to [supported.md](https://github.com/cloudflare/next-on-pages/blob/main/packages/next-on-pages/docs/supported.md) i18n is fully supported but it seems that it also breaks serving files from the public folder. When activating i18n the files in the public folder are no longer served but get a 404 instead.

### Reproduction

We have created a minimal Next.js-app using `create-next-app` available on: https://github.com/soundtrackyourbrand/next-on-pages-i18n-issue that reproduces the issue.

The readme in the project explains how to use it but in essence activating i18n, for a Next.js app using the pages router, will make files from the public folder stop serving. This is demonstrated both with a robots.txt file but also with the default logo from the `create-next-app` which both get a 404 when built with next-on-pages and run with wrangler.

### Pages Deployment Method

None

### Additional Information

We detected this in a largish Next.js app, running on Cloudflare pages, after activating i18n. We have, however, since detecting the problem disabled i18n.

### Would you like to help?

- [X] Would you like to help fixing this bug?

**Comment by james-elicx** [comment]
I actually think this might have been fixed by https://github.com/cloudflare/next-on-pages/pull/473.

Could you try the beta version of next-on-pages and confirm please - `@cloudflare/next-on-pages@beta`?

**Comment by gabrielf** [comment]
Using `@cloudflare/next-on-pages@beta` did solve the problem with i18n + public folder, wonderful!

Unfortunately the beta seems to trigger a bug/limitation in package-manager-manager when using [asdf](https://asdf-vm.com/) as a version manager for node/npm which leads to the below error:

```shell
$ npx @cloudflare/next-on-pages@beta --info         
EXIT WHEN NOT EXPECTED

SHELLAC COMMAND FAILED!
Executing: npm --version in /Users/<user>/Code/nextjs-sandbox

STDOUT:



STDERR:

/Users/<user>/.asdf/plugins/nodejs/shims/npm: line 14: HOME: unbound variable


node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```

Using asdf works flawlessly for running `npx @cloudflare/next-on-pages` but fails for the beta starting with commit #69efaa5. #0fb53a7 works. But this is due to package-manager-manager so I'll log an issue there, or see if I can solve the problem, tomorrow.

Thanks for the swift reply! ❤️

**Comment by gabrielf** [comment]
Closing as this is fixed in the beta!

By the way, after thinking about the `HOME: unbound variable` situation above, I think it's an asdf issue. Normal package managers don't require the HOME env variable so the shim installed by asdf's nodejs plugin shouldn't require it either.

**Comment by james-elicx** [comment]
Thanks for the update, glad to hear the latest changes resolved your problem :)
