### ISSUE TITLE
"npm run build" should be run on "prepare" event to allow direct github installs

### ISSUE THREAD

**Issue by nakedible** [cloudflare/next-on-pages#49]
Currently `package.json` seems to run `npm run build` as part of the `publish` hook. Instead, that part should be run in the `prepare` hook, to support cases where this repository is installed as a dependency directly from GitHub and not via a published packages.

See: https://docs.npmjs.com/cli/v9/using-npm/scripts#prepare-and-prepublish

**Comment by mrluc** [comment]
👋  howdy @dario-piotrowicz -- this issue is right on the money; this is what I did in my fork, so that I could point the dependency at github:

https://github.com/mrluc/next-on-pages/commit/0ecb47d4aa73d409c9e6c8010b32e0e22dd00976

**Comment by dario-piotrowicz** [comment]
Thanks for the issue @nakedible 🙂 

And thanks for pinging me @mrluc 😄 

it does seem sensible to me, I've created a PR with the script, let me know if that works for you 🙂👍

**Comment by nakedible** [comment]
I will test later, but quick comment:

npm publish runs:
- prepublishOnly
- prepack
- prepare
- postpack
- publish
- postpublish

npm install runs:
- preinstall
- install
- postinstall
- prepublish
- preprepare
- prepare
- postprepare

Hence there is no sense in having `npm run build` both in prepare and publish. Prepare should be enough to get it run also when running `npm publish`. That's the point of the hook...

**Comment by mrluc** [comment]
@nakedible yeah that makes sense, thanks for checking the docs -- my commit referenced above unblocked us 😄 but ofc we're not running `npm publish`

**Comment by dario-piotrowicz** [comment]
Thanks a lot @nakedible I also did check the npm docs (as I must admit I am not really that super familiar with generating npm packages), the docs do say that `prepare` runs before `publish` and `pack` but testing locally that didn't seem the case, that's why I implemented it this way
