### ISSUE TITLE
`_routes.json` support

### ISSUE THREAD

**Issue by GregBrimble** [cloudflare/next-on-pages#5]
https://developers.cloudflare.com/pages/platform/functions/billing/#will-requests-to-assets-be-charged

**Comment by arielvieira** [comment]
One quick tip for now is to create a `_routes.json` 
file manually inside the next `public` directory with all of your static assets and pages. Now that file will be picked up by Cloudflare Pages and will not run the functions for static assets.

_routes.json reference:
https://developers.cloudflare.com/pages/platform/functions/routing/#creating-a-_routesjson-file

**Comment by karimkaylani** [comment]
It seems like the `_routes.json` file is supposed to be in your root directory, not in the `public` folder.

See here for more info: https://github.com/cloudflare/next-on-pages/blob/main/packages%2Fnext-on-pages%2Fdocs%2Fstatic-assets-routing.md

**Comment by dario-piotrowicz** [comment]
Yes, this was implemented by @james-elicx a while back (https://github.com/cloudflare/next-on-pages/pull/402) 👍
