### ISSUE TITLE
[🐛 Bug]: Unhelpful Error Message when running "npx @cloudflare/next-on-pages@1"

### ISSUE THREAD

**Issue by dvaJi** [cloudflare/next-on-pages#510]
### next-on-pages environment related information

System:
        Platform: win32
        Arch: x64
        Version: Windows 10 Pro
        CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
        Memory: 32 GB
        Shell: C:\Program Files\Git\usr\bin\bash.exe
Package Manager Used: npm (10.2.0)

Relevant Packages:
        @cloudflare/next-on-pages: 1.7.0
        vercel: 32.4.1
        next: 13.5.6

### Description

When attempting to build my application using the "npx @cloudflare/next-on-pages@1" command in watch mode, I encountered an error that wasn't providing helpful information. The error message displayed is: "⚡️ Watch mode unexpected error: [object Object]."

**Expected Behavior:**
Errors encountered should provide specific information to help identify and address the issue.

**Actual Behavior:**
An error message is displayed, but it simply states: "⚡️ Watch mode unexpected error: [object Object]."

### Reproduction

Run the following command in the terminal:

`npx @cloudflare/next-on-pages@1`

### Pages Deployment Method

None

### Would you like to help?

- [X] Would you like to help fixing this bug?

**Comment by dario-piotrowicz** [comment]
Hi @dvaJi version 1.7.0 had this issue which I put a patch on in https://github.com/cloudflare/next-on-pages/pull/509 so you should hopefully not encountering it anymore, sorry about the regression 🙇 

If you'd still like to help and make sure we don't risk showing `[object Object]` in the future please feel free to improve this piece of code (where printing `${error}` is what generates the `[object Object]`):
https://github.com/cloudflare/next-on-pages/blob/b4745806c514ac26d070df11f2c42eb9ff2eed76/packages/next-on-pages/src/index.ts#L75

with a simple stringify and/or also asserting if the `error` object is an instance of `Error` and in that case display it accordingly
