### ISSUE TITLE
[🐛 Bug]: Next.js deployed failed on getStaticPath page

### ISSUE THREAD

**Issue by vader1359** [cloudflare/next-on-pages#522]
### next-on-pages environment related information

  "error": {
    "code": "ELSPROBLEMS",
    "summary": "extraneous: @isaacs/cliui@8.0.2 /Users/iant1359/Develop/projects/next-cloudflare/node_modules/@isaacs/cliui\nextraneous: @npmcli/agent@2.2.0 /Users/iant1359/Develop/projects/next-cloudflare/node_modules/@npmcli/agent\nextraneous: @npmcli/fs@3.1.0 /Users/iant1359/Develop/projects/next-cloudflare/node_modules/@npmcli/fs\nextraneous: @pkgjs/parseargs@0.11.0 /Users/iant1359/Develop/projects/next-cloudflare/node_modules/@pkgjs/parseargs\nextraneous: abbrev@2.0.0 /Users/iant1359/Develop/projects/next-cloudflare/node_modules/abbrev\nextraneous: agent-base@7.1.0 /Users/iant1359/Develop/projects/next-cloudflare/node_modules/agent-base\nextraneous: cacache@18.0.0 /Users/iant1359/Develop/projects/next-cloudflare/node_modules/cacache\nextraneous: eastasianwidth@0.2.0 /Users/iant1359/Develop/projects/next-cloudflare/node_modules/eastasianwidth\nextraneous: err-code@2.0.3 /Users/iant1359/Develop/projects/next-cloudflare/node_modules/err-code\nextraneous: exponential-backoff@3.1.1 /Users/iant1359/Develop/projects/next-cloudflare/node_modules/exponential-backoff\nextraneous: foreground-child@3.1.1 /Users/iant1359/Develop/projects/next-cloudflare/node_modules/foreground-child\nextraneous: http-proxy-agent@7.0.0 /Users/iant1359/Develop/projects/next-cloudflare/node_modules/http-proxy-agent\nextraneous: ip@2.0.0 /Users/iant1359/Develop/projects/next-cloudflare/node_modules/ip\nextraneous: is-lambda@1.0.1 /Users/iant1359/Develop/projects/next-cloudflare/node_modules/is-lambda\nextraneous: jackspeak@2.3.6 /Users/iant1359/Develop/projects/next-cloudflare/node_modules/jackspeak\nextraneous: make-fetch-happen@13.0.0 /Users/iant1359/Develop/projects/next-cloudflare/node_modules/make-fetch-happen\nextraneous: minipass-collect@1.0.2 /Users/iant1359/Develop/projects/next-cloudflare/node_modules/minipass-collect\nextraneous: minipass-fetch@3.0.4 /Users/iant1359/Develop/projects/next-cloudflare/node_modules/minipass-fetch\nextraneous: minipass-flush@1.0.5 /Users/iant1359/Develop/projects/next-cloudflare/node_modules/minipass-flush\nextraneous: minipass-pipeline@1.2.4 /Users/iant1359/Develop/projects/next-cloudflare/node_modules/minipass-pipeline\nextraneous: minipass-sized@1.0.3 /Users/iant1359/Develop/projects/next-cloudflare/node_modules/minipass-sized\nextraneous: negotiator@0.6.3 /Users/iant1359/Develop/projects/next-cloudflare/node_modules/negotiator\nextraneous: node-gyp@10.0.0 /Users/iant1359/Develop/projects/next-cloudflare/node_modules/node-gyp\nextraneous: nopt@7.2.0 /Users/iant1359/Develop/projects/next-cloudflare/node_modules/nopt\nextraneous: proc-log@3.0.0 /Users/iant1359/Develop/projects/next-cloudflare/node_modules/proc-log\nextraneous: promise-retry@2.0.1 /Users/iant1359/Develop/projects/next-cloudflare/node_modules/promise-retry\nextraneous: retry@0.12.0 /Users/iant1359/Develop/projects/next-cloudflare/node_modules/retry\nextraneous: smart-buffer@4.2.0 /Users/iant1359/Develop/projects/next-cloudflare/node_modules/smart-buffer\nextraneous: socks-proxy-agent@8.0.2 /Users/iant1359/Develop/projects/next-cloudflare/node_modules/socks-proxy-agent\nextraneous: socks@2.7.1 /Users/iant1359/Develop/projects/next-cloudflare/node_modules/socks\nextraneous: ssri@10.0.5 /Users/iant1359/Develop/projects/next-cloudflare/node_modules/ssri\nextraneous: string-width-cjs@npm:string-width@4.2.3 /Users/iant1359/Develop/projects/next-cloudflare/node_modules/string-width-cjs\nextraneous: strip-ansi-cjs@npm:strip-ansi@6.0.1 /Users/iant1359/Develop/projects/next-cloudflare/node_modules/strip-ansi-cjs\ninvalid: styled-components@5.3.11 /Users/iant1359/Develop/projects/next-cloudflare/node_modules/styled-components\nextraneous: unique-filename@3.0.0 /Users/iant1359/Develop/projects/next-cloudflare/node_modules/unique-filename\nextraneous: unique-slug@4.0.0 /Users/iant1359/Develop/projects/next-cloudflare/node_modules/unique-slug\nextraneous: wrap-ansi-cjs@npm:wrap-ansi@7.0.0 /Users/iant1359/Develop/projects/next-cloudflare/node_modules/wrap-ansi-cjs",
    "detail": ""
  }
}

It's too long...

### Description

![CleanShot 2023-10-30 at 11 04 37@2x](https://github.com/cloudflare/next-on-pages/assets/27997820/c4e7a385-cd5a-41cb-b24a-702bd746611b)

All these paths have getStaticPaths function.

I tried to add export const runtime = 'edge' to these pages, it will complain Error: Page /news/[...id] provided runtime 'edge', the edge runtime for rendering is currently experimental. Use runtime 'experimental-edge' instead.
IF I swith to experimental-edge, it will complain > webpack config.resolve.alias was incorrectly overridden. https://nextjs.org/docs/messages/invalid-resolve-alias
Tried to add the export const runtime = 'edge' to layout, it build OK but failed on deployment.

### Reproduction

Here is the minimum repo.
https://github.com/vader1359/next-cloudflare

### Pages Deployment Method

Direct Upload (`wrangler pages publish` or the @cloudflare/pages-action GitHub Action)

### Additional Information

This project is created using this: npm create cloudflare@latest my-next-app -- --framework=next

### Would you like to help?

- [ ] Would you like to help fixing this bug?

**Comment by dario-piotrowicz** [comment]
Hi @vader1359 thanks for the issue 🙂  (and sorry for the late reply 😓)

I've had a look at your minimal reproduction (by the way thanks a lot for providing one 🙏), but the `pages:build` script seems to succeed, both in the top level project and in the next-14-cloud-npm one, could you double check and let me know how to reproduce the issue there? 🙏 

Also in your issue description you mention `getStaticPaths` but I [can't find](https://github.com/search?q=repo%3Avader1359%2Fnext-cloudflare+%2FgetStaticPaths%2F&type=code) any in your minimal reproduction (is something missing there?)

Regarding `getStaticPaths` I also wanted to ask you if you have seen [our documentation about it](https://github.com/cloudflare/next-on-pages/blob/main/packages/next-on-pages/docs/supported.md#getstaticpaths) and accordingly added the required `fallback: false` values.

**Comment by dario-piotrowicz** [comment]
Closing this issue to the lack or response from my previous message

@vader1359 I hope you don't mind, please feel free to reopen this issue if you still need assistance with it 🙏
