### ISSUE TITLE
[⚡ Feature]: Add Queues Producers support to the `next-dev` submodule

### ISSUE THREAD

**Issue by dario-piotrowicz** [cloudflare/next-on-pages#526]
### Description

The `next-dev` submodule (introduced in #486) is missing support for local Queue produces (as discussed in 
https://github.com/cloudflare/next-on-pages/pull/486#issuecomment-1779506998), so we should add it.

However it is not yet implemented in `wrangler pages dev`, so we should first wait for it to be implemented there (see: https://github.com/cloudflare/workers-sdk/issues/4336) before adding it to our submodule.

> **Note**
> Queue Consumers are not yet available in Pages, that will probably come later and we'll add them when Pages (and `wrangler pages dev`) supports them

**Comment by dario-piotrowicz** [comment]
cc. @iamvishnusankar 🙂 

(PS: sorry in #486 I didn't realize that Queues aren't fully implemented in Pages 😅)

**Comment by iamvishnusankar** [comment]
@dario-piotrowicz Finally the much awaited updates are here. But totally stuck with not being able to access dashboard because of the Cloudflare outage! 😢

**Comment by dario-piotrowicz** [comment]
@iamvishnusankar yeah quite the outage we've had 😓 , but it should be alright now
