### ISSUE TITLE
[🐛 Bug]: Fails to install next-on-pages after selecting "yes" to installing next-on-pages

### ISSUE THREAD

**Issue by jpoly1219** [cloudflare/next-on-pages#538]
### next-on-pages environment related information

Does not create a output. Running on Powershell on Windows 11.

### Description

<img width="735" alt="image" src="https://github.com/cloudflare/next-on-pages/assets/21210638/c38a3531-417c-4745-949a-68373c356032">

When following the tutorial here: https://developers.cloudflare.com/pages/framework-guides/deploy-a-nextjs-site/#use-the-edge-runtime

After running `npm create cloudflare@latest my-next-app -- --framework=next`, it succeeds in creating the app. However, when I select yes to install `next-on-pages`, it tries to look up the root directory of my C drive, which seems problematic to me.

### Reproduction

Running on Powershell on Windows 11, using node version 18.16.0

`npm create cloudflare@latest my-next-app -- --framework=next`

Select the following options:

<img width="486" alt="image" src="https://github.com/cloudflare/next-on-pages/assets/21210638/efbdbe75-fcf0-4278-9791-4a58f490084e">

Say yes to the prompt `├ Do you want to use the next-on-pages eslint-plugin?`

### Pages Deployment Method

None

### Would you like to help?

- [x] Would you like to help fixing this bug?

**Comment by dario-piotrowicz** [comment]
Hi @jpoly1219 thanks a bunch for the issue 🙂

I think this is a problem with C3 and there's already a gh issue for it: https://github.com/cloudflare/workers-sdk/issues/4282

There's actually also a PR to fix it: https://github.com/cloudflare/workers-sdk/pull/4445 

🙂 

If you want we can keep this issue open for visibility until the C3 PR/issues above aren't merged/solved 🙂

**Comment by jpoly1219** [comment]
Thank you!

**Comment by dario-piotrowicz** [comment]
@jpoly1219 The workers-sdk PR has been merged and the fix has been released 🙂 

Could you please try running `npm create cloudflare@latest my-next-app -- --framework=next` again and let me know if it's all good now? 🙏

**Comment by dario-piotrowicz** [comment]
Closing due to the lack of response, and since I do think that this has been solved

@jpoly1219 if you still encounter this bug please let me know and we can reopen this issue and look into it 🙂
