### ISSUE TITLE
[🐛 Bug]: Request to ?_rsc=* returns 404 and app is no more SPA

### ISSUE THREAD

**Issue by fineshop** [cloudflare/next-on-pages#542]
### next-on-pages environment related information

```
System:
        Platform: linux
        Arch: x64
        Version: #1 SMP Thu Oct 5 21:02:42 UTC 2023
        CPU: (12) x64 AMD Ryzen 5 5500U with Radeon Graphics
        Memory: 3 GB
        Shell: /bin/bash
Package Manager Used: npm (10.1.0)

Relevant Packages:
        @cloudflare/next-on-pages: 1.7.3
        vercel: 32.5.5
        next: 14.0.3
```

### Description

The app is making request to {url}/?_rsc={random_string} and it responses with 404 status code also navigating to other pages hard reloads the page when app is build using `npx @cloudflare/next-on-pages`.
Note that this issue only appears in production mode (built using `npx @cloudflare/next-on-pages`).

Here are screenshots of devtools:
**In production mode** (`npx @cloudflare/next-on-pages`):

![image](https://github.com/cloudflare/next-on-pages/assets/97987158/abbe36c5-4ccb-4189-84a1-3bb1ee849c0c)

![image](https://github.com/cloudflare/next-on-pages/assets/97987158/263e6d45-59c2-413a-8f3b-0bafbb749b29)

![image](https://github.com/cloudflare/next-on-pages/assets/97987158/1141be8c-a616-4f3f-b242-cf0725f291d9)

**In development mode** (`next dev`) **or production mode** (`next build && next start`):

![image](https://github.com/cloudflare/next-on-pages/assets/97987158/5113f06c-fcc8-4f71-8342-27eacc1fc955)

![image](https://github.com/cloudflare/next-on-pages/assets/97987158/534a93d7-ec60-47b1-8839-2e932c0fca78)

### Reproduction

See: https://github.com/techwithdeo/next-pages-test

1. `git clone git@github.com:techwithdeo/next-pages-test.git`
2. `cd next-pages-test`
3. `npm install`
4. `npm run pages:build`
5. `npm run pages:serve`
6. Open DevTools
7. Navigate to /contact

**Works fine ✅ when:**

1. `npm run build`
2. `npm start`

### Pages Deployment Method

*Not yet deployed*

### Pages Deployment ID

*Not yet deployed*

### Would you like to help?

- [ ] Would you like to help fixing this bug?

**Comment by james-elicx** [comment]
Are you able to provide a reproduction?

**Comment by fineshop** [comment]
> Are you able to provide a reproduction?

The error occurs in production mode (built using `npx @cloudflare/next-on-pages`) when using `src` directory.

**Comment by fineshop** [comment]
> Are you able to provide a reproduction?

I have updated the issue.

**Comment by nicholasray** [comment]
I'm also experiencing this problem

**Comment by james-elicx** [comment]
Hi @fineshop @nicholasray, thank you for raising this. I have opened a PR that should fix this, and you are welcome to try out the prerelease in https://github.com/cloudflare/next-on-pages/pull/550#issuecomment-1817851623

**Comment by fineshop** [comment]
> Hi @fineshop @nicholasray, thank you for raising this. I have opened a PR that should fix this, and you are welcome to try out the prerelease in [#550 (comment)](https://github.com/cloudflare/next-on-pages/pull/550#issuecomment-1817851623)
> 
> Thank you very much for providing the reproduction :)

Wow, it works fine now.
