### ISSUE TITLE
[🐛 Bug]: `vc: not found`

### ISSUE THREAD

**Issue by ari-becker** [cloudflare/next-on-pages#544]
### next-on-pages environment related information

Using default setup on Cloudflare Pages

### Description

```
2023-11-15T13:59:42.857796Z	Executing user command: npx @cloudflare/next-on-pages@1
2023-11-15T13:59:46.766589Z	⚡️ @cloudflare/next-on-pages CLI v.1.7.2
2023-11-15T13:59:47.291315Z	⚡️ Detected Package Manager: npm (10.1.0)
2023-11-15T13:59:47.292135Z	⚡️ Preparing project...
2023-11-15T13:59:47.296591Z	⚡️ Project is ready
2023-11-15T13:59:47.297085Z	⚡️ Building project...
2023-11-15T13:59:50.678259Z	▲  sh: 1: vc: not found
2023-11-15T13:59:50.693316Z	
2023-11-15T13:59:50.693679Z	⚡️ The Vercel build (`npx vercel build`) command failed. For more details see the Vercel logs above.
2023-11-15T13:59:50.693881Z	⚡️ If you need help solving the issue, refer to the Vercel or Next.js documentation or their repositories.
2023-11-15T13:59:50.694061Z	
2023-11-15T13:59:50.718735Z	Failed: Error while executing user command. Exited with error code: 1
2023-11-15T13:59:50.729663Z	Failed: build command exited with code: 1
2023-11-15T13:59:51.762904Z	Failed: error occurred while running build command
```

### Pages Deployment Method

Pages CI (GitHub/GitLab integration)

### Pages Deployment ID

fbdcd237-43e5-4f7e-93ca-0bd488b9ce8c

### Would you like to help?

- [ ] Would you like to help fixing this bug?

**Comment by jinseok0** [comment]
I'm in the same situation
the error @cloudflare/next-on-pages version 1.7.1, 1.7.2, 1.7.3

try lowering the version to 1.6.3. It worked for me.

**Comment by ChiragAgg5k** [comment]
Same issue here

**Comment by dario-piotrowicz** [comment]
Hi @ari-becker, thanks for the issue 🙂 

From the deployment you shared I can see that your build command is: `npx @cloudflare/next-on-pages@1`
however I think that the project is using pnpm, I suspect that the incompatibility comes from there, could you try either using npm instead of pnpm or updating your build script to be `pnpm dlx @cloudflare/next-on-pages` instead? 🙏

**Comment by ari-becker** [comment]
> Hi @ari-becker, thanks for the issue 🙂
> 
> From the deployment you shared I can see that your build command is: `npx @cloudflare/next-on-pages@1` however I think that the project is using pnpm, I suspect that the incompatibility comes from there, could you try either using npm instead of pnpm or updating your build script to be `pnpm dlx @cloudflare/next-on-pages` instead? 🙏

Seems to fix.

I would keep the bug open as `vc: not found` is not a helpful error - `@cloudflare/next-on-pages` should identify when there's a conflicting package manager and provide a more helpful error message, and the [documentation](https://developers.cloudflare.com/pages/framework-guides/deploy-a-nextjs-site/#deploy-via-the-cloudflare-dashboard)  should indicate that the correct configuration is either `npx` / `yarn dlx` / `pnpm dlx` depending on the project's package manager.

**Comment by dario-piotrowicz** [comment]
@ari-becker yeah that's a valid point, it was a user error but certainly we could surface it better, I will look into how we can improve this thanks! 🙂

PS: the documentation and dashboard presets are all for npm... changing it would be quite the ordeal, it must have been considered at some point, I will try to see if it was (and if it's in the plan) 👍

**Comment by dario-piotrowicz** [comment]
@jinseok0 and @ChiragAgg5k, are you also using one package manager for the project and a different one in the build command?

**Comment by jinseok0** [comment]
@dario-piotrowicz  oh yeah, I'm using pnpm too, and using npx for the build command.

I also changed the command to pnpm dlx and it built successfully.

**Comment by dario-piotrowicz** [comment]
@ari-becker I've added a warning that shows in case a different package manager is being used to run next-on-pages, I hope that helps, please let me know what you think

I didn't want to straight up throw an error/fail the build as things might still work ok (for example if you have `vercel` installed as a dependency) so forcing a build failure didn't seem right to me (it could also break existing applications), hopefully the warning should help make the `vc: not found` error clearer

**Comment by ari-becker** [comment]
Great, thanks @dario-piotrowicz !

**Comment by wuyasong** [comment]
It's great. Saved me hours of research on this.
