### ISSUE TITLE
[🐛 Bug]: Allow `NextResponse.rewrite()` to proxy a different host in middleware.

### ISSUE THREAD

**Issue by khalil-omer** [cloudflare/next-on-pages#551]
### Description

I am not sure this is even within the scope of next-on-pages or a fundamental Workers security choice. If it is in scope, I'm not sure if it is a feature request or a bug in how Pages interprets Next.js middleware.

For context, we have a marketing site, docs site, and web app. Each are Next.js projects, but it is required for multiple reasons that they be separate sites. 

On Vercel we hosted the app and docs on subdomains. The marketing site, on the root domain, used Next.js middleware to rewrite requests. For example, `/dashboard` to `app.site.com/app/dashboard` and `/docs/welcome` to `docs.site.com/docs/welcome`. By setting `app` and `docs` as the `basePath` for those sites, this worked well and resulted in no routing conflicts. 

On Cloudflare Pages, redirects and same-host rewrites seem to work the same, but rewrites that change the host (to another Pages project on a subdomain) fail silently at runtime. The middleware runs, and `console.log()` shows that the logic is functioning fine, but when the middleware returns the result of `NextResponse.rewrite()`, Pages returns a 404 rather than rewriting. 

Because Vercel uses Workers as their 'edge runtime', I had assumed the behavior would match between Vercel and CF Pages.

### Additional Information

I first submitted [this bug](https://github.com/cloudflare/next-on-pages/issues/546) but realized that the actual difference in behavior was more narrow and possibly not a bug at all. 

### Would you like to help?

- [ ] Would you like to help implement this feature?

**Comment by dario-piotrowicz** [comment]
Hi @khalil-omer, thanks for the issue 🙂 

Sorry it took me a bit to get around to it, I'm having a look at it now

In the meantime I have created this [minimal reproduction](https://github.com/dario-piotrowicz/next-on-pages-issue-551-reproduction) of your issue, where we can see that the difference in behaviour Pages and Vercel have in regards to external rewrites:
 - https://next-on-pages-issue-551-reproduction.pages.dev/
 - https://next-on-pages-issue-551-reproduction.vercel.app/
 
(Please have a look and let me know if the reproduction is not correct 🙂)

**Comment by dario-piotrowicz** [comment]
@khalil-omer I have implemented a fix for the issue in #568, it sees to work as expected based on my testing

See the pages example mentioned above:
- Before: https://97f409b8.next-on-pages-issue-551-reproduction.pages.dev/
and
- After: https://c60293e7.next-on-pages-issue-551-reproduction.pages.dev/

If you want please try to [PR's prerelease](https://github.com/cloudflare/next-on-pages/pull/568#issuecomment-1836097594) and let me know if it solves the issue on your end as well 🙂 🙏
