### ISSUE TITLE
[🐛 Bug]: `next/cache`: Handle changed type signature of Next.js 13.5+

### ISSUE THREAD

**Issue by susemeee** [cloudflare/next-on-pages#556]
> Hello! I have been debugging `revalidateTag` inconsistency and found out some breaking changes of upstream.
> 
> Internal cache handling behavior of Next.js seems to be changed starting from version 13.5 and above. `IncrementalCacheValue` no longer provides `tags` attribute, results in inability of flushing cache with tags. (despite [revalidate code](https://github.com/cloudflare/next-on-pages/blob/2d5dde95176bca46cdd63c8b204699127017c219/packages/next-on-pages/templates/_worker.js/utils/cache.ts#L19C44-L19C54) works fine)

looks like the type signature changed in next.js :(

https://github.com/vercel/next.js/blob/canary/packages/next/src/server/response-cache/types.ts

would you be able to open a new issue for this @susemeee? i recall on your other issue you ticked the box that you'd be interested in helping fix the bug. would you like to give this issue a go? if not, just lmk and i'll be happy to look into a fix

_Originally posted by @james-elicx in https://github.com/cloudflare/next-on-pages/issues/451#issuecomment-1822392271_

**Comment by susemeee** [comment]
In request headers there is `x-vercel-cache-tags` property exists, and I think it is okay to use it if original property is missing.

@james-elicx Could you check if it's safe to use? If so, I will make a PR with the fix.

**Comment by james-elicx** [comment]
> In request headers there is `x-vercel-cache-tags` property exists, and I think it is okay to use it if original property is missing.

Ah yeah, I remember that header from when I first did the cache, and ended up going with the property instead because, well, it was on the object.

Sounds good to me, falling back to the header makes sense.
