### ISSUE TITLE
[🐛 Bug]: Defects when combining dynamic, parallel, and intercept routes

### ISSUE THREAD

**Issue by Karibash** [cloudflare/next-on-pages#558]
### next-on-pages environment related information

```
System:
	Platform: darwin
	Arch: x64
	Version: Darwin Kernel Version 22.6.0: Fri Sep 15 13:39:52 PDT 2023; root:xnu-8796.141.3.700.8~1/RELEASE_X86_64
	CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
	Memory: 32 GB
	Shell: /usr/local/bin/fish
Package Manager Used: npm (10.1.0)

Relevant Packages:
	@cloudflare/next-on-pages: 1.7.4
	vercel: N/A
	next: 14.0.3
```

### Description

When combining dynamic routes, parallel routes, and interceptor routes, the following issues occur:
- When accessing a page through an intra-page transition to a parallel route, the page itself can be displayed, but the path parameters are not being successfully retrieved.
- Reloading the page in a parallel route results in a 404 error, rendering the page inaccessible.

Perhaps there is a glitch in the [routes matcher for next-on-pages](https://github.com/cloudflare/next-on-pages/blob/main/packages/next-on-pages/templates/_worker.js/routes-matcher.ts), but it is so complex that I could not pinpoint what the problem is.

### Reproduction

https://github.com/Karibash/nextjs-dynamic-interception-parallel-routes

### Pages Deployment Method

Direct Upload (`wrangler pages publish` or the @cloudflare/pages-action GitHub Action)

### Would you like to help?

- [ ] Would you like to help fixing this bug?

**Comment by james-elicx** [comment]
> I have updated the version of @cloudflare/next-on-pages to 1.8.0, but the problem is still not resolved.

will look into it tonight

**Comment by james-elicx** [comment]
Hey there @Karibash, so sorry for the delay in getting to this and thank you very much for the reproduction :)

I have opened a PR which should fix these issues, and I would welcome you to try out the prerelease in https://github.com/cloudflare/next-on-pages/pull/564#issuecomment-1828683330

**Comment by Karibash** [comment]
Hi, @james-elicx 
Thanks for the fix!
I have tried it in the pre-release and can confirm that it works correctly.
I look forward to the release of this fix🥳
