### ISSUE TITLE
⚠️ Dead on arrival

### ISSUE THREAD

**Issue by shinebayar-g** [cloudflare/next-on-pages#57]
Removed my original comment since it was negative 😬 

TLDR; Vercel won't support Cloudflare officially. It's up to us Cloudflare community to maintain this library.
You may be interested in the following libraries. They're officially supported by their maintainers.

https://www.npmjs.com/package/solid-start-cloudflare-pages
https://www.npmjs.com/package/@astrojs/cloudflare
https://www.npmjs.com/package/@sveltejs/adapter-cloudflare
https://www.npmjs.com/package/@remix-run/cloudflare-pages

**Comment by DevOfManyThings** [comment]
@shinebayar-g This should be a discussion, not an issue.

Did you read the [announcement blog post](https://blog.cloudflare.com/next-on-pages/)? This is built on the [Build Output API](https://vercel.com/blog/build-output-api) which is supported by Vercel officially, and nothing around that is specific to Cloudflare or any other provider.

There is a valid point that you can make around this not having feature parity with Vercel, and whether you believe this will maintain long term support required to use a product in production (only time will tell how well cloudflare maintain this repo, as you said most other repos are primarily maintained by the framework themselves).

At least Cloudflare are taking the open source route for supporting this, so the community can raise PRs and expand on this unlike amplify where if you host your project there and want to use newer versions you are at the mercy of their internal team updating the tooling.

**Comment by re-thc** [comment]
> This should be a discussion, not an issue.

The base functionality actually isn't usable and even when you workaround those you can't deploy more than a few pages without exceeding the 1MB limit. I would say that's an actual issue.

> At least Cloudflare are taking the open source route for supporting this, so the community can raise PRs and expand on this unlike amplify where if you host your project there and want to use newer versions you are at the mercy of their internal team updating the tooling.

As a consumer / potential consumer of this freemium product I'd just want it to work - regardless of it being open source or not. The announcement blog says it "should work".

**Comment by shinebayar-g** [comment]
There is no discussion option enabled on this repo. Unless you forgot to mention Discord which isn't suitable place imo.

I forgot to mention this. From the experience with this repo, most people will think it's feature incomplete, something is broken, not supported on Cloudflare end not Vercel. And that's not a good look for Cloudflare imho. Wdyt?

**Comment by jdddog** [comment]
This project and Cloudflare Pages are definitely not ready to be used for a production Next.js project yet, there are just too many issues getting a project to work compared with doing the same in Vercel.

**Comment by newVincentFong** [comment]
@mrluc Thanks man
I was planning to do some modifications in the project to make it production
Yep, from Vercel to Pages
But the Middleware is still not working ?!
It seems I should come back here later :)
Till it's stable
BTW, what's your Next.js version, 12 or 13
They changed a lot in the Middleware though

**Comment by newVincentFong** [comment]
@mrluc Hi
The empty body in Middleware seems to be by design
Check this out:
https://nextjs.org/docs/messages/middleware-upgrade-guide#no-response-body

**Comment by mrluc** [comment]
> @mrluc Hi The empty body in Middleware seems to be by design Check this out: https://nextjs.org/docs/messages/middleware-upgrade-guide#no-response-body

Hi Vincent -- that's true, but not quite relevant.

Empty bodies in Middleware are by design, yes -- but this library immediately returns that empty response **to the client** without proceeding to the function! Which is definitely not by design. 😆 

Another way of saying it might be: this library has clearly not followed the upgrade guide you linked, since it treats the middleware's response, empty body and all, as the final response to send to the client.

**Comment by shinebayar-g** [comment]
Closing this issue. There's no point to spread negativity, we're all aware of situation.
