### ISSUE TITLE
[🐛 Bug]: Server actions don't work with `wrangler pages dev`

### ISSUE THREAD

**Issue by dario-piotrowicz** [cloudflare/next-on-pages#588]
### Description

Server actions do work fine when using next dev (with or without `next-dev`) and also in production, they do however not work locally when previewing the application with `wrangler pages dev` since there seem to be a discrepancy between the request's origin header which uses `localhost` and the `x-forwarded-host` header which uses `127.0.0.1`.

> [!tip]
> People can still use server actions in local mode if they go to the specific address the worker is running on
> eg. instead of going to `http://localhost:8788/server-actions/simple-kv-forms` they can go to `http://127.0.0.1:xxxxx/server-actions/simple-kv-forms` and there actions should works as expected

### Reproduction

https://github.com/dario-piotrowicz/next-on-pages-server-actions-test/tree/main/next-app

To reproduce the issue:
 - run `npm i`
 - run `npm run pages:build`
 - run `npm run pages:dev`
 - navigate to `http://localhost:8788/server-actions/simple-kv-forms`
 - try to set a new value using the button
 
 This should be the result:
![Screenshot 2023-12-12 at 22 50 40](https://github.com/cloudflare/next-on-pages/assets/61631103/50096ab7-bdde-4879-8dd5-f394fa0b1d0c)

### Additional Information

One solution could be to set, during local development a proper value to [`allowedOrigins`](https://nextjs.org/docs/app/api-reference/next-config-js/serverActions#allowedorigins), the issue is that the config doesn't accept wildcards, and the port which is part of `x-forwarded-host` changes each time, so I think this is not really a feasible solution

Another idea would be to apply some logic in the build process itself so that for server actions we try to convert all potentially localhost urls to a well defined format (as for example `localhost` without a port), I am not a big fan of dev changes that effect the production build output, but this would likely be such a small one that it might be acceptable

**Comment by dario-piotrowicz** [comment]
Seems like `allowedOrigins` is getting wildcards supports soon: https://github.com/vercel/next.js/pull/59428

**Comment by dario-piotrowicz** [comment]
I've labeled this issue as "blocked by external" as we need to check with the wrangler team if the `x-forwarded-host` can be applied on their side

**Comment by petebacondarwin** [comment]
PR up in Wrangler to resolve this problem. See https://github.com/cloudflare/workers-sdk/pull/4630
