### ISSUE TITLE
Documentation: Mention expected workflow for local builds and dev mode.

### ISSUE THREAD

**Issue by janpio** [cloudflare/next-on-pages#603]
https://developers.cloudflare.com/pages/framework-guides/deploy-a-nextjs-site/, the main documentation for this approach, does not mention how to locally use `build`, `dev`, `pages:build`, and `pages:dev` to develop. I think it would be very nice to add that.

Related question in Discord #next-on-pages: https://discord.com/channels/595317990191398933/1135899572141568050/1186764035497140335

**Comment by dario-piotrowicz** [comment]
Hi @janpio thanks a lot for the issue 🙂 

For now I've documented the recommended workflow here: https://github.com/cloudflare/next-on-pages/tree/main/internal-packages/next-dev#recommended-workflow (yeah not super discoverable, is it? 😓)

The `next-dev` submodule is however still experimental (we just need to finalize its API see #527), as soon as it is finalized I'll make sure to update the Cloudflare docs accordingly 🙂👍

**Comment by antsorin** [comment]
Thank you for the info, it helped me a lot.

Maybe it helps others who read this: while the `next-dev` submodule is still experimental, getting the `setupDevBidnings` can be made with:

```
const { setupDevBindings } = require('@cloudflare/next-on-pages/__experimental__next-dev');
```
instead of:
```
const { setupDevBindings } = require('@cloudflare/next-on-pages/next-dev');
```

**Comment by antsorin** [comment]
Also worth noting is that `setupDevBindings` supports additional options which I'm currently experimenting with, e.g.:

```
textBindings: {
    ENVIRONMENT: "development"
},
d1Databases: ['MY_D1'],
persist: "tmp/state/v3"
```

Full list of options are available [here](https://github.com/cloudflare/next-on-pages/blob/main/internal-packages/next-dev/src/index.ts).

**Comment by dario-piotrowicz** [comment]
I'm closing this issue since `setupDevBindings` has been documented in our docs: https://developers.cloudflare.com/pages/framework-guides/nextjs/deploy-a-nextjs-site/

(it is also getting updated with the newer `setupDevPlatform` function (which replaces `setupDevBindings`): https://github.com/cloudflare/cloudflare-docs/pull/13001)

Hopefully this is enough, @janpio and @antsorin please let me know if you think it isn't

(@antsorin in our docs we didn't include options to try not to be too verbose there... I hope that typescript and IDE intellisense/autocompletion should get people discover all the various options if need be, please let me know if you disagree 🙂)

**Comment by antsorin** [comment]
> (@antsorin in our docs we didn't include options to try not to be too verbose there... I hope that typescript and IDE intellisense/autocompletion should get people discover all the various options if need be, please let me know if you disagree 🙂)

I agree. 🙂

My comment also pointed out a small inconsistency related to the `persist` option, which needs to include the `v3` dir in `next.config.js`, but it is implied with the `--persist-to` CLI option.

```
// next.config.js
persist: "tmp/state/v3"
```

```
// CLI - will actually be persisted in tmp/state/v3
--persist-to=tmp/state"
```

It's not super important, I just wrote about it in case someone finds it helpful.

**Comment by dario-piotrowicz** [comment]
Thanks @antsorin 😄 

Yeah I fill like that small inconsistency can trip someone over 😓, thanks for the reminder...

It might be worth pointing out, I'll to include it in our docs 👍

**Comment by antsorin** [comment]
> Please let me know what you think 🙂

Looks great to me, thanks for adding the note!
