### ISSUE TITLE
[🐛 Bug]: bindings don't work in Server Actions

### ISSUE THREAD

**Issue by deadlynjdj** [cloudflare/next-on-pages#607]
### Description

when trying to use server actions in nextjs it can't find any process.env for the Cloudflare binds 

### Pages Deployment Method

None

### Would you like to help?

- [X] Would you like to help fixing this bug?

**Comment by dario-piotrowicz** [comment]
Hi @deadlynjdj I believe that server actions do get access to bindings as expected, I've experimented with that just last week as you can see here: https://github.com/dario-piotrowicz/next-on-pages-server-actions-test/tree/main/next-app

Everything works as expected there (except that server actions don't currently work in `wrangler pages dev`: #588)

So I am not sure what issue you're experiencing, could you please provide more details and potentially a minimal reproduction? 🙏 

PS: are you running the application via `next dev`?  if so, are you using the `setupDevBindings` from the [`next-dev` submodule](https://github.com/cloudflare/next-on-pages/tree/main/internal-packages/next-dev)?

**Comment by deadlynjdj** [comment]
thank you for the example just had some bad config files works fine now

i am running it using next dev with the compiler options

**Comment by deadlynjdj** [comment]
thank you for the example just had some bad config files works fine now

i am running it using next dev with the compiler options

**Comment by dario-piotrowicz** [comment]
Awesome, I'm glad it you got it working 😃👍
