### ISSUE TITLE
[🐛 Bug]: Cannot build when fetch data in layout

### ISSUE THREAD

**Issue by hoangvietfreelancer** [cloudflare/next-on-pages#629]
### next-on-pages environment related information

```
System:
        Platform: darwin
        Arch: arm64
        Version: Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:34 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T8103
        CPU: (8) arm64 Apple M1
        Memory: 16 GB
        Shell: /bin/zsh
Package Manager Used: npm (10.1.0) / yarn (4.0.2)

Relevant Packages:
        @cloudflare/next-on-pages: 1.8.5
        vercel: N/A
        next: 14.0.4
```

### Description

I'm current having _not-found error even there is no not-found.tsx page. This issue exist when I fetch data inside layout.tsx.

The reproduction step is just one commit inside repo provided below
```
⚡️ Warning: your app/not-found route might contain runtime logic, this is currently
⚡️ not supported by @cloudflare/next-on-pages, if that's actually the case please
⚡️ remove the runtime logic from your not-found route

⚡️ ERROR: Failed to produce a Cloudflare Pages build from the project.
⚡️ 
⚡️      The following routes were not configured to run with the Edge Runtime:
⚡️        - /_not-found
⚡️ 
⚡️      Please make sure that all your non-static routes export the following edge runtime route segment config:
⚡️        export const runtime = 'edge';
⚡️ 
⚡️      You can read more about the Edge Runtime on the Next.js documentation:
⚡️        https://nextjs.org/docs/app/building-your-application/rendering/edge-and-nodejs-runtimes
```

### Reproduction

https://github.com/hoangvietfreelancer/next-on-page-not-found-with-fetch-in-layout

### Pages Deployment Method

None

### Would you like to help?

- [ ] Would you like to help fixing this bug?

**Comment by dario-piotrowicz** [comment]
@hoangvietfreelancer sorry, I didn't have the chance to look into this issue

Since you're closing it I assume that you've solved it on your end?

**Comment by hoangvietfreelancer** [comment]
Oh look like I close it accidentally

**Comment by dario-piotrowicz** [comment]
Ah I see 🥲

Ok, I'm glad at least caught that 😄

Sorry for triaging this issue taking some time, I will look into this soon! 🙏

**Comment by hoangvietfreelancer** [comment]
Hi, is there any update on this bug? Or do you need any addition info?

**Comment by dario-piotrowicz** [comment]
Hi @hoangvietfreelancer, sorry I forgot to come back to this issue 🙇 

I've just had a look and I am pretty sure that this is only a matter of defining a `not-found` route that uses the edge runtime, as indicated here: https://developers.cloudflare.com/pages/framework-guides/nextjs/deploy-a-nextjs-site/#not-found

(and the fact that you do need a custom `not-found` route for this is unfortunately something out of our control)

Could you please try to add a custom not found route (that uses the `edge` runtime!) and let me know if that works for you? 🙂

**Comment by hoangvietfreelancer** [comment]
Thanks for the reply.

I had tried create custom `not-found` route before submit this issue but WITHOUT `edge` runtime so it doesn't work 😂

That was my mistake. Thank you again for telling me this!
