### ISSUE TITLE
[🐛 Bug]: setupDevBindings ignores D1 ID

### ISSUE THREAD

**Issue by markdembo** [cloudflare/next-on-pages#631]
### next-on-pages environment related information

System:
	Platform: darwin
	Arch: arm64
	Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:35 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T8103
	CPU: (8) arm64 Apple M1
	Memory: 8 GB
	Shell: /bin/zsh
Package Manager Used: npm (10.1.0)

Relevant Packages:
	@cloudflare/next-on-pages: 1.8.5
	vercel: 33.1.0
	next: 14.0.4

### Description

Before the 18.0.4 release,  D1 bindings were defined as:
```
    d1Databases: {
      BINDING_NAME: DB_ID,
      }
```

With the change of the API, they are defined as:

`BINDING_NAME: { type: "d1", databaseName: DB_NAME },`

Hence , DB_ID was replaced by DB_NAME to reference a D1 instance. Referencing D1 by ID though is still [supported and required](https://developers.cloudflare.com/workers/wrangler/configuration/#d1-databases) by Wrangler for Workers bindings.

This breaks my development flow as I share the local (and prod) D1 instances between my Pages project and Workers, which now reference two different D1 instances.

### Pages Deployment Method

Direct Upload (`wrangler pages publish` or the @cloudflare/pages-action GitHub Action)

### Would you like to help?

- [ ] Would you like to help fixing this bug?

**Comment by markdembo** [comment]
Solution as outlined in https://github.com/cloudflare/next-on-pages/issues/632 is correct.
Hence, the binding should be `{ type: "d1", databaseId: DB_ID }` instead of the current `{ type: "d1", databaseName: DB_NAME }`

**Comment by admah** [comment]
@markdembo we have talked on the Wrangler team about moving away from the requirement of "ID" in favor of "name" since most (if not all) of our dev platform resources do not allow duplicate names.

**Comment by dario-piotrowicz** [comment]
Thanks a lot @markdembo for the issue 🙏 

@admah thanks a lot for the insight 🙂 

I am not sure what we should be doing here... maybe we do need to temporarily change this and require the db id 🤔 

I'll have a quick check with the wrangler team and see if they'd be ok with that (especially since this would also effect `getBindingsProxy`)

**Comment by markdembo** [comment]
Not sure about the code under the hood, but it seems to be matching the ID under the hood right now, so I'd advocate to rename the field for now, and once we have moved full to DB name, we can introduce that change.

**Comment by dario-piotrowicz** [comment]
Hi @markdembo 🙂👋 

I'm amending this in #642 I hope that solves the issue for you, please let me know what you think 🙂

**Comment by markdembo** [comment]
See comment on PR - LGTM 💯
