### ISSUE TITLE
[🐛 Bug]: devBindings var adds extra quotes

### ISSUE THREAD

**Issue by markdembo** [cloudflare/next-on-pages#635]
### Description

Moving to the new dev bindings, when using a binding of type "var" i.e. env variables, the string gets wrapped in extra quotes.

Expected output: normal strings
Actual output: string wrapped in qoutes.

This breaks everything (auth etc.)

### Reproduction

```
// next.config.js
  setupDevBindings({
    bindings: {
      TEST_STRING: { type: "var", value: "Hello to Cloudflare" },
      ...
  })
```
  
```
  // page.tsx

export const runtime = "edge";

const env = process.env;

const Test = () => {
  const a = process.env.TEST_STRING;
  const b = "Hello to Cloudflare";
  console.log(a);
  console.log(b);
};
export default Test;
```

Run `npm run dev`
Open page
Console output:

```
"Hello to Cloudflare"
Hello to Cloudflare
```

### Pages Deployment Method

None

### Additional Information

As a(n ugly) workaround I use `.replaceAll('"', "")` for the time being when accessing an env var.

### Would you like to help?

- [ ] Would you like to help fixing this bug?

**Comment by dario-piotrowicz** [comment]
@markdembo thanks a lot for the issue 🙂 

Sorry it's my bad, I added an incorrect `JSON.stringify` call to the code 🤦

I'm fixing this in #637 🙂👍
