### ISSUE TITLE
Need assistance to deploy my nx monorepo next js project on cloudflare pages

### ISSUE THREAD

**Issue by alihussain575** [cloudflare/next-on-pages#65]
I am using  `@nrwl/next`  to create the app and now that it is working i want to deploy it. In nx dosn't adds package.json file in the project

**Comment by jondotblack** [comment]
Cloudflare pages doesn't support monorepos - https://developers.cloudflare.com/pages/platform/known-issues/

**Comment by GregBrimble** [comment]
We're thinking about mono-repo support in the Pages product in general, and that'll happen independently of this next-on-pages project. Stay tuned to our [blog](https://blog.cloudflare.com/) and [Discord](https://discord.gg/cloudflaredev) for any announcements!

**Comment by ejoo** [comment]
@GregBrimble can we build project and cannot copy the dist folder? Because the dist folder is unique btw?

**Comment by sam-goodwin** [comment]
Is monorepo support still not supported? Seems like a big problem. I am getting hit by this and it's turning out to be a terrible experience.

**Comment by dario-piotrowicz** [comment]
@sam-goodwin no, there's no support for it yet 😢 (and I'm sorry to hear that t's a terrible experience 😓)

It is not the same but we do also have github actions that can be used to deploy pages applications from github repos: https://github.com/cloudflare/wrangler-action

**Comment by n1rjal** [comment]
Reopening the issue. Any update on this ?

**Comment by kunal-singh** [comment]
Looking forward to this. Using vercel for now but I have most of my infra on AWS.

**Comment by at15** [comment]
Mono repo works https://developers.cloudflare.com/pages/configuration/monorepos/ I only tried pnpm one created by shadcn https://ui.shadcn.com/docs/monorepo For nx there seems to be a plugin but I haven't tried that https://www.npmjs.com/package/@naxodev/nx-cloudflare
