### ISSUE TITLE
[🐛 Bug]: `Error: failed to retrieve the Cloudflare request context`

### ISSUE THREAD

**Issue by lamualfa** [cloudflare/next-on-pages#680]
### next-on-pages environment related information

```bash
System:
        Platform: linux
        Arch: x64
        Version: #17-Ubuntu SMP PREEMPT_DYNAMIC Thu Jan 11 14:01:59 UTC 2024
        CPU: (16) x64 13th Gen Intel(R) Core(TM) i7-13620H
        Memory: 15 GB
        Shell: /usr/bin/fish
Package Manager Used: pnpm (8.15.3)

Relevant Packages:
        @cloudflare/next-on-pages: 1.9.0
        vercel: N/A
        next: 14.1.1-canary.70
```

### Description

The `getRequestContext` function throw an error when it called on the [server actions](https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions-and-mutations#client-components).

### Reproduction

**command**
```bash
next dev
```

**`app/sign-in/actions.ts`**
```ts
'use server'

import { getRequestContext } from '@cloudflare/next-on-pages'

export async function signIn() {
  const { env } = getRequestContext() // throw an error
  const { dbCache } = env
}
```

**`next.config.mjs`**
```js
import { setupDevPlatform } from '@cloudflare/next-on-pages/next-dev'

/** @type {import('next').NextConfig} */
const nextConfig = {}
export default nextConfig

const isDev = process.env.NODE_ENV === 'development'
if (isDev) {
  await setupDevPlatform()
}
```

**`wrangler.toml`**
```toml
[[kv_namespaces]]
id = "<redacted>"
binding = "dbCache"
```

### Pages Deployment Method

None

### Would you like to help?

- [ ] Would you like to help fixing this bug?

**Comment by OpenSource03** [comment]
Seems like you forgot to export runtime as 'edge':

https://nextjs.org/docs/app/building-your-application/rendering/edge-and-nodejs-runtimes#segment-runtime-option

**Comment by lamualfa** [comment]
> Seems like you forgot to export runtime as 'edge':
> 
> https://nextjs.org/docs/app/building-your-application/rendering/edge-and-nodejs-runtimes#segment-runtime-option

Next.js server actions doesn't have `export const runtime = "edge"` options. Should I add it on the page that use the related actions?

**Comment by lamualfa** [comment]
Ok it works. We have to add `export const runtime = "edge"` to the `page.tsx` that consume the actions.

Thanks @OpenSource03
