### ISSUE TITLE
[⚡ Feature]: Allow a way to use local node_modules folder when compiling

### ISSUE THREAD

**Issue by coratype** [cloudflare/next-on-pages#698]
### Description

I would like a way to use the local node_modules folder when running npx @cloudflare/next-on-pages instead of getting the packages from the npm registry for testing purposes, unless there's a documented way to do this

### Would you like to help?

- [ ] Would you like to help implement this feature?

**Comment by dario-piotrowicz** [comment]
Hi @coratype 🙂

Thanks for the issue 😄

Could you clarify what you mean with the above? what files are you getting from the npm registry? are they installed in your project?

Are you referring to this?
![Screenshot 2024-03-10 at 23 41 05](https://github.com/cloudflare/next-on-pages/assets/61631103/9a84c164-7ede-4093-8f72-271dd7c882b3)

**Comment by coratype** [comment]
Yes, I assumed when it's installing dependencies it's gathering them from the npm registry not from the local node_modules folder in my project? I would like to be able to run use a modified version of a library I have without having to fork it

**Comment by dario-piotrowicz** [comment]
It is simply running an `npm install` (or your package manager's equivalent), so no, I'm pretty sure that it is not gathering the packages from the npm registry but using the local copies.

(From my screenshot above you can see `up to date in 266ms`, this shows that no package needed updating and thus all the local ones have been used).

You should be able to link any local copy of a library to your project or use patches to patch the dependencies and it should all work as you'd expect it to 🙂

**Comment by coratype** [comment]
Oh okay thank you for clarifying

**Comment by dario-piotrowicz** [comment]
@coratype no problem 🙂 

I'm closing this issue then (as there isn't much to do on our side), I hope that's fine by you

Anyways please give it a try and feel free to reopen this issue (or open a new one) if you have issues 🙂
