### ISSUE TITLE
[🐛 Bug]: iron-session error 405 method-not-allow

### ISSUE THREAD

**Issue by TimKieu** [cloudflare/next-on-pages#703]
### next-on-pages environment related information

1. Local PC: Macos Apple silicon M2/M1
Nodejs 18.19
wrangler 3.9.0
2. Deployment: CloudFlare Pages

### Description

I am building Nextjs 14 app on Cloudflare Pages with iron-session as a Auth option.
The local webapp builds and runs well with next-on-pages.
But running on CloudFlare Pages gets the 405 error. 
I also try to debug with real-time log but, it shows nothing.
Please help for this simple code in [Next-iron-session](https://github.com/clickandcure/next-cookie-session)

### Reproduction

1. Get the sample code
2. Fill env vars
3. Build and deploy to CF Pages by github or wrangler
4. Test login with account: john/123

### Pages Deployment Method

None

### Would you like to help?

- [ ] Would you like to help fixing this bug?

**Comment by TimKieu** [comment]
@all Please kindly share your experience on Auth options with Next-on-pages apps:
1. Next-Auth v5 with backend workers (I also got error 405)
2. Iron-session
3. Others

**Comment by tarikrazine** [comment]
the only solution i found for this issue is to add export const runtime = "edge" to the root layout

**Comment by abooo96** [comment]
I have the same issue today. If your app uses iron-session, your cloudflare worker deployment will complain. What does "closed as not planned" even mean? I am having struggles deploying my app because of this. Any ideas anyone?
