### ISSUE TITLE
[🐛 Bug]: Error: The script will never generate a response.

### ISSUE THREAD

**Issue by rakibatomnixima** [cloudflare/next-on-pages#711]
### next-on-pages environment related information

System:
        Platform: darwin
        Arch: arm64
        Version: Darwin Kernel Version 23.3.0: Wed Dec 20 21:30:27 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T8103
        CPU: (8) arm64 Apple M1
        Memory: 16 GB
        Shell: /bin/zsh
Package Manager Used: npm (10.5.0)

Relevant Packages:
        @cloudflare/next-on-pages: 1.10.0
        vercel: N/A
        next: N/A

### Description

I'm getting ```Error: The script will never generate a response.``` on my deployed pages project. The build goes without and error and deploy is successful. But the above error is displayed on the website. 

The app also works when I use the wrangler dev server like this ```wrangler pages dev --persist-to=migrations  --compatibility-date=2024-01-17 --compatibility-flag=nodejs_compat -- next dev```. 

But when doing ```wrangler pages dev .vercel/output/static --compatibility-date=2024-01-17 --compatibility-flag=nodejs_compat```, this error shows up on the console ```A hanging Promise was canceled. This happens when the worker runtime is waiting for a Promise from JavaScript to resolve, but has detected that the Promise cannot possibly ever resolve because all code and events related to the Promise's I/O context have already finished.```.

Update: The issue happens on Next.js canary version and not present in v14.1.3

### Reproduction

Setup a new project with latest Next.js Canary version

### Pages Deployment Method

Pages CI (GitHub/GitLab integration)

### Pages Deployment ID

87e157c0-7d2c-4f05-bc8d-0723e0f0dd37

### Would you like to help?

- [ ] Would you like to help fixing this bug?

**Comment by makepanic** [comment]
Seeing the same issue with the newly released [next@14.1.4](https://github.com/vercel/next.js/releases/tag/v14.1.4).

**Comment by dario-piotrowicz** [comment]
@rakibatomnixima thanks a lot for the issue 🙂

As @makepanic mentioned this has been introduced in the latest Next.js versions

#720 should address this, if you can, please to try the PR's [prerelease](https://github.com/cloudflare/next-on-pages/pull/720#issuecomment-2015422109) and let me know if it solves the issue for you 🙂🙏

**Comment by brianfryer** [comment]
This issue is not resolved 😢

**Comment by ItsWendell** [comment]
@dario-piotrowicz I'm also experiencing this, especially with calls to `?_rsc=xxx` through the middleware, I'm on the latest version of next-on-pages and next.js as of to date. It seems to successfully complete the middleware but it somehow, and give a response when I check Chrome Dev Tools.

E.g. Chrome Dev Tools says: Connection closed.

The network tab shows that a connection to e.g.: https://my-web-site.com/blog/item?_rsc=13mjf that it returned a 200 status code, but in the cloudflare logs it says: The script will never generate a response, while it does seem to complete the middleware run. It also happens _very_ sporadically and only on navigation from a page (e.g. blog overview) to another page, e.g. direct visits do always work.


Can we re-open this issue or should I create a new one? Also not sure how to create reproducible for this but I might give it a try

**Comment by simmbiote** [comment]
I got past this by upgrading to Nextjs 14.2.3

**Comment by CashmereNahida** [comment]
I resolved the issue by upgrading nextjs, cloudflare/next-on-pages, and cloudflare/workers-types to their latest versions

**Comment by alejomendoza** [comment]
Still happening I think [Next Cloudflare](https://community.cloudflare.com/t/the-script-will-never-generate-a-response-in-generatemetadata-with-fetch-nextjs14/658974)

**Comment by alejomendoza** [comment]
> I resolved the issue by upgrading nextjs, cloudflare/next-on-pages, and cloudflare/workers-types to their latest versions

This didn't work for me, could you please comment with your exact versions @CashmereNahida Thanks!

**Comment by CashmereNahida** [comment]
> > I resolved the issue by upgrading nextjs, cloudflare/next-on-pages, and cloudflare/workers-types to their latest versions
> 
> This didn't work for me, could you please comment with your exact versions @CashmereNahida Thanks!

"next": "^14.2.3",
"@cloudflare/next-on-pages": "^1.11.3"
These are the current versions. The previous versions were "next": "^14.1.0", "@cloudflare/next-on-pages": "^1.11.0". After upgrading, the issue was resolved, but I'm not exactly sure what caused the problem initially.

**Comment by alejomendoza** [comment]
I'm on those two latest versions and I'm still getting it on dynamic routes like this [page](https://github.com/skyhitz/skyhitz-tailwind/blob/cloudflare/apps/appdir/app/dashboard/beat/%5Bid%5D/page.tsx)

**Comment by ItsWendell** [comment]
This might help some people, but in my specific case, I was using Storyblok. Storyblok's client initializes it's client, and some other metadata / components in the global scope. I think what might've happened in some cases is that these global variables got potentially shared in between requests, and / or would cause hanging promises, both of which Cloudflare Workers doesn't allow / like.

As soon as I started forcefully re-initializing Storyblok for every API call we did to it seemed to have solved "The script will never generate a response." and similar issues.

**Comment by alejomendoza** [comment]
Took all the global variables out and still bump into this issue for some routes, what is strange is that I also get it for static metadata exports like this one:
```
export const metadata: Metadata = {

```

**Comment by simmbiote** [comment]
I'm getting this without using the metadata feature - any page that's using edge (on app router) or experimental edge (pages router) triggers this error. 

```
Error: The script will never generate a response.
    at async Object.fetch (file:///Users/{user}/.npm/_npx/afd351970c453bac/node_modules/miniflare/dist/src/workers/core/entry.worker.js:1024:22)
```

**Comment by simmbiote** [comment]
I seem to have narrowed this down to 2 pieces of custom configuration in the `next.config.js` file.
With either or both of these enabled, the error "Error: The script will never generate a response." is shown.

1) TerserPlugin for Minifaction
In this case using the `TerserPlugin`, which comes built in with webpack 5.

```
const TerserPlugin = require('terser-webpack-plugin');
...
...
const nextConfig = {
  webpack(config) {
    config.optimization = {
      minimize: true,
    minimizer: [new TerserPlugin()],
    };
```

2) Babel Link Helper

```
/** @type {import('next').NextConfig} */
const babelLinkHelper = function ({ types: t }) {
  return {
    name: 'nextjs-link-prefetch-default',
    visitor: {
      JSXOpeningElement({ node }) {
        if (node.name.name === 'Link') {
          const defaultValue = false;
          const prefetchAttributes = node.attributes.filter(
            (attribute) => attribute.type === 'JSXAttribute' && attribute.name.name === 'prefetch'
          );
          if (prefetchAttributes.length <= 0) {
            node.attributes.push(t.jSXAttribute(t.jSXIdentifier('prefetch'), t.JSXExpressionContainer(t.booleanLiteral(defaultValue))));
          }
        }
      },
    },
  };
};


...

const nextConfig = {
  webpack(config) {
  plugins: [babelLinkHelper],
...
```

**Comment by alejomendoza** [comment]
I'm still getting this, should this issue be reopened?

**Comment by dario-piotrowicz** [comment]
@alejomendoza sorry somehow I missed the thread that started after the issue got closed 😓 (darn Github notifications 😅)
(thanks for pinging me and making me have a look! 🙏)

The original issue was investigated and solved, now the issue is that `Error: The script will never generate a response.` is a standard workerd error that can happen for an infinite number of reasons (you can see it almost as an unknown error), so reopening this issue and collecting all possible situations that trigger such error message seems quite unhelpful to me.

So if possible I really appreciate it if you (and/or @simmbiote, @ItsWendell, @brianfryer) could open a new issue describing the problem as clearly as possible with as much as details as you can, ideally also including a minimal reproduction 🙏 

I'll have a look at it as soon as I can 🙇

**Comment by dario-piotrowicz** [comment]
(PS: I've updated the issue's title so that it doesn't specifically call out the error message and so that hopefully in the future people, when encountering this error message, don't add comments to this thread but open new issues instead)

**Comment by alejomendoza** [comment]
> @alejomendoza sorry somehow I missed the thread that started after the issue got closed 😓 (darn Github notifications 😅) (thanks for pinging me and making me have a look! 🙏)
> 
> The original issue was investigated and solved, now the issue is that `Error: The script will never generate a response.` is a standard workerd error that can happen for an infinite number of reasons (you can see it almost as an unknown error), so reopening this issue and collecting all possible situations that trigger such error message seems quite unhelpful to me.
> 
> So if possible I really appreciate it if you (and/or @simmbiote, @ItsWendell, @brianfryer) could open a new issue describing the problem as clearly as possible with as much as details as you can, ideally also including a minimal reproduction 🙏
> 
> I'll have a look at it as soon as I can 🙇

Thanks so much for your reply @dario-piotrowicz here is the new issue I opened https://github.com/cloudflare/next-on-pages/issues/802
