### ISSUE TITLE
All pages streaming / no static?

### ISSUE THREAD

**Issue by sgoodluck** [cloudflare/next-on-pages#73]
I've noticed that when trying to use this to create a Nextjs 13 application that all pages are being built as streaming pages when using the edge runtime. 

Even incredibly simple pages that should be static. 

A few questions:

- Is this by design?

- Is it on roadmap to support caching options in the future? 

- For a very simple page, since it is presumably ISR, is it effectively static/delivered static anyway?

**Comment by mikecentric** [comment]
Depends where you create the page. 

If it's in the /app directory it's always SSR if it's in /pages it will be the same as next 12 like you mention.

**Comment by sgoodluck** [comment]
I'm not having this experience. 

- Opting out of the app directory 
- Using Next 13.1.6 

If I set the entire project to use experimental-edge, all pages are streaming 
If I set only relevant pages to use experimental-edge, I get 404s when deployed to Cloudflare 

If you have a setup working where you use edge but have static pages, would you mind sharing it?

**Comment by sgoodluck** [comment]
![Screen Shot 2023-02-14 at 11 27 51 AM](https://user-images.githubusercontent.com/106334996/218797935-a5f9757a-76e2-4a85-b9a4-eab6200eae6f.png)

So toggling experimental edge seems to turn that very simple about page into a streamed page
