### ISSUE TITLE
[⚡ Feature]: Please add support for nextjs 14.2

### ISSUE THREAD

**Issue by pandas9** [cloudflare/next-on-pages#748]
### Description

There is a massive bug with nextjs memory leak and builds are using a lot unnecessary memory, it got a lot better with new nextjs version

If you deploy any nextjs version above 14.1.0 on cloudflares pages functions do not work anymore and return 404 not found, thank you!

### Would you like to help?

- [ ] Would you like to help implement this feature?

**Comment by pandas9** [comment]
> May we know what error did you ran into? I have my app on the latest Next.js version and it works great!

server actions return 404 not found response for any nextjs version above 14.1.0

**Comment by pandas9** [comment]
not sure what they did in nextjs but 14.1.0 RAM usage of M1 macbook of 16GB during build time goes all the way to 9GB and nextjs 14.2.2 doesn't use more than 2GB of RAM

cloudflare pages during build runs out of the memory, was able to deploy it with adjusting the code and making it more dynamic but the app itself is not that complicated

**Comment by NavOrange** [comment]
> > May we know what error did you ran into? I have my app on the latest Next.js version and it works great!
> 
> server actions return 404 not found response for any nextjs version above 14.1.0

I have the same problem, but it works normally in next@14.2.1, and does not work in 14.2.2.

**Comment by dazweeja** [comment]
I can confirm that server actions work in next@14.2.1 but not 14.2.2. This breaks next-auth on my site so I would guess that it's affecting other packages too.

Minimal repo:
https://github.com/dazweeja/cloudflare_nextjs-14-2-2-test

For "npx wrangler pages dev .vercel/output/static --compatibility-flag=nodejs_compat" on  next@14.2.2:
POST / 404 Not Found

For "npm run dev":
POST / 200

For "npx wrangler pages dev .vercel/output/static --compatibility-flag=nodejs_compat" on  next@14.2.1:
POST / 200 OK

**Comment by rakibatomnixima** [comment]
I am also encountering this 404 error on server actions using next js version 14.2.2

**Comment by cheraff** [comment]
Same issue

**Comment by tuphan-dn** [comment]
Confirm that the weird 404 Not Found occurred on next@14.2.2

**Comment by jenslys** [comment]
Newest release seems to fix my server actions not working on 14.2.2, but **none** of my api routes seems to work.

**Comment by pandas9** [comment]
next-on-pages updated to latest nextjs version, thanks team

**Comment by cosmicproc** [comment]
I am still experiencing the 404 Not Found issue with server actions in NextJS version 14.2.3 and next-on-pages version 1.11.1

**Comment by Gbuomprisco** [comment]
Same issue here, on 14.2.3, 404s on server actions

**Comment by orl0pl** [comment]
Just downgrade next to 14.2.1
`npm i next@14.2.1`

**Comment by Jdruwe** [comment]
I am about to start a new project on 14.2.3, is this version still causing issues?
