### ISSUE TITLE
ESbuild warning with NextJS 13.1.6 (fix: rollback to 13.1.5)

### ISSUE THREAD

**Issue by mountainash** [cloudflare/next-on-pages#75]
Using `"next": "^13.1.6",` in the `package.json` (which is what `npx create-next-app@latest` as per the `README.md` of this project suggests) causes the following error when running `npx @cloudflare/next-on-pages --watch`. Can I suggest that this project pins dependencies until they are tested?

▶️ Rolling back to `v13.1.5` of **NextJS** allows it to build without errors.

### Sample of the error:

```
⚡️ Completed 'npx vercel build'.
⚡️
▲ [WARNING] Using direct eval with a bundler is not recommended and may cause problems [direct-eval]

    ../../../tmp/tm8non2pc5/index.func.js:304:79122:
      304 │ ...ThisContext=function(){return eval(this.code)},Script.prototype....
          ╵                                  ~~~~

  You can read more about direct eval and bundling here:
  https://esbuild.github.io/link/direct-eval
```

If you deploy this to Pages, it results in an "Internal Sever Error" being served (and the "Real-time Logs [Beta] giving an "✅ Ok" for the status 😿).

**Comment by dario-piotrowicz** [comment]
Hi @mountainash, I've been trying to reproduce this but I haven't had much luck, could you please provide some reproduction steps/code? :pray: 

(also I would  suggest you to try with the latest Next.js version, I wonder if it is still an issue)

Also, you said that there is an error but the one you're providing is a warning, is that actually making your compilation fail?

___

> Can I suggest that this project pins dependencies until they are tested?

We've recently updated our README, it doesn't actually pin the Next.js version but it says which one is the last version that we've tested (`13.2.4`) , we might do something better at some point but we'll probably want to get a better understanding of what we support and what not first
___

PS: for context I think that the eval comes from this [vm-browserify/index.js](
https://github.com/vercel/next.js/blob/400ccf7b1c802c94127d8d8e0d5e9bdf9aab270c/packages/next/src/compiled/vm-browserify/index.js)
