### ISSUE TITLE
[🐛 Bug]: Using KV for next cache breaks time revalidation

### ISSUE THREAD

**Issue by TimothyKrell** [cloudflare/next-on-pages#757]
### Description

When binding KV to `__NEXT_ON_PAGES__KV_SUSPENSE_CACHE` for my app, using `unstable_cache(fn, ['tag'], { revalidate: 60 })` does not update the cache after 60 seconds. This works with the default cache. I can manually revalidate by tag, however. Is this a known issue? I can make a reproduction if that's helpful, but to test this, it's literally just cache and set time revalidation then see if it updates.

### Pages Deployment Method

Pages CI (GitHub/GitLab integration)

### Pages Deployment ID

06c430b2-3f3f-4657-8ce6-30306c132419

### Would you like to help?

- [X] Would you like to help fixing this bug?

**Comment by dario-piotrowicz** [comment]
Hi @TimothyKrell 🙂👋 

Thanks a bunch for the issue 🙂 , anyways no, this is not a known issue

This is the KV cache implementation: https://github.com/cloudflare/next-on-pages/blob/main/packages/next-on-pages/templates/cache/kv.ts as you can see it is rather simple very similar to the default cache implementation: https://github.com/cloudflare/next-on-pages/blob/main/packages/next-on-pages/templates/cache/cache-api.ts

So I am not sure why only one would not work, my best guess is that the workers cache api handles for us something that we'd manually need to do in KVs? 🤔 

Anyways I'd really appreciate a minimal reproduction as I think would be super helpful 🙂🙏
