### ISSUE TITLE
Use AsyncLocalStorage to support newer versions of `next`

### ISSUE THREAD

**Issue by GregBrimble** [cloudflare/next-on-pages#76]
`next` has started to rely on AsyncLocalStorage being available in the global scope. We need to add the requirement for the new `nodejs_compat` Compatibility Flag and add this to our Worker template.

**Comment by GregBrimble** [comment]
While we're here, we can also swap out the hack of setting `globalThis.process.env` to the incoming `env` object from the fetch handler and instead use AsyncLocalStorage to do this correctly scoped to the current request.

**Comment by AndrewIngram** [comment]
Should setting the `nodejs_compat` flag in my pages project be enough to make this work? Because I've just added it and it didn't seem to solve the `"Error: Invariant: AsyncLocalStorage accessed in runtime where it is not available"` error I see in the logs.

**Comment by dario-piotrowicz** [comment]
This should have been solved by #115 🙂
