### ISSUE TITLE
[🐛 Bug]: next@14.2.0 breaks mutating server actions on Pages deployment.

### ISSUE THREAD

**Issue by varna** [cloudflare/next-on-pages#762]
### next-on-pages environment related information

System:
        Platform: darwin
        Arch: arm64
        Version: Darwin Kernel Version 23.3.0: Wed Dec 20 21:30:27 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T8103
        CPU: (8) arm64 Apple M1
        Memory: 8 GB
        Shell: /bin/zsh
Package Manager Used: npm (10.5.0)

Relevant Packages:
        @cloudflare/next-on-pages: 1.11.1
        vercel: 34.1.3
        next: 14.2.0

### Description

Server Actions, used as mutations in Client Components stop working on CF Pages deployments from updating next@^14.2.0 package.

```ts
// actionts.ts
"use server";

import { revalidatePath } from "next/cache";

/**
 * Used in Server component (page) to query data from server
 * Works in all versions of next
 */
export async function queryServerAction() {
	console.log("logging: queryServerAction");
	return `query server action response: ${new Date().toISOString()}`;
}

/**
 * Used in Client component to mutate data on server.
 * Works in next@14.1.4
 * Fails in next@14.2.0 and later.
 * 	by returning 404 html page
 */
export async function mutationServerAction([input, duput]: [string, string?]) {
	console.log("logging: mutationServerAction", input, duput);
	revalidatePath("/");
	return `mutation server action response: ${input}`;
}
```
```tsx
// my-button.tsx
"use client";

import { mutationServerAction } from "./actions";

export default function MyButton() {
	return (
		<button
			type="button"
			onClick={async () => {
				const response = await mutationServerAction(["a", "b"]);
			}}
		>
			button
		</button>
	);
}
```

### Reproduction

```bash
got clone https://github.com/varna/server-action-mutation-repro
cd server-action-mutation-repro

# add GitHub Project to Cloudflare Pages and Vercel.
# wait for deploy to complete
# click on Client Component button
# mutation action on Vercel works, but fails on CF Pages

ni next@14.1.4

# wait for deploy to complete
# click on Client Component button
# mutation action on Vercel works, just as on CF Pages

ni next@14.2.0

# wait for deploy to complete
# click on Client Component button
# mutation action on Vercel works, but fails on CF Pages
```

### Pages Deployment Method

Pages CI (GitHub/GitLab integration)

### Would you like to help?

- [X] Would you like to help fixing this bug?

**Comment by sunneydev** [comment]
facing same issue, after investigation i conclude it has something to do with redirects, which makes me think `revalidePath` is also a redirect in some way. basically server actions using redirects messes things up.

**Comment by dario-piotrowicz** [comment]
Hi @varna 🙂👋 

Thanks a bunch for the issue, and for the minimal reproduction! that's always very helpful! ❤️ 

Speaking of which... I did try your minimal reproduction with both Next.js 14.1.4 and 14.2.0 and I didn't see the issue in either

I made this deployment using Next.js 14.2.0: https://ddfb7c18.server-action-mutation-repro.pages.dev/
and it seems to be working as expected (I click on [Go to issues](https://ddfb7c18.server-action-mutation-repro.pages.dev/issues) then I type something in the input field and click `click to run mutation` and see the response text displayed)

Am I missing something? 😕

**Comment by varna** [comment]
Hi @dario-piotrowicz 

> Am I missing something? 😕
Nope. It just works right now. The issue is gone. 🤔

@cloudflare/next-on-pages@1.11.2 was released so I tried forcing `npx @cloudflare/next-on-pages@1.11.1` in settings instead of `npx @cloudflare/next-on-pages@1`. It still works properly. I can't force this repro to repro the bug anymore. 🫠

Thanks for caring!

**Comment by dario-piotrowicz** [comment]
Yeah I did try with next-on-pages `1.11.1` too 😅 🤷 

Well.... I don't know.... hopefully it was just a random one time thing 🤞
