### ISSUE TITLE
npx @cloudflare/next-on-pages error during build

### ISSUE THREAD

**Issue by kvnang** [cloudflare/next-on-pages#8]
I received the following errors during `npx @cloudflare/next-on-pages` build step, after `Completed 'npx vercel build'`. These are repeated for all page files:

```
    {
      detail: undefined,
      id: '',
      location: {
        column: 8,
        file: '../../../tmp/ge1zkztc959/about.func.js',
        length: 2,
        line: 13617,
        lineText: '    true=>{(!C||s)&&(i&&clearTimeout(i),i=setTimeout(()=>{n.done(!0)},t))},"routeChangeError");return w(`',
        namespace: '',
        suggestion: ';'
      },
      notes: [],
      pluginName: '',
      text: 'Expected ";" but found "=>"'
    },
```

Though these errors seem to be ignored with Node 14, Node 16 would fail the build entirely. Happy to include the entire log, though it's mostly just a repeat of the above for all the pages.

And, I'm not sure if this is related, but all of the `getServerSideProps` pages return 404, while the static pages work as expected.

This project runs `next@12.3.1`, `react@18.2.0`.

Thank you!

**Comment by kvnang** [comment]
When testing locally, removing the following lines from `@cloudflare/next-on-pages` eliminates the error:
https://github.com/cloudflare/next-on-pages/blob/main/src/index.ts#L224-L228

I'm not 100% what these do, but investigating further ...

**Comment by tj-kev** [comment]
This fixed the issue for me as well. Thanks.

**Comment by emilyobaditch** [comment]
> When testing locally, removing the following lines from `@cloudflare/next-on-pages` eliminates the error:
> 
> https://github.com/cloudflare/next-on-pages/blob/4858ac4b0597327408444af7d00657c91db17fe4/src/index.ts#L224-L228
> 
> If the goal of these lines is to make `configurable: true`, then I believe the regex replace should be like this:
> 
> ```js
> contents = contents.replace(
>   /(Object.defineProperty\(globalThis,\s*"__import_unsupported",\s*{[\s\S]*?configurable:\s*)([^,}]*)(.*}\s*\))/gm,
>   "$1true$3"
> );
> ```
> 
> Happy to help with PR if this is the case.

I am running into this issue as well.  Where did you actually make this change? How are you patching something in a dependency?

**Comment by kvnang** [comment]
> I am running into this issue as well. Where did you actually make this change? How are you patching something in a dependency?

Yes. To be exact, I use npm module `patch-package` that allows me to edit the local `node_modules/@cloudflare/next-on-pages` package directly and have that change carry over to Cloudflare Pages build.

So, I installed both `patch-package` and `@cloudflare/next-on-pages`

```
npm i --save-dev patch-package @cloudflare/next-on-pages
```

And then, made the change on the `node_modules` folder. Save the patch by running

```
npx patch-package @cloudflare/next-on-pages
```

and commit the generated `patch` directory. Then I needed to add two new scripts to `package.json` to ensure that changes are applied on Cloudflare Pages build step:

```json
"scripts": {
    "cloudflare:build": "node node_modules/@cloudflare/next-on-pages/bin/index.js --experimental-minify",
    "postinstall": "patch-package"
}
```

Finally, instead of using `npx @cloudflare/next-on-pages` for the build command, use `npm run cloudflare:build` instead. That ensures that you're using the local (patched) package.

**Comment by WalshyDev** [comment]
Would love a PR @kvnang !

**Comment by aidenwallis** [comment]
Cut a PR to this: https://github.com/cloudflare/next-on-pages/pull/16

**Comment by Danny-Duck** [comment]
>Finally, instead of using npx @cloudflare/next-on-pages for the build command, use npm run cloudflare:build instead. That ensures that you're using the local (patched) package.

If you're trying to get this patch to work on Pages, don't forget to "patch" the newly install packages. I added `yarn run patch-package && yarn run cloudflare:build` to my build settings on Cloudflare
