### ISSUE TITLE
How to get environment variables

### ISSUE THREAD

**Issue by Meagsy** [cloudflare/next-on-pages#803]
I've tried searching this answer everywhere but to no avail. 

I have an app router next.js site on Github and linked it to Cloudflare Pages and not using C3/Wrangler bit Git Integration. I set up secret environment variables in cloudflare dashboard and try to access them in a page route like this process.env.CONTENTFUL_ACCESS_TOKEN but everytime I try to build  it, it has this error  TypeError: Expected parameter accessToken (which is for the createClient function from contentful). 

This is supposed to be a static page, just need to fetch the content from contentful and get it to be built. 

How do I access environment variables properly?

Page begins like this:
`export default async function Page({ params }: { params: { slug: string } }) {`

edit: can you not use force-static on cloudflare pages? After removing that and forcing edge runtime, seems I can get the environment variables

**Comment by dario-piotrowicz** [comment]
Hi @Meagsy 🙂👋 

I might be wrong but I feel like here you're confusing Cloudflare env variables with Next.js env variables.

Cloudflare env variables are the ones you set in the dashboard (and in `wrangler.toml` files) and are made available for your application at runtime if you're using the edge runtime.
Next.js env variables are variables that you can use in your next.js application, some can be inlined/bundled during the build process too (or, like in this case, used during SSG).

In your case I think to build your static page you need to use Next.js env variables so that the Next.js build process can use them during the SSG process, so I'd suggest you to create a `.env` file with the `CONTENTFUL_ACCESS_TOKEN` variable and try again.
If that token is going to be needed at runtime too then you'll need to set it in the Cloudflare dashboard as well.

I hope the above helps! please let me know 🙏

**Comment by Meagsy** [comment]
> Hi @Meagsy 🙂👋
> 
> I might be wrong but I feel like here you're confusing Cloudflare env variables with Next.js env variables.
> 
> Cloudflare env variables are the ones you set in the dashboard (and in `wrangler.toml` files) and are made available for your application at runtime if you're using the edge runtime. Next.js env variables are variables that you can use in your next.js application, some can be inlined/bundled during the build process too (or, like in this case, used during SSG).
> 
> In your case I think to build your static page you need to use Next.js env variables so that the Next.js build process can use them during the SSG process, so I'd suggest you to create a `.env` file with the `CONTENTFUL_ACCESS_TOKEN` variable and try again. If that token is going to be needed at runtime too then you'll need to set it in the Cloudflare dashboard as well.
> 
> I hope the above helps! please let me know 🙏

Ohh thank you! So it is possible to have some SSG pages using next on pages? I was making every route edge runtime because I couldn't get the data, but if I just have to use the next.js variables and can then use SSG, that is perfect. 

I'll try it out!

**Comment by Meagsy** [comment]
@dario-piotrowicz If I use cloudflare with github to build the next.js site, where do you put the environment variables so the secrets aren't exposed to build SSG pages?

**Comment by dario-piotrowicz** [comment]
If you're using github actions to build the app (and do the SSG) then you should add the token in the environment secrets: 
![Screenshot 2024-06-24 at 20 15 17](https://github.com/cloudflare/next-on-pages/assets/61631103/0308a749-d747-4fa5-84e5-678184db1b07)

If the token is also needed at runtime you should also set it for your app in the Cloudflare dashboard (or alternatively by using a `wrangler.toml` file)

**Comment by Meagsy** [comment]
@dario-piotrowicz Ah I'm not using Github actions, I just connected Cloudflare to github and when I push to master on Github, it automatically starts building on Cloudflare. Is there any way to get the cloudflare build to get the environment variables or are those only for runtime?

**Comment by dario-piotrowicz** [comment]
ah ok, I'm sorry I didn't catch that 😓 

yes then you should be able to add the secrets in the dashboard and those should be picked up by the Pages build pipeline (and should made available to the vercel build process)

and you're saying that that didn't work? 😕

**Comment by Meagsy** [comment]
@dario-piotrowicz Oh wow, it does work, thank you for your help! It originally wasn't working when I first made this post as I was using the contentful JS SDK library to fetch blog entries and that had issues which I thought were related to the environment variables. I've since then switched to using contentful's graphql instead and so now the static pages work! I didn't think to try static again after the switch. Appreciate you helping me understand all these options!

**Comment by thedewpoint** [comment]
@dario-piotrowicz just fyi i wasted about an hour with this same confusion, the docs don't explicitly call out the difference, my assumption here was that by putting all my variables in the dashboard, i was effecitvely transplanting my .env file and it was not needed at build time. I understand the distinction now but just reiterating that it might be helpful to make this explicit in the docs. (If it is I apologize I did not see it) this is where I read
https://developers.cloudflare.com/pages/configuration/build-configuration/#environment-variables
