### ISSUE TITLE
[🐛 Bug]: Cloudflare Pages invoking functions on request to static assets in Next.js

### ISSUE THREAD

**Issue by divrawat** [cloudflare/next-on-pages#824]
### Description

I have deployed a fully static next.js website (pages directory of next.js) to cloudflare pages and I have added _routes.json file to root of my project excluding static assets from function invocation.

But still my Dashboard is showing the requests made , but it is a fully static site.

Is functions directory creating cumpalsory since all my website is static. Here is my github repo - [https://github.com/divrawat/One-Blog](https://github.com/divrawat/One-Blog)

### Pages Deployment Method

None

### Would you like to help?

- [ ] Would you like to help fixing this bug?

**Comment by beadex** [comment]
can u share your logs? i might have same issue 🤔

**Comment by divrawat** [comment]
> can u share your logs? i might have same issue 🤔

How to view logs, I am not able to find where to see them

**Comment by divrawat** [comment]
Ok, I came to know that by default cloudflare pages route every request to pages or functions despite being static so creating _routes.json is compalsory and including exclude routes will work. I deleted previous deploys or build and added _routes.json and this time my _routes.json was picked up.

![0000000](https://github.com/cloudflare/next-on-pages/assets/83118748/6cdcb562-9f76-4387-be7d-d4bbf4b50f0b)
![54000](https://github.com/cloudflare/next-on-pages/assets/83118748/1802222d-6b08-4ace-959d-e4843faef8e7)
