### ISSUE TITLE
[🐛 Bug]: The following routes were not configured to run with the Edge Runtime 	  - /favicon.ico

### ISSUE THREAD

**Issue by pepsiamir** [cloudflare/next-on-pages#825]
### next-on-pages environment related information

<html>
<body>

14:01:33.999 | * branch            c849bf2e6e9d112973fc3b0512f736de72db18fb -> FETCH_HEAD
-- | --
14:01:34.000 |  
14:01:34.036 | HEAD is now at c849bf2 Update layout.jsx
14:01:34.037 |  
14:01:34.132 |  
14:01:34.132 | Using v2 root directory strategy
14:01:34.162 | Success: Finished cloning repository files
14:01:36.246 | Checking for configuration in a wrangler.toml configuration file (BETA)
14:01:36.247 |  
14:01:36.376 | No wrangler.toml file found. Continuing.
14:01:36.527 | Detected the following tools from environment: pnpm@8.7.1, nodejs@18.17.1
14:01:37.374 | Installing project dependencies: pnpm install
14:01:38.074 | Lockfile is up to date, resolution step is skipped
14:01:38.101 | Progress: resolved 1, reused 0, downloaded 0, added 0
14:01:38.198 | Packages: +426
14:01:38.198 | ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
14:01:39.109 | Progress: resolved 426, reused 0, downloaded 34, added 28
14:01:40.119 | Progress: resolved 426, reused 0, downloaded 103, added 97
14:01:41.119 | Progress: resolved 426, reused 0, downloaded 185, added 174
14:01:42.120 | Progress: resolved 426, reused 0, downloaded 302, added 293
14:01:43.154 | Progress: resolved 426, reused 0, downloaded 401, added 393
14:01:44.156 | Progress: resolved 426, reused 0, downloaded 426, added 425
14:01:44.255 | Progress: resolved 426, reused 0, downloaded 426, added 426, done
14:01:44.513 |  
14:01:44.514 | dependencies:
14:01:44.514 | + @hookform/resolvers 3.3.4
14:01:44.515 | + @mantine/hooks 7.1.6
14:01:44.515 | + @radix-ui/react-icons 1.3.0
14:01:44.515 | + @radix-ui/react-label 2.0.2
14:01:44.516 | + @radix-ui/react-slot 1.0.2
14:01:44.516 | + @vercel/analytics 1.1.1
14:01:44.516 | + axios 1.5.1
14:01:44.516 | + class-variance-authority 0.7.0
14:01:44.517 | + clsx 2.0.0
14:01:44.517 | + embla-carousel-react 8.0.1
14:01:44.517 | + framer-motion 10.16.4
14:01:44.517 | + lucide-react 0.288.0
14:01:44.518 | + next 14.2.4
14:01:44.518 | + next-intl 3.15.3
14:01:44.518 | + next-themes 0.2.1
14:01:44.518 | + popmotion 11.0.5
14:01:44.518 | + react 18.3.1
14:01:44.518 | + react-dom 18.3.1
14:01:44.518 | + react-hook-form 7.47.0
14:01:44.519 | + react-use-measure 2.1.1
14:01:44.519 | + react-wrap-balancer 1.1.1
14:01:44.519 | + sass 1.69.4
14:01:44.519 | + tailwind-merge 1.14.0
14:01:44.519 | + tailwindcss-animate 1.0.7
14:01:44.519 | + zod 3.22.4
14:01:44.519 |  
14:01:44.520 | devDependencies:
14:01:44.520 | + @tailwindcss/typography 0.5.10
14:01:44.520 | + @types/node 20.8.9
14:01:44.521 | + @types/react 18.2.32
14:01:44.521 | + @types/react-dom 18.2.14
14:01:44.521 | + autoprefixer 10.4.16
14:01:44.521 | + eslint 8.52.0
14:01:44.522 | + eslint-config-next 14.2.4
14:01:44.522 | + postcss 8.4.31
14:01:44.522 | + tailwindcss 3.3.5
14:01:44.522 | + typescript 5.2.2
14:01:44.522 |  
14:01:44.536 | Done in 6.8s
14:01:44.683 | Executing user command: npx @cloudflare/next-on-pages@1
14:01:47.295 | npm WARN exec The following package was not found and will be installed: @cloudflare/next-on-pages@1.12.0
14:01:52.912 | npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
14:01:52.995 | npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
14:01:53.431 | npm WARN deprecated are-we-there-yet@2.0.0: This package is no longer supported.
14:01:53.462 | npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
14:01:53.628 | npm WARN deprecated gauge@3.0.2: This package is no longer supported.
14:01:53.648 | npm WARN deprecated npmlog@5.0.1: This package is no longer supported.
14:01:53.670 | npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
14:01:53.713 | npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
14:01:54.105 | npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
14:01:54.281 | npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 \|\| >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
14:01:58.440 | ⚡️ @cloudflare/next-on-pages CLI v.1.12.0
14:01:58.869 | ⚡️ Detected Package Manager: npm (9.6.7)
14:01:58.870 | ⚡️ Preparing project...
14:01:58.870 |  
14:01:58.870 | ⚡️ The project is set up for pnpm but it is currently being run via npm this might lead to build errors, please be sure to use the same package manager your project uses when running @cloudflare/next-on-pages
14:01:58.870 |  
14:01:58.873 | ⚡️ Project is ready
14:01:58.873 | ⚡️ Building project...
14:02:00.709 | ▲  npm WARN exec The following package was not found and will be installed: vercel@34.3.1
14:02:02.831 | ▲  npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
14:02:02.857 | ▲  npm WARN
14:02:02.858 | ▲  deprecated npmlog@5.0.1: This package is no longer supported.
14:02:02.905 | ▲  npm
14:02:02.906 | ▲  WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
14:02:02.925 | ▲  npm WARN deprecated are-we-there-yet@2.0.0: This package is no longer supported.
14:02:02.937 | ▲  npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
14:02:02.984 | ▲  npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 \|\| >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
14:02:03.011 | ▲  npm WARN deprecated gauge@3.0.2: This package is no longer supported.
14:02:03.034 | ▲  npm WARN
14:02:03.035 | ▲  deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
14:02:04.220 | ▲  Vercel CLI 34.3.1
14:02:04.564 | ▲  Detected `pnpm-lock.yaml` version 6 generated by pnpm 8
14:02:04.579 | ▲  Installing dependencies...
14:02:05.101 | ▲  Lockfile is up to date, resolution step is skipped
14:02:05.160 | ▲  Already up to date
14:02:05.409 | ▲
14:02:05.427 | ▲  Done in 717ms
14:02:05.452 | ▲  Detected Next.js version: 14.2.4
14:02:05.465 | ▲  Running "pnpm run build"
14:02:05.908 | ▲  > minifolio-next-app@0.1.0 build /opt/buildhome/repo
14:02:05.908 | ▲  > next build
14:02:06.645 | ▲  Attention: Next.js now collects completely anonymous telemetry regarding usage.
14:02:06.646 | ▲  This information is used to shape Next.js' roadmap and prioritize features.
14:02:06.646 | ▲  You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
14:02:06.646 | ▲  https://nextjs.org/telemetry
14:02:06.723 | ▲  ▲ Next.js 14.2.4
14:02:06.800 | ▲
14:02:06.858 | ▲  Creating an optimized production build ...
14:02:24.479 | ▲  Browserslist: caniuse-lite is outdated. Please run:
14:02:24.480 | ▲  npx update-browserslist-db@latest
14:02:24.480 | ▲  Why you should do it regularly: https://github.com/browserslist/update-db#readme
14:02:31.375 | ▲  ✓ Compiled successfully
14:02:31.377 | ▲  Linting and checking validity of types ...
14:02:34.675 | ▲  ./app/about/page.jsx
14:02:34.676 | ▲  89:11  Warning: Using `<img>` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
14:02:34.676 | ▲  112:19  Warning: Using `<img>` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
14:02:34.676 | ▲
14:02:34.676 | ▲  ./app/services/[slug]/page.jsx
14:02:34.676 | ▲  100:9  Warning: Using `<img>` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
14:02:34.676 | ▲  123:17  Warning: Using `<img>` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
14:02:34.677 | ▲
14:02:34.677 | ▲  ./components/Designer/BlogArticle.jsx
14:02:34.677 | ▲  140:19  Warning: Using `<img>` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
14:02:34.677 | ▲  164:25  Warning: Using `<img>` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
14:02:34.677 | ▲  217:19  Warning: Using `<img>` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
14:02:34.677 | ▲
14:02:34.677 | ▲  ./components/Designer/BlogsHomeRender.jsx
14:02:34.677 | ▲  43:17  Warning: Using `<img>` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
14:02:34.678 | ▲
14:02:34.678 | ▲  ./components/Designer/ClientsHomeFilter.jsx
14:02:34.678 | ▲  13:15  Warning: Using `<img>` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
14:02:34.678 | ▲
14:02:34.678 | ▲  ./components/Designer/CourseSingle.jsx
14:02:34.678 | ▲  141:19  Warning: Using `<img>` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
14:02:34.678 | ▲  165:25  Warning: Using `<img>` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
14:02:34.678 | ▲  221:19  Warning: Using `<img>` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
14:02:34.679 | ▲
14:02:34.679 | ▲  ./components/Designer/CoursesHomeRender.jsx
14:02:34.679 | ▲  25:15  Warning: Using `<img>` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
14:02:34.679 | ▲
14:02:34.679 | ▲  ./components/Designer/FaqsHomeRender.jsx
14:02:34.679 | ▲  4:1  Warning: Prevent client components from being async functions. See: https://nextjs.org/docs/messages/no-async-client-component  @next/next/no-async-client-component
14:02:34.679 | ▲
14:02:34.680 | ▲  ./components/Designer/HeroHomeRender.jsx
14:02:34.680 | ▲  122:11  Warning: Using `<img>` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
14:02:34.680 | ▲
14:02:34.680 | ▲  ./components/Designer/PortfolioHomeFilterRender.jsx
14:02:34.680 | ▲  55:19  Warning: Using `<img>` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
14:02:34.680 | ▲
14:02:34.680 | ▲  ./components/Designer/PortfolioSingle.jsx
14:02:34.680 | ▲  140:19  Warning: Using `<img>` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
14:02:34.680 | ▲  164:25  Warning: Using `<img>` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
14:02:34.681 | ▲  217:19  Warning: Using `<img>` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
14:02:34.681 | ▲
14:02:34.681 | ▲  ./components/Designer/ProductSingle.jsx
14:02:34.681 | ▲  140:19  Warning: Using `<img>` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
14:02:34.681 | ▲  164:25  Warning: Using `<img>` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
14:02:34.681 | ▲  217:19  Warning: Using `<img>` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
14:02:34.681 | ▲
14:02:34.681 | ▲  ./components/Designer/ProductsHomeRender.jsx
14:02:34.681 | ▲  43:17  Warning: Using `<img>` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
14:02:34.682 | ▲
14:02:34.682 | ▲  ./components/Designer/SkillsHomeFilter.jsx
14:02:34.682 | ▲  17:15  Warning: Using `<img>` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
14:02:34.682 | ▲
14:02:34.682 | ▲  info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
14:02:36.739 | ▲  Collecting page data ...
14:02:38.084 | ▲  ⚠ Using edge runtime on a page currently disables static generation for that page
14:02:41.307 | ▲  Generating static pages (0/10) ...
14:02:41.954 | ▲  Generating static pages (2/10)
14:02:43.111 | ▲  Generating static pages (4/10)
14:02:43.880 | ▲  Generating static pages (7/10)
14:02:44.752 | ▲  ✓ Generating static pages (10/10)
14:02:44.943 | ▲  Finalizing page optimization ...
14:02:44.943 | ▲  Collecting build traces ...
14:02:47.783 | ▲
14:02:47.794 | ▲  Route (app)                              Size     First Load JS
14:02:47.794 | ▲  ┌ ○ /                                    3.22 kB         144 kB
14:02:47.795 | ▲  ├ ○ /_not-found                          875 B            88 kB
14:02:47.795 | ▲  ├ ƒ /about                               188 B          94.1 kB
14:02:47.795 | ▲  ├ ○ /blog                                188 B          94.1 kB
14:02:47.795 | ▲  ├ ƒ /blog/[slug]                         2.29 kB        96.2 kB
14:02:47.795 | ▲  ├ ƒ /contact                             24 kB           118 kB
14:02:47.795 | ▲  ├ ○ /courses                             188 B          94.1 kB
14:02:47.795 | ▲  ├ ƒ /courses/[slug]                      3.18 kB         104 kB
14:02:47.795 | ▲  ├ ○ /portfolio                           178 B           130 kB
14:02:47.795 | ▲  ├ ƒ /portfolio/[slug]                    2.29 kB        96.2 kB
14:02:47.796 | ▲  ├ ○ /products                            188 B          94.1 kB
14:02:47.796 | ▲  ├ ƒ /products/[slug]                     2.29 kB        96.2 kB
14:02:47.796 | ▲  ├ ○ /services                            188 B          94.1 kB
14:02:47.796 | ▲  └ ƒ /services/[slug]                     188 B          94.1 kB
14:02:47.796 | ▲  + First Load JS shared by all            87.1 kB
14:02:47.796 | ▲  ├ chunks/205-9aee323a51859813.js       31.5 kB
14:02:47.797 | ▲  ├ chunks/9d57a665-61e9b1e16823bf98.js  53.7 kB
14:02:47.797 | ▲  └ other shared chunks (total)          1.9 kB
14:02:47.797 | ▲
14:02:47.797 | ▲
14:02:47.797 | ▲  ○  (Static)   prerendered as static content
14:02:47.797 | ▲  ƒ  (Dynamic)  server-rendered on demand
14:02:47.797 | ▲
14:02:48.243 | ▲  Traced Next.js server files in: 357.607ms
14:02:48.366 | ▲  Created all serverless functions in: 121.771ms
14:02:49.235 | ▲  Collected static files (public/, static/, .next/static): 9.403ms
14:02:49.390 | ▲  Build Completed in .vercel/output [45s]
14:02:49.501 | ⚡️ Completed `npx vercel build`.
14:02:51.556 |  
14:02:51.557 | ⚡️ ERROR: Failed to produce a Cloudflare Pages build from the project.
14:02:51.557 | ⚡️
14:02:51.557 | ⚡️ 	The following routes were not configured to run with the Edge Runtime:
14:02:51.557 | ⚡️ 	  - /favicon.ico
14:02:51.557 | ⚡️
14:02:51.557 | ⚡️ 	Please make sure that all your non-static routes export the following edge runtime route segment config:
14:02:51.558 | ⚡️ 	  export const runtime = 'edge';
14:02:51.558 | ⚡️
14:02:51.558 | ⚡️ 	You can read more about the Edge Runtime on the Next.js documentation:
14:02:51.558 | ⚡️ 	  https://nextjs.org/docs/app/building-your-application/rendering/edge-and-nodejs-runtimes
14:02:51.558 |  
14:02:51.591 | Failed: Error while executing user command. Exited with error code: 1
14:02:51.606 | Failed: build command exited with code: 1
14:02:52.815 | Failed: error occurred while running build command

</body>
</html>

### Description

I have no idea where this error is coming from. I tried many different things and tried to revert my code the healthy state but the error doesn't go away.

### Pages Deployment Method

Pages CI (GitHub/GitLab integration)

### Would you like to help?

- [ ] Would you like to help fixing this bug?

**Comment by HakonHarnes** [comment]
Experiencing the same issue here. I tried to revert  to a commit that successfully deployed yesterday to no avail.

**Comment by jenslys** [comment]
Experiencing this aswell, happened out of the blue.
i had to delete `favicon.ico` to get it to deploy 💀

**Comment by LilaRest** [comment]
> Experiencing this aswell.
> 
> i had to delete `favicon.ico` to get it to deploy 💀

Uh that's ugly. Any idea of the source of the issue? It seems that this lib didn't received any release since 2 weeks? Could that come from a dependency?

**Comment by altrr2** [comment]
I have the sam issue, running 
```
npm create cloudflare@latest my-next-app -- --framework=next
cd my-next-app
npm run pages:build
```
would result in an error

if seems that the problem is related to the latest release of vercel:
```
npm uninstall -D vercel
npm i -D vercel@34.3.0
npm run pages:build
```
fixes the problem (for now)

**Comment by pepsiamir** [comment]
> Experiencing the same issue here. I tried to revert to a commit that successfully deployed yesterday to no avail.

I did the same thing. I tried to redeploy one of previous successful deployments but it didn't work.
I even removed my pages project and reployed but that didn't help either.

**Comment by pepsiamir** [comment]
> Experiencing this aswell.
> 
> i had to delete `favicon.ico` to get it to deploy 💀

I removed favicon.ico but still getting the same error.

**Comment by mihaip** [comment]
This appears to be a change in the Vercel CLI – 34.3.1 was just released and it picks up some changes to route generation: https://github.com/vercel/vercel/commit/3c9876e3d92fdbc2ad403eef0cb3469070ce0ecf and https://github.com/vercel/vercel/commit/9c5362b3d4ad29dcd56f0e7b6c31d02bf6a3f6f3

We were able to work around it by pinning the `vercel` dev dependency in our package.json to 34.3.0

**Comment by pepsiamir** [comment]
> This appears to be a change in the Vercel CLI – 34.3.1 was just released and it picks up some changes to route generation: [vercel/vercel@3c9876e](https://github.com/vercel/vercel/commit/3c9876e3d92fdbc2ad403eef0cb3469070ce0ecf) and [vercel/vercel@9c5362b](https://github.com/vercel/vercel/commit/9c5362b3d4ad29dcd56f0e7b6c31d02bf6a3f6f3)
> 
> We were able to work around it by pinning the `vercel` dev dependency in our package.json to 34.3.0

What is the solution for the Cloudflare Pages production deployment? I don't have this dependency in my package.json.
I'm using this build configuration on my project in Pages: npx @cloudflare/next-on-pages@1

**Comment by kalkih** [comment]
> > This appears to be a change in the Vercel CLI – 34.3.1 was just released and it picks up some changes to route generation: [vercel/vercel@3c9876e](https://github.com/vercel/vercel/commit/3c9876e3d92fdbc2ad403eef0cb3469070ce0ecf) and [vercel/vercel@9c5362b](https://github.com/vercel/vercel/commit/9c5362b3d4ad29dcd56f0e7b6c31d02bf6a3f6f3)
> > We were able to work around it by pinning the `vercel` dev dependency in our package.json to 34.3.0
> 
> What is the solution for the Cloudflare Pages production deployment? I don't have this dependency in my package.json. I'm using this build configuration on my project in Pages: npx @cloudflare/next-on-pages@1

Without knowing your build pipeline, adding vercel as a dependency in your project & pinning the version would probably do the job. npx would then look for the vercel dependency locally first before fetching it remotely i believe.

```bash
npm install vercel@34.3.0 --save-dev
```

**Comment by franjorub** [comment]
I followed the nextjs tutorial for cloudflare pages using c3. I had the same issue and fixing @vercel to 34.3.0 worked

**Comment by james-elicx** [comment]
This should now be fixed in v1.12.1.

**Comment by franjorub** [comment]
hi @james-elicx  thank you ! I have a question. for a project already generated with c3 should be enough upgrading @cloudflare/next-on-pages to v1.12.1 ?

**Comment by franjorub** [comment]
> hi @james-elicx thank you ! I have a question. for a project already generated with c3 should be enough upgrading @cloudflare/next-on-pages to v1.12.1 ?

tested with @clouldflare/next-on-pages@1.12.1 and vercel@34.3.1 and worked 🥳

**Comment by okcodes** [comment]
I fixed it by moving `src/app/favicon.ico` to `public/favicon.ico`, I didn't need to install anything or modify my `package.json`.

**Comment by MuneerAhmed03** [comment]
> I fixed it by moving `src/app/favicon.ico` to `public/favicon.ico`, I didn't need to install anything or modify my `package.json`.

worked for me

**Comment by mzsenevi** [comment]
> > hi @james-elicx thank you ! I have a question. for a project already generated with c3 should be enough upgrading @cloudflare/next-on-pages to v1.12.1 ?
> 
> tested with @clouldflare/next-on-pages@1.12.1 and vercel@34.3.1 and worked 🥳

I just changed the "@clouldflare/next-on-pages@1.12.1" version and it worked!! 🥳
