### ISSUE TITLE
[🐛 Bug]: Type declarations for @cloudflare/next-on-pages's `getRequestContext` and `getOptionalRequestContext` missing

### ISSUE THREAD

**Issue by chrisp-code** [cloudflare/next-on-pages#840]
### Description

Starting at [version 0.0.0-78accfd](https://www.npmjs.com/package/@cloudflare/next-on-pages/v/0.0.0-78accfd?activeTab=code) TypeScript declarations for `packages/next-on-pages/tsconfig.api.json` are no longer being built.

It looks to have been introduced in #828. I haven't confirmed, but the change to [package.json](https://github.com/cloudflare/next-on-pages/blob/main/packages/next-on-pages/package.json#L23) specifying multiple projects in one `tsc` command appears to be the likely cause. From my understanding, specifying multiple projects to be built in one command is only supported through  `build` (ie. `tsc -b tsconfig.api.json tsconfig.fetch-handler.json`) rather than `project`.

Getting error:
```
Could not find a declaration file for module '@cloudflare/next-on-pages'. '/node_modules/.pnpm/@cloudflare+next-on-pages@1.13.0_@cloudflare+workers-types@4.20240725.0_vercel@34.2.3_wrangle_33tq7rpr3o3a4zzjsenxncpldi/node_modules/@cloudflare/next-on-pages/dist/api/index.js' implicitly has an 'any' type.
```

### Pages Deployment Method

None

### Would you like to help?

- [ ] Would you like to help fixing this bug?

**Comment by dario-piotrowicz** [comment]
Thanks a lot for the issue @chrisp-code 🙂 

Yes, sorry this is a regression introduced in the latest release, I failed to notice the incorrect `tsc` command that we merged in! 😓 

A fix is on it's way, sorry for the inconvenience 🙇

**Comment by dario-piotrowicz** [comment]
It should be fixed in https://www.npmjs.com/package/@cloudflare/next-on-pages/v/1.13.1 now 🙂
