### ISSUE TITLE
[🐛 Bug]: "Error: Invariant: buildID is required" with next > 14.2.7

### ISSUE THREAD

**Issue by davidar** [cloudflare/next-on-pages#876]
### next-on-pages environment related information

```
System:
        Platform: linux
        Arch: x64
        Version: #26~22.04.1-Ubuntu SMP Thu Jul 11 22:33:04 UTC 2024
        CPU: (2) x64 AMD EPYC 7763 64-Core Processor
        Memory: 8 GB
        Shell: /bin/bash
Package Manager Used: npm (10.8.2)

Relevant Packages:
        @cloudflare/next-on-pages: 1.13.2
        vercel: 37.4.2
        next: 14.2.8
```

### Description

See https://www.answeroverflow.com/m/1281077192154943571

Since next 14.2.8, next-on-pages sites have started having internal server errors, the only error log is "Error: Invariant: buildID is required". This occurs both on deployed pages sites and locally with `wrangler pages dev`. It doesn't occur with `next start`, or with next versions 14.2.7 and below.

### Reproduction

See https://github.com/compute-toys/compute.toys/pull/126 for an example of the issue.

### Pages Deployment Method

Pages CI (GitHub/GitLab integration)

### Pages Deployment ID

https://1463c917.compute-toys.pages.dev

### Additional Information

All I can tell is that the error is coming from https://github.com/vercel/next.js/blob/v14.2.8/packages/next/src/server/future/normalizers/request/next-data.ts#L12 but I don't know what has changed in recent versions of next that triggers it.

### Would you like to help?

- [x] Would you like to help fixing this bug?

**Comment by Ambroos** [comment]
I'm 90% sure this is the cause: https://github.com/vercel/next.js/pull/65426

Specifically, Next now requires env var `__NEXT_BUILD_ID` to be set in Edge environments, containing the build ID. Alternatively on build, `process.env.__NEXT_BUILD_ID` can be replaced with the actual build ID to fix this if I'm not mistaken.

**Comment by Ambroos** [comment]
You can use this pnpm patch on next-on-pages@1.13.2 to get things working again. I'm working on the matching PR.

```diff
diff --git a/dist/index.js b/dist/index.js
index 4cb150acd490b4ec5c6d1884b2f7819ef6866dc2..df72cab2983b7032c945c074aaacaf6ebebfc755 100644
--- a/dist/index.js
+++ b/dist/index.js
@@ -12907,6 +12907,10 @@ async function buildFile(contents, filePath, { relativeTo } = {}) {
     )
   );
   await (0, import_promises8.mkdir)((0, import_node_path7.dirname)(filePath), { recursive: true });
+  const nextBuildID = await (0, import_promises3.readFile)(
+    (0, import_path4.resolve)('.next', 'BUILD_ID'),
+    'utf8',
+  );
   await (0, import_esbuild2.build)({
     stdin: { contents },
     target: "es2022",
@@ -12915,7 +12919,10 @@ async function buildFile(contents, filePath, { relativeTo } = {}) {
     bundle: true,
     external: ["node:*", `${relativeNopDistPath}/*`, "*.wasm", "cloudflare:*"],
     minify: true,
-    plugins: [builtInModulesPlugin]
+    plugins: [builtInModulesPlugin],
+    define: {
+      'process.env.__NEXT_BUILD_ID': JSON.stringify(nextBuildID),
+    },
   });
 }
 function getRelativePathToAncestor(opts) {
```

**Comment by davidar** [comment]
@Ambroos Thanks! That patch fixes the issue locally for me
